// The words of a conversation column (DESIGN §5.5, §5.12 items 10–17). What people and agents wrote is never here
// and never translated; lines the host's smurg wrote arrive as wire catalogue references (lib/errors renderWireText).
import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

export const t = defineStrings(
  'conversation',
  {
    // ---- the column
    loading: 'Loading the conversation…',
    loadError: 'The conversation could not be loaded: {message}',
    'load.retry': 'Try again',
    'log.label': 'Conversation: {title}',
    'earlier.load': 'Load earlier messages',
    'earlier.loading': 'Loading earlier messages…',
    'earlier.start': 'This is the start of the conversation.',
    newActivity: 'New activity',
    'agent.name': 'Claude',
    'person.you': '{name} (you)',
    actionFailed: 'That did not work: {message}',
    attempt: 'Attempt {number}',

    // ---- header strip
    'strip.label': 'About this session',
    'responsible.is': 'Responsible: {name}',
    'responsible.nobody': 'Responsible: nobody',
    'responsible.menu': 'Who is responsible for this session',
    'responsible.option': '{name} · {role}',
    'responsible.optionBusy': { one: '{name} · {role} · responsible for {count} session', other: '{name} · {role} · responsible for {count} sessions' },
    'responsible.none': 'No one: everyone watches',
    'where.main': 'Main workspace',
    'where.mainTitle': 'Works in the shared main workspace. Browse it in code mode',
    'where.worktree': 'Worktree {branch}: browse its files in code mode',
    'where.unknown': 'a worktree',
    'mode.title': 'Permission mode: {mode}',
    'mode.fixed': 'Reads code, writes only the spec and the plan',
    'mode.fixedTitle': 'Permission mode: reads code, writes only the spec and the plan. A discussion cannot do more.',
    'mode.dialog': 'What this session may do without asking',
    'mode.choice': 'Permission mode',
    'mode.onlyDrive': 'The host and members with agent access can change this.',
    'mode.rules': 'Always allowed in this session',
    'mode.rules.none': 'Nothing is always allowed here. "Always allow this kind" on a permission request adds to this list.',
    'mode.rules.session': 'this session',
    'mode.rules.topic': 'every session of this topic',
    'mode.rules.entry': '{scope} · allowed by {name}',
    'mode.rules.remove': 'Remove {rule}',
    'mode.rules.loading': 'Loading what is always allowed…',
    'mode.rules.failed': 'Could not load what is always allowed: {message}',
    'mode.host': { one: "The host's own Claude Code rules apply too: agents here run {count} kind of command without asking.", other: "The host's own Claude Code rules apply too: agents here run {count} kinds of commands without asking." },
    'mode.host.show': 'Show them',
    'mode.close': 'Done',
    stop: 'Stop',
    'stop.title': 'Stop what the agent is doing now. The session stays open.',
    'menu.rename': 'Rename session…',
    'menu.end': 'End session…',
    'rename.title': 'Rename this session',
    'rename.label': 'Name',
    'rename.hint': 'Everyone sees this name.',
    'rename.save': 'Rename',
    'end.title': 'End {title}?',
    'end.body': 'The agent stops and the session takes no more messages. The conversation stays readable.',
    'end.item': 'Its worktree stays with the work item.',
    'end.keep': 'Keep its worktree',
    'end.keepHint': 'Without this, the worktree and the changes in it that were not merged are deleted.',
    'end.confirm': 'End session',
    cancel: 'Cancel',

    // ---- pieces of the conversation
    'message.role': '{role}',
    'message.suggestion': 'suggestion, accepted by {name}',
    'message.suggestionEdited': 'suggestion, edited and accepted by {name}',
    'message.cleaned': 'Hidden characters were removed',
    'message.delivery.queued': 'Claude reads it when it starts again',
    'message.delivery.cancelled': 'Not delivered: its sender left',
    'message.origin.selection': 'from a selection in the editor',
    'message.origin.follow-up': 'about a result report',
    'message.origin.revise': 'about the spec or the plan',
    'smurg.by': 'smurg told Claude, asked by {name}',
    'smurg.own': 'smurg told Claude',
    'smurg.show': 'What smurg wrote',
    'text.aborted': 'Stopped before it was finished.',
    'text.truncated': 'This text was too long: the rest is not kept.',
    // The time follows each of these on the same line ("… · 05:25:15"): no full stop.
    'turn.interrupted': 'The agent was stopped',
    'turn.interruptedBy': '{name} stopped the agent',
    'turn.error': 'The agent stopped with an error',
    'turn.max-turns': 'The agent reached its limit of steps for one turn',
    'turn.budget': 'The agent reached its spending limit for one turn',
    'notice.retry': 'Try again',
    'notice.restart': "Restart this session's agent now",
    'notice.hostOnly': 'Only the host can try again.',
    thinking: 'Claude is thinking…',
    redact: 'Remove this entry…',
    'redact.result': 'Remove its result…',
    'row.failed': 'This entry cannot be shown.',
    'notice.review': 'Review the project settings',

    // ---- tool cards (a verb has three forms: done, running, and `.call` for a call that has not had its effect:
    // it waits for permission, it failed, or its turn ended first)
    'tool.read': 'Read',
    'tool.read.running': 'Reading',
    'tool.read.call': 'Read of',
    'tool.edit': 'Edited',
    'tool.edit.running': 'Editing',
    'tool.edit.call': 'Edit of',
    'tool.create': 'Created',
    'tool.create.running': 'Creating',
    'tool.create.call': 'New file',
    'tool.run': 'Ran',
    'tool.run.running': 'Running',
    'tool.run.call': 'Command',
    'tool.search': 'Searched',
    'tool.search.running': 'Searching',
    'tool.search.call': 'Search for',
    'tool.fetch': 'Fetched',
    'tool.fetch.running': 'Fetching',
    'tool.fetch.call': 'Fetch of',
    'tool.task': 'Subagent',
    'tool.task.running': 'Subagent working',
    'tool.task.call': 'Subagent',
    'tool.smurg': 'Checked with smurg',
    'tool.smurg.running': 'Checking with smurg',
    'tool.smurg.call': 'Check with smurg',
    'tool.todo': 'Updated its to-do list',
    'tool.todo.running': 'Updating its to-do list',
    'tool.todo.call': 'Update of its to-do list',
    'tool.other': 'Used {name}',
    'tool.other.running': 'Using {name}',
    'tool.other.call': 'Use of {name}',
    'tool.outside': 'a file outside the workspace',
    'tool.failed': 'failed',
    'tool.exit': 'exit {code}',
    'tool.matches': { one: '{count} match', other: '{count} matches' },
    'tool.running': 'running',
    // Short, as the card under it says it ("waiting 3 sec"): in a narrow column the line's room is the command's.
    'tool.waiting': 'waiting',
    'tool.unfinished': 'not finished',
    'tool.noDetails': 'Nothing more to show.',
    'tool.truncated': 'The rest was cut off.',
    'tool.open': 'Open in editor',
    'tool.reads': { one: '{count} file', other: '{count} files' },
    'tool.readsIn': { one: '{count} file in {dir}', other: '{count} files in {dir}' },
    'tool.reads.failed': '{count} failed',
    'tool.reads.unfinished': '{count} not finished',
    'tool.steps': { one: '{count} step', other: '{count} steps' },
    'diff.label': 'Changes to {path}',
    'diff.labelPlain': 'Changes',
    'diff.added': 'added',
    'diff.removed': 'removed',

    // ---- cards: shared
    'card.waiting': 'waiting {age}',
    'card.withdrawn.stopped': 'Not answered: the agent was stopped.',
    'card.withdrawn.stoppedBy': 'Not answered: {name} stopped the agent.',
    'card.withdrawn.ended': 'Not answered: the session ended.',
    'card.withdrawn.endedBy': 'Not answered: {name} ended the session.',
    'card.withdrawn.failed': 'Not answered: the agent stopped with an error.',
    'card.withdrawn.restarted': 'Not answered: smurg was restarted. Claude asks again when the session continues.',
    'card.missing': 'Loading this card…',
    'card.gone': "The host's computer no longer keeps this card.",
    'card.escalated': '{name} has not answered for {age}.',
    'card.late.answered': '{name} already submitted an answer.',
    'card.late.allowed': '{name} already allowed this.',
    'card.late.denied': '{name} already denied this.',
    'card.late.decided': '{name} already decided this suggestion.',
    'card.late.withdrawn': 'This is no longer open.',
    'card.late.someone': 'Someone',

    // ---- question card
    'q.title': 'Question from Claude',
    'q.voted': '{voted} of {eligible} voted',
    'q.allVoted': { one: 'The {count} person who can vote has voted', other: 'All {count} voted' },
    'q.part': 'Question {number} of {count}',
    'q.vote': 'Your vote',
    'q.voteFor': 'Your vote: {question}',
    'q.multi': 'Choose all that apply.',
    'q.leading': 'Leading',
    'q.votesFor': { one: '{count} vote: {names}', other: '{count} votes: {names}' },
    'q.noVotes': 'No votes',
    'q.other': 'Other',
    'q.other.label': 'Your own answer',
    'q.other.placeholder': 'Write your own answer',
    'q.other.save': 'Vote for this',
    'q.other.needText': 'An answer of your own needs a text.',
    'q.other.by': '{name}: {text}',
    'q.comments': { one: '{count} comment', other: '{count} comments' },
    'q.comments.none': 'No comments yet',
    'q.comment.label': 'Add a comment',
    'q.comment.placeholder': 'Add a comment. Type @ to mention someone',
    'q.comment.send': 'Comment',
    'q.comment.note': 'Comments are for the team. Claude does not read them.',
    'q.addToNote': 'Add to the note',
    'q.decide.responsible': 'You decide: you are responsible for this session.',
    'q.decide.opener': 'You decide: nobody is assigned to this session, and you opened it.',
    'q.decide.host': 'You decide: nobody else is assigned and you are the host.',
    'q.decide.other': '{name} decides (responsible for this session). Your vote and comments are visible to everyone.',
    'q.decide.otherOpener': '{name} decides: nobody is assigned to this session. Your vote and comments are visible to everyone.',
    'q.decide.viewer': 'You are watching. Viewers do not vote. {name} decides.',
    'q.decide.nobody': 'Nobody can decide this right now: the host is not here.',
    'q.decide.hostToo': '{name} decides. As the host you can submit the answer too.',
    'q.decide.escalated': '{name} decides and has not answered for {age}. You can submit for them.',
    'q.seen': '{name} has seen this question.',
    'q.notSeen': '{name} has not opened this question yet.',
    'q.advice': 'Your click on an option sets your vote and the answer. You can submit now; votes are advice.',
    'q.tie': 'The vote is tied. Choose the answer yourself.',
    'q.nobodyVoted': 'Nobody has voted yet. You can still choose and submit.',
    'q.answer': 'Answer to submit',
    'q.answerFor': 'Answer to submit: {question}',
    'q.answer.none': 'No answer chosen yet',
    'q.answer.choose': 'Choose an answer',
    'q.answer.different': 'Submit a different answer',
    'q.answer.otherOf': 'Other, by {name}: {text}',
    'q.answer.otherOwn': 'Other: an answer in my own words',
    'q.answer.otherText': 'The answer to send',
    'q.submit': 'Submit answer',
    'q.submitAll': 'Submit answers',
    'q.submitFor': 'Submit for {name}',
    'q.note.label': 'Note for Claude (optional)',
    'q.note.placeholder': 'Note for Claude (optional). Only this note and the answer reach Claude',
    'q.editor': "You decide among Claude's options. An answer in your own words needs {names}.",
    'q.askSubmit': 'Ask them to submit',
    'q.askSubmit.text': '{mentions} please submit the answer to this question: I cannot submit one in my own words.',
    'q.askSubmit.sent': 'Asked {names} in a comment.',
    'q.remind': 'Remind those who have not voted',
    'q.remind.sent': 'Reminded.',
    'q.previous': { one: 'Asked before: {count} vote for "{label}"', other: 'Asked before: {count} votes for "{label}"' },
    'q.settled.answered': 'Answered: {answer}',
    'q.settled.tally': { one: '{count} vote', other: '{count} votes' },
    'q.settled.by': 'submitted by {name}, {time}',
    'q.settled.byFor': 'submitted by {name} for {decider}, {time}',
    'q.settled.note': 'Note for Claude: {note}',
    'q.settled.show': 'Show the votes and comments',
    'q.settled.otherBy': '{text} (by {name})',

    // ---- permission card
    'perm.title.command': 'Claude asks for permission to run a command',
    'perm.title.edit': 'Claude asks for permission to edit a file',
    'perm.title.fetch': 'Claude asks for permission to fetch a web address',
    'perm.title.outside': 'Claude asks for permission to use a file outside the workspace',
    'perm.title.other': 'Claude asks for permission to use {tool}',
    'perm.outside': 'a file outside the workspace',
    'perm.input': 'What {tool} was given',
    'perm.where.main': 'In the main workspace',
    'perm.where.worktree': 'In the worktree {branch}',
    'perm.reason': "Claude Code's reason: {reason}",
    'perm.gate.writes-settings-script':
      "smurg asks because this command changes a place where this folder's Claude Code project settings keep a script they run (the script itself, or a folder that holds it). Those scripts run as the host.",
    'perm.gate.may-reach-settings-script': "smurg asks because this folder's Claude Code project settings run scripts, and smurg cannot tell whether this command leaves them alone.",
    'perm.more': { one: '{count} line: scroll this box to read all of it.', other: '{count} lines: scroll this box to read all of them.' },
    'perm.readFirst': 'Allow is available once you have scrolled to the end of what is asked.',
    'perm.allow': 'Allow once',
    'perm.always': 'Always allow this kind',
    'perm.deny': 'Deny',
    'perm.deny.label': 'What should Claude do instead? (optional)',
    'perm.deny.confirm': 'Deny',
    'perm.scope': 'Where "always" applies',
    'perm.scope.session': 'in this session',
    'perm.scope.topic': 'in every session of this topic',
    'perm.kind.bash': '"This kind" is: commands that start with {pattern}. It also covers the same command after Claude changes the files it runs.',
    'perm.kind.fetch': '"This kind" is: fetching from {host}.',
    'perm.noAlways.interpreter': '{command} can run any code: it cannot be always allowed.',
    'perm.noAlways.fetches-code': '{command} downloads and runs code: it cannot be always allowed.',
    'perm.noAlways.one-word': 'A command of one word cannot be always allowed.',
    'perm.noAlways.host-only': 'What only the host can allow cannot be always allowed.',
    'perm.noAlways.no-suggestion': 'This kind of request cannot be always allowed.',
    'perm.inbox.mine': 'It is in your inbox: you are responsible. The host and members with agent access can answer too.',
    'perm.inbox.theirs': "It is in {name}'s inbox (responsible). You can answer too: the host and members with agent access may.",
    'perm.inbox.all': 'It is in the inbox of the host and of every member with agent access.',
    'perm.hostOnly': 'Only the host can allow this: it reaches beyond the shared project.',
    'perm.hostOnly.mine': 'Only you, the host, can allow this: it reaches beyond the shared project.',
    'perm.waiting.responsible': 'Waiting for {name} (responsible), the host or a member with agent access. Your role cannot allow this.',
    'perm.waiting.all': 'Waiting for the host or a member with agent access. Your role cannot allow this.',
    'perm.settled.allowed': 'Allowed once by {name}, {time}',
    'perm.settled.always.session': 'Allowed, and always for {rule} in this session, by {name}, {time}',
    'perm.settled.always.topic': 'Allowed, and always for {rule} in every session of this topic, by {name}, {time}',
    'perm.settled.denied': 'Denied by {name}, {time}',
    'perm.settled.deniedWith': 'Denied by {name}, {time}: "{message}"',

    // ---- suggestion card
    'sug.title': 'Suggestion from {name}',
    'sug.cleaned': 'Hidden characters were removed.',
    'sug.source': 'About {path}, lines {range}',
    'sug.sourceLine': 'About {path}, line {line}',
    'sug.accept': 'Accept',
    'sug.editAccept': 'Edit and accept',
    'sug.acceptEdited': 'Accept this text',
    'sug.reject': 'Reject',
    'sug.reject.label': 'Why? (optional; {name} reads it)',
    'sug.reject.confirm': 'Reject',
    'sug.reaches': 'It reaches the agent only when someone accepts it.',
    'sug.edit': 'Edit',
    'sug.edit.label': 'Your suggestion',
    'sug.edit.save': 'Save',
    'sug.withdraw': 'Withdraw',
    'sug.waiting.responsible': 'Waiting for {name} (responsible). The host and members with agent access can accept it too.',
    'sug.waiting.all': 'Waiting for the host or a member with agent access.',
    'sug.settled.accepted': 'Accepted by {name}, {time}',
    'sug.settled.acceptedEdited': 'Edited and accepted by {name}, {time}',
    'sug.settled.rejected': 'Rejected by {name}, {time}',
    'sug.settled.rejectedWith': 'Rejected by {name}, {time}: "{reason}"',
    'sug.settled.withdrawn': 'Withdrawn by {name}',
    'sug.settled.closed.session-ended': 'Closed: the session ended',
    'sug.settled.closed.author-kicked': 'Closed: {name} was removed from the workspace',
    'sug.settled.closed.author-demoted': "Closed: {name}'s role no longer allows suggestions",
    'sug.settled.closed.topic-archived': 'Closed: the topic was archived',

    // ---- next-step cards
    'next.spec': 'The spec draft is ready. Next: edit it together or ask for changes. When it is right:',
    'next.spec.generate': 'Generate plan',
    'next.spec.who': '{names} can generate the plan.',
    'next.spec.open': 'Open spec',
    'next.plan': 'The plan is ready. Next: check who is responsible, then start.',
    'next.plan.open': 'Open plan',
    'next.report': 'The result report is written.',
    'next.report.item': 'The result report of {item} is written.',
    'next.report.reviewers': '{names} reviews it.',
    'next.report.anyone': 'Anyone but a viewer can review it.',
    'next.report.open': 'Open report',

    // ---- status bar
    'status.starting': 'Claude is starting…',
    'status.writing': 'Claude is writing',
    'status.working': 'Claude is working',
    'status.thinking': 'Claude is thinking',
    'status.compacting': 'Claude is shortening the conversation',
    'status.question': 'Claude is waiting for an answer',
    'status.permission': 'Claude is waiting for permission',
    'status.age': '· {age}',
    'status.show': 'Show it',
    'status.idle': 'Claude is idle.',
    'status.done': 'Done. Claude answers follow-ups here and in the report.',
    'status.stalled': 'Stopped without a report.',
    'status.stalled.restart': 'Paused: smurg was restarted.',
    'status.stalled.stopped': 'Stopped by a person, no report.',
    'status.stalled.error': 'Stopped on an error, no report.',
    'status.stalled.continue': 'Continue',
    'status.failed': 'The agent stopped with an error.',
    'status.failed.retry': 'Try again',
    'status.ended': 'This session has ended.',
    'status.account.usage-limit': "The host's Claude account reached a usage limit.",
    'status.account.logged-out': "Claude Code is not logged in on the host's computer.",
    'status.login.check': 'Check login again',
    'status.login.ok': "Claude Code is logged in on the host's computer.",
    'status.login.unknown': 'The login could not be checked.',
    'status.spec': 'Write the spec now',
    'status.spec.title': 'Ask Claude for the first draft of the spec',
    'status.fresh': 'Start a fresh conversation',
    'status.fresh.title': 'This discussion is long. A new one starts from the spec and the plan as they are now.',
    'status.catchingUp': 'Catching up…',

    // ---- composer
    'composer.message': 'Message Claude · {title}',
    'composer.suggest': 'Suggest to Claude · {title}',
    'composer.inTopic': '{title} · {topic}',
    'composer.send': 'Send',
    'composer.sendSuggestion': 'Send suggestion',
    'composer.hint': 'Enter to send · Shift+Enter for a new line',
    'composer.hint.working': 'Claude reads it at its next step · Enter to send',
    'composer.hint.question': 'Claude is waiting for the answer above and reads messages after it.',
    'composer.goes.one': 'Goes to {name} as a suggestion. It reaches the agent only when accepted.',
    'composer.goes.many': 'Goes to {names} as a suggestion. It reaches the agent only when accepted.',
    'composer.goes.responsible': 'Goes to {names} as a suggestion: you are responsible, but your role cannot message agents.',
    'composer.goes.nobody': 'Goes to the host as a suggestion. It reaches the agent only when accepted.',
    'composer.viewer': 'As a viewer you can watch this session. You cannot send messages, make suggestions or vote.',
    'composer.ended': 'This session has ended. It takes no more messages.',
    'composer.offline': 'The host is offline: nothing can be sent right now.',
    'composer.blank': 'Write something first.',
    'composer.tooLong': 'This is too long: at most {max} characters.',
    'composer.failed': 'Not sent: {message}',
    'composer.suggested': 'Suggestion sent.',
    'composer.source': '{path}, lines {range}',
    'composer.sourceLine': '{path}, line {line}',
    'composer.source.open': 'Open {path} at line {line}',
    'composer.source.remove': 'Remove the attached code',
    'composer.mentions': 'People to mention',
    'composer.mention.option': '{name} · {role}',

    // ---- "Send to agent" from the editor
    'select.title': 'Send to which session?',
    'select.body.message': 'The selected lines go into the message box of the session you choose.',
    'select.body.suggestion': 'The selected lines become a suggestion for the session you choose.',
    'select.none': 'There is no agent session to send it to.',
    'select.viewer': 'As a viewer you cannot send text to an agent.',
    'select.gone': 'That session no longer exists.',
    'select.ended': 'That session has ended.',
    'select.sent': 'Sent to {title}.',
    'select.failed': 'Not sent: {message}',
  },
  zhTW,
);
