// Traditional Chinese of the `conversation` namespace: exactly the keys of strings.ts (the English table defines them).
// Only strings.ts imports this file.
export const zhTW = {
  // ---- the column
  loading: '正在載入對話…',
  loadError: '無法載入對話：{message}',
  'load.retry': '再試一次',
  'log.label': '對話：{title}',
  'earlier.load': '載入較早的訊息',
  'earlier.loading': '正在載入較早的訊息…',
  'earlier.start': '這是對話的開頭。',
  newActivity: '有新動態',
  'agent.name': 'Claude',
  'person.you': '{name}（你）',
  actionFailed: '沒有成功：{message}',
  attempt: '第 {number} 次嘗試',

  // ---- header strip
  'strip.label': '這個 session 的資訊',
  'responsible.is': '負責人：{name}',
  'responsible.nobody': '負責人：無',
  'responsible.menu': '這個 session 的負責人',
  'responsible.option': '{name} · {role}',
  'responsible.optionBusy': '{name} · {role} · 負責 {count} 個 session',
  'responsible.none': '不指派：大家一起看',
  'where.main': '主工作區',
  'where.mainTitle': '在共用的主工作區工作。到手寫 code 模式瀏覽',
  'where.worktree': 'worktree {branch}：到手寫 code 模式瀏覽它的檔案',
  'where.unknown': '某個 worktree',
  'mode.title': '權限模式：{mode}',
  'mode.fixed': '可讀程式碼，只能寫 spec 和計畫',
  'mode.fixedTitle': '權限模式：可讀程式碼，只能寫 spec 和計畫。討論不能做更多事。',
  'mode.dialog': '這個 session 不必先問就能做的事',
  'mode.choice': '權限模式',
  'mode.onlyDrive': '主人和「可使用 agent」的成員可以變更。',
  'mode.rules': '這個 session 一律允許的類型',
  'mode.rules.none': '這裡沒有一律允許的類型。在權限請求上按「一律允許這類」就會加到這份清單。',
  'mode.rules.session': '這個 session',
  'mode.rules.topic': '這個主題的所有 session',
  'mode.rules.entry': '{scope} · 由 {name} 允許',
  'mode.rules.remove': '移除 {rule}',
  'mode.rules.loading': '正在載入一律允許的類型…',
  'mode.rules.failed': '無法載入一律允許的類型：{message}',
  'mode.host': '主人自己的 Claude Code 規則也適用：這裡的 agent 有 {count} 類指令不必先問就會執行。',
  'mode.host.show': '顯示這些規則',
  'mode.close': '完成',
  stop: '停止',
  'stop.title': '停止 agent 現在正在做的事，session 仍然保留。',
  'menu.rename': '重新命名 session…',
  'menu.end': '結束 session…',
  'rename.title': '重新命名這個 session',
  'rename.label': '名稱',
  'rename.hint': '所有人都會看到這個名稱。',
  'rename.save': '重新命名',
  'end.title': '要結束「{title}」嗎？',
  'end.body': 'agent 會停止，這個 session 不再接受訊息。對話內容仍然可以閱讀。',
  'end.item': '它的 worktree 會留給這個工作項目。',
  'end.keep': '保留它的 worktree',
  'end.keepHint': '不勾選的話，這個 worktree 和裡面尚未合併的變更都會被刪除。',
  'end.confirm': '結束 session',
  cancel: '取消',

  // ---- pieces of the conversation
  'message.role': '{role}',
  'message.suggestion': '建議，由 {name} 採用',
  'message.suggestionEdited': '建議，由 {name} 修改後採用',
  'message.cleaned': '已移除看不見的字元',
  'message.delivery.queued': 'Claude 重新啟動後會讀到',
  'message.delivery.cancelled': '未送達：傳送的人已離開',
  'message.origin.selection': '來自編輯器裡選取的內容',
  'message.origin.follow-up': '關於一份結果報告',
  'message.origin.revise': '關於 spec 或計畫',
  'smurg.by': '應 {name} 的要求，smurg 告訴 Claude',
  'smurg.own': 'smurg 告訴 Claude',
  'smurg.show': 'smurg 寫的內容',
  'text.aborted': '還沒寫完就被停止了。',
  'text.truncated': '這段文字太長，後面的部分沒有保留。',
  'turn.interrupted': 'agent 已被停止',
  'turn.interruptedBy': '{name} 停止了 agent',
  'turn.error': 'agent 因錯誤而停止',
  'turn.max-turns': 'agent 已達到單一回合的步驟上限',
  'turn.budget': 'agent 已達到單一回合的花費上限',
  'notice.retry': '再試一次',
  'notice.restart': '立刻重新啟動這個 session 的 agent',
  'notice.hostOnly': '只有主人可以再試一次。',
  thinking: 'Claude 正在思考…',
  redact: '移除這則內容…',
  'redact.result': '移除它的結果…',
  'row.failed': '這則內容無法顯示。',
  'notice.review': '檢視專案設定',

  // ---- tool cards
  'tool.read': '讀取',
  'tool.read.running': '正在讀取',
  'tool.read.call': '讀取',
  'tool.edit': '編輯',
  'tool.edit.running': '正在編輯',
  'tool.edit.call': '編輯',
  'tool.create': '建立',
  'tool.create.running': '正在建立',
  'tool.create.call': '建立檔案',
  'tool.run': '執行',
  'tool.run.running': '正在執行',
  'tool.run.call': '指令',
  'tool.search': '搜尋',
  'tool.search.running': '正在搜尋',
  'tool.search.call': '搜尋',
  'tool.fetch': '擷取',
  'tool.fetch.running': '正在擷取',
  'tool.fetch.call': '擷取',
  'tool.task': '子 agent',
  'tool.task.running': '子 agent 工作中',
  'tool.task.call': '子 agent',
  'tool.smurg': '向 smurg 確認',
  'tool.smurg.running': '正在向 smurg 確認',
  'tool.smurg.call': '向 smurg 確認',
  'tool.todo': '更新了待辦清單',
  'tool.todo.running': '正在更新待辦清單',
  'tool.todo.call': '更新待辦清單',
  'tool.other': '使用了 {name}',
  'tool.other.running': '正在使用 {name}',
  'tool.other.call': '使用 {name}',
  'tool.outside': '工作區以外的檔案',
  'tool.failed': '失敗',
  'tool.exit': '結束代碼 {code}',
  'tool.matches': '{count} 筆符合',
  'tool.running': '執行中',
  'tool.waiting': '等待許可',
  'tool.unfinished': '沒有完成',
  'tool.noDetails': '沒有更多內容。',
  'tool.truncated': '後面的部分已被截斷。',
  'tool.open': '在編輯器開啟',
  'tool.reads': '{count} 個檔案',
  'tool.readsIn': '{dir} 裡的 {count} 個檔案',
  'tool.reads.failed': '{count} 個失敗',
  'tool.reads.unfinished': '{count} 個沒有完成',
  'tool.steps': '{count} 個步驟',
  'diff.label': '{path} 的變更',
  'diff.labelPlain': '變更',
  'diff.added': '新增',
  'diff.removed': '移除',

  // ---- cards: shared
  'card.waiting': '已等待 {age}',
  'card.withdrawn.stopped': '未回答：agent 已被停止。',
  'card.withdrawn.stoppedBy': '未回答：{name} 停止了 agent。',
  'card.withdrawn.ended': '未回答：session 已結束。',
  'card.withdrawn.endedBy': '未回答：{name} 結束了 session。',
  'card.withdrawn.failed': '未回答：agent 因錯誤而停止。',
  'card.withdrawn.restarted': '未回答：smurg 重新啟動了。session 繼續時 Claude 會再問一次。',
  'card.missing': '正在載入這張卡片…',
  'card.escalated': '{name} 已經 {age} 沒有回答。',
  'card.late.answered': '{name} 已經送出答案了。',
  'card.late.allowed': '{name} 已經允許了。',
  'card.late.denied': '{name} 已經拒絕了。',
  'card.late.decided': '{name} 已經處理這則建議了。',
  'card.late.withdrawn': '這已經不再等待回答。',
  'card.late.someone': '有人',

  // ---- question card
  'q.title': 'Claude 的選擇題',
  'q.voted': '{eligible} 人中 {voted} 人已投票',
  'q.allVoted': '{count} 人都投票了',
  'q.part': '第 {number} 題，共 {count} 題',
  'q.vote': '你的投票',
  'q.voteFor': '你的投票：{question}',
  'q.multi': '可以複選。',
  'q.leading': '領先',
  'q.votesFor': '{count} 票：{names}',
  'q.noVotes': '沒有人投',
  'q.other': '其他',
  'q.other.label': '你自己的答案',
  'q.other.placeholder': '寫下你自己的答案',
  'q.other.save': '投這個',
  'q.other.needText': '自己的答案需要有文字。',
  'q.other.by': '{name}：{text}',
  'q.comments': '{count} 則留言',
  'q.comments.none': '還沒有留言',
  'q.comment.label': '新增留言',
  'q.comment.placeholder': '新增留言。輸入 @ 可以提及成員',
  'q.comment.send': '留言',
  'q.comment.note': '留言是給團隊看的，Claude 不會讀。',
  'q.addToNote': '加到備註',
  'q.decide.responsible': '由你決定：你是這個 session 的負責人。',
  'q.decide.opener': '由你決定：這個 session 沒有指派負責人，而它是你開的。',
  'q.decide.host': '由你決定：沒有指派其他人，而你是主人。',
  'q.decide.other': '由 {name} 決定（這個 session 的負責人）。你的投票和留言所有人都看得到。',
  'q.decide.otherOpener': '由 {name} 決定：這個 session 沒有指派負責人。你的投票和留言所有人都看得到。',
  'q.decide.viewer': '你正在旁觀，「旁觀」的成員不能投票。由 {name} 決定。',
  'q.decide.nobody': '現在沒有人可以決定：主人不在。',
  'q.decide.hostToo': '由 {name} 決定。你是主人，也可以送出答案。',
  'q.decide.escalated': '由 {name} 決定，但已經 {age} 沒有回答。你可以代為送出。',
  'q.seen': '{name} 已經看過這一題。',
  'q.notSeen': '{name} 還沒看過這一題。',
  'q.advice': '你點選的選項就是你的投票，也是要送出的答案。你現在就可以送出；投票只是參考。',
  'q.tie': '票數相同，請你自己選擇答案。',
  'q.nobodyVoted': '還沒有人投票，你仍然可以選擇並送出。',
  'q.answer': '要送出的答案',
  'q.answerFor': '要送出的答案：{question}',
  'q.answer.none': '還沒有選擇答案',
  'q.answer.choose': '選擇答案',
  'q.answer.different': '送出不同的答案',
  'q.answer.otherOf': '其他（{name}）：{text}',
  'q.answer.otherOwn': '其他：用我自己的話回答',
  'q.answer.otherText': '要送出的答案',
  'q.submit': '送出答案',
  'q.submitAll': '送出所有答案',
  'q.submitFor': '代 {name} 送出',
  'q.note.label': '給 Claude 的備註（選填）',
  'q.note.placeholder': '給 Claude 的備註（選填）。只有這段備註和答案會送給 Claude',
  'q.editor': '你可以在 Claude 給的選項中決定。要用自己的話回答，需要 {names}。',
  'q.askSubmit': '請他們送出',
  'q.askSubmit.text': '{mentions} 請幫忙送出這一題的答案：我不能送出自己寫的答案。',
  'q.askSubmit.sent': '已在留言中請 {names} 送出。',
  'q.remind': '提醒還沒投票的人',
  'q.remind.sent': '已提醒。',
  'q.previous': '之前問過：「{label}」有 {count} 票',
  'q.settled.answered': '已回答：{answer}',
  'q.settled.tally': '{count} 票',
  'q.settled.by': '由 {name} 送出，{time}',
  'q.settled.byFor': '由 {name} 代 {decider} 送出，{time}',
  'q.settled.note': '給 Claude 的備註：{note}',
  'q.settled.show': '顯示投票和留言',
  'q.settled.otherBy': '{text}（{name}）',

  // ---- permission card
  'perm.title.command': 'Claude 請求許可執行指令',
  'perm.title.edit': 'Claude 請求許可編輯檔案',
  'perm.title.fetch': 'Claude 請求許可擷取網址',
  'perm.title.outside': 'Claude 請求許可使用工作區以外的檔案',
  'perm.title.other': 'Claude 請求許可使用 {tool}',
  'perm.outside': '工作區以外的檔案',
  'perm.input': '交給 {tool} 的內容',
  'perm.where.main': '在主工作區',
  'perm.where.worktree': '在 worktree {branch}',
  'perm.reason': 'Claude Code 的理由：{reason}',
  'perm.gate.writes-settings-script': 'smurg 會先問，是因為這個指令會更動這個資料夾的 Claude Code 專案設定所執行的腳本所在的位置（腳本本身，或放腳本的資料夾）。這些腳本會以主人的身分執行。',
  'perm.gate.may-reach-settings-script': 'smurg 會先問，是因為這個資料夾的 Claude Code 專案設定會執行腳本，而 smurg 無法確定這個指令不會動到它們。',
  'perm.more': '共 {count} 行：請捲動這個方框，把內容全部看完。',
  'perm.readFirst': '把要求的內容捲到最後，才能按「允許」。',
  'perm.allow': '允許一次',
  'perm.always': '一律允許這類',
  'perm.deny': '拒絕',
  'perm.deny.label': 'Claude 應該改做什麼？（選填）',
  'perm.deny.confirm': '拒絕',
  'perm.scope': '「一律允許」的範圍',
  'perm.scope.session': '在這個 session',
  'perm.scope.topic': '在這個主題的所有 session',
  'perm.kind.bash': '「這類」是指：以 {pattern} 開頭的指令。Claude 改了它會執行的檔案之後，同樣的指令也包含在內。',
  'perm.kind.fetch': '「這類」是指：從 {host} 擷取內容。',
  'perm.noAlways.interpreter': '{command} 可以執行任何程式碼：不能設為一律允許。',
  'perm.noAlways.fetches-code': '{command} 會下載並執行程式碼：不能設為一律允許。',
  'perm.noAlways.one-word': '只有一個單字的指令不能設為一律允許。',
  'perm.noAlways.host-only': '只有主人能允許的請求不能設為一律允許。',
  'perm.noAlways.no-suggestion': '這類請求不能設為一律允許。',
  'perm.inbox.mine': '它在你的收件夾裡：你是負責人。主人和「可使用 agent」的成員也可以回答。',
  'perm.inbox.theirs': '它在 {name}（負責人）的收件夾裡。你也可以回答：主人和「可使用 agent」的成員都可以。',
  'perm.inbox.all': '它在主人和每一位「可使用 agent」成員的收件夾裡。',
  'perm.hostOnly': '只有主人可以允許：它會動到共用專案以外的地方。',
  'perm.hostOnly.mine': '只有你（主人）可以允許：它會動到共用專案以外的地方。',
  'perm.waiting.responsible': '等待 {name}（負責人）、主人或「可使用 agent」的成員。你的角色不能允許。',
  'perm.waiting.all': '等待主人或「可使用 agent」的成員。你的角色不能允許。',
  'perm.settled.allowed': '{name} 允許了一次，{time}',
  'perm.settled.always.session': '{name} 已允許，並在這個 session 一律允許 {rule}，{time}',
  'perm.settled.always.topic': '{name} 已允許，並在這個主題的所有 session 一律允許 {rule}，{time}',
  'perm.settled.denied': '{name} 拒絕了，{time}',
  'perm.settled.deniedWith': '{name} 拒絕了，{time}：「{message}」',

  // ---- suggestion card
  'sug.title': '{name} 的建議',
  'sug.cleaned': '已移除看不見的字元。',
  'sug.source': '關於 {path} 第 {range} 行',
  'sug.sourceLine': '關於 {path} 第 {line} 行',
  'sug.accept': '採用',
  'sug.editAccept': '修改後採用',
  'sug.acceptEdited': '採用這段文字',
  'sug.reject': '不採用',
  'sug.reject.label': '為什麼？（選填，{name} 會看到）',
  'sug.reject.confirm': '不採用',
  'sug.reaches': '有人採用之後，它才會送給 agent。',
  'sug.edit': '編輯',
  'sug.edit.label': '你的建議',
  'sug.edit.save': '儲存',
  'sug.withdraw': '撤回',
  'sug.waiting.responsible': '等待 {name}（負責人）。主人和「可使用 agent」的成員也可以採用。',
  'sug.waiting.all': '等待主人或「可使用 agent」的成員。',
  'sug.settled.accepted': '{name} 已採用，{time}',
  'sug.settled.acceptedEdited': '{name} 修改後採用，{time}',
  'sug.settled.rejected': '{name} 不採用，{time}',
  'sug.settled.rejectedWith': '{name} 不採用，{time}：「{reason}」',
  'sug.settled.withdrawn': '{name} 已撤回',
  'sug.settled.closed.session-ended': '已關閉：session 已結束',
  'sug.settled.closed.author-kicked': '已關閉：{name} 已被移出工作區',
  'sug.settled.closed.author-demoted': '已關閉：{name} 的角色已不能提出建議',
  'sug.settled.closed.topic-archived': '已關閉：主題已封存',

  // ---- next-step cards
  'next.spec': 'spec 初稿完成了。接下來：一起編輯，或請 agent 修改。確定沒問題之後：',
  'next.spec.generate': '產生計畫',
  'next.spec.who': '{names} 可以產生計畫。',
  'next.spec.open': '開啟 spec',
  'next.plan': '計畫完成了。接下來：確認各項目的負責人，然後開始。',
  'next.plan.open': '開啟計畫',
  'next.report': '結果報告寫好了。',
  'next.report.item': '{item} 的結果報告寫好了。',
  'next.report.reviewers': '由 {names} 負責看。',
  'next.report.anyone': '除了「旁觀」的成員，任何人都可以看。',
  'next.report.open': '開啟報告',

  // ---- status bar
  'status.starting': 'Claude 正在啟動…',
  'status.writing': 'Claude 正在寫',
  'status.working': 'Claude 工作中',
  'status.thinking': 'Claude 正在思考',
  'status.compacting': 'Claude 正在縮短對話內容',
  'status.question': 'Claude 正在等待回答',
  'status.permission': 'Claude 正在等待許可',
  'status.age': '· {age}',
  'status.show': '顯示',
  'status.idle': 'Claude 待命中。',
  'status.done': '完成。追問可以在這裡或在報告裡提出，Claude 會回答。',
  'status.stalled': '沒寫報告就停下了。',
  'status.stalled.restart': '已暫停：smurg 重新啟動過。',
  'status.stalled.stopped': '被人停止，沒有報告。',
  'status.stalled.error': '因錯誤停止，沒有報告。',
  'status.stalled.continue': '繼續',
  'status.failed': 'agent 因錯誤而停止。',
  'status.failed.retry': '再試一次',
  'status.ended': '這個 session 已結束。',
  'status.account.usage-limit': '主人的 Claude 帳號已達用量上限。',
  'status.account.logged-out': '主人電腦上的 Claude Code 尚未登入。',
  'status.login.check': '重新檢查登入',
  'status.login.ok': '主人電腦上的 Claude Code 已登入。',
  'status.login.unknown': '無法檢查登入狀態。',
  'status.spec': '現在就寫 spec',
  'status.spec.title': '請 Claude 寫 spec 的初稿',
  'status.fresh': '開始新的對話',
  'status.fresh.title': '這段討論很長了。新的討論會從目前的 spec 和計畫開始。',
  'status.catchingUp': '正在跟上最新內容…',

  // ---- composer
  'composer.message': '傳訊息給 Claude · {title}',
  'composer.suggest': '向 Claude 提出建議 · {title}',
  'composer.inTopic': '{title} · {topic}',
  'composer.send': '傳送',
  'composer.sendSuggestion': '送出建議',
  'composer.hint': 'Enter 傳送 · Shift+Enter 換行',
  'composer.hint.working': 'Claude 會在下一步讀到 · Enter 傳送',
  'composer.hint.question': 'Claude 正在等上面那一題的答案，之後才會讀訊息。',
  'composer.goes.one': '會以建議的形式送給 {name}，採用之後才會送給 agent。',
  'composer.goes.many': '會以建議的形式送給 {names}，採用之後才會送給 agent。',
  'composer.goes.responsible': '會以建議的形式送給 {names}：你是負責人，但你的角色不能傳訊息給 agent。',
  'composer.goes.nobody': '會以建議的形式送給主人，採用之後才會送給 agent。',
  'composer.viewer': '你是「旁觀」的成員，可以觀看這個 session，但不能傳訊息、提出建議或投票。',
  'composer.ended': '這個 session 已結束，不再接受訊息。',
  'composer.offline': '主人離線中：現在無法傳送。',
  'composer.blank': '請先寫點內容。',
  'composer.tooLong': '太長了：最多 {max} 個字元。',
  'composer.failed': '沒有送出：{message}',
  'composer.suggested': '建議已送出。',
  'composer.source': '{path} 第 {range} 行',
  'composer.sourceLine': '{path} 第 {line} 行',
  'composer.source.open': '開啟 {path} 第 {line} 行',
  'composer.source.remove': '移除附上的程式碼',
  'composer.mentions': '可以提及的成員',
  'composer.mention.option': '{name} · {role}',

  // ---- "Send to agent" from the editor
  'select.title': '要送到哪一個 session？',
  'select.body.message': '選取的程式碼會放進你選的 session 的訊息框。',
  'select.body.suggestion': '選取的程式碼會成為給你選的 session 的建議。',
  'select.none': '沒有可以送去的 agent session。',
  'select.viewer': '你是「旁觀」的成員，不能把文字送給 agent。',
  'select.gone': '那個 session 已經不存在。',
  'select.ended': '那個 session 已結束。',
  'select.sent': '已送到「{title}」。',
  'select.failed': '沒有送出：{message}',
} as const;
