import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the editor feature (Monaco + Yjs, presence cursors, lock banner, selection → suggestion). English
// defines the keys; strings.zh-TW.ts holds the same keys in Traditional Chinese.
export const t = defineStrings(
  'editor',
  {
    title: 'Editor',
    'empty.title': 'No open files',
    'empty.hint': 'Open a file from the file tree on the left. Everyone can edit together in real time, and changes are saved automatically.',
    'tabs.label': 'Open files',
    'tabs.close': 'Close {name}',
    'tabs.closeHint': 'Press Delete to close the tab',
    'tabs.agentLocked': '{agent} is editing',
    'tabs.unsaved': 'Not saved yet',
    'tabs.readOnly': 'Read-only',
    'tabs.error': 'Could not open',
    'root.main': 'Main workspace',
    'root.worktree': 'Worktree: {name}',
    'doc.loading': 'Opening the file…',
    'doc.syncing': 'Syncing the content…',
    'doc.reopening': 'Reconnecting…',
    'doc.editorLabel': 'Editor for {path}',
    'doc.infoLabel': 'File information',
    'engine.loading': 'Loading the editor…',
    'engine.failed': 'The editor failed to load. Check your network and try again.',
    'engine.retry': 'Retry',
    'lock.agent': '{agent} is editing; you cannot type for now',
    'lock.agentDetail': 'You can edit again as soon as it finishes.',
    'lock.someAgent': 'An agent',
    'lock.mine': 'You are editing this file, so agents cannot change it for now.',
    'lock.mineShared': 'You and {others} are editing this file (a shared edit lock), so agents cannot change it for now.',
    'lock.others': 'This file is being edited by {others}, so agents cannot change it for now.',
    'lock.release': 'Let the agent go first',
    'lock.forceRelease': 'Force release',
    'lock.releaseHint': 'Leave the edit lock so that agents can change this file. You get the lock back when you type again.',
    'lock.releaseFailed': 'Could not release the edit lock: {message}',
    'readOnly.noPermission': 'This file is read-only for you',
    'readOnly.removed': 'This file is no longer where it was, so you cannot type',
    'removed.deletedBy': 'This file was deleted by {who}',
    'removed.movedBy': 'This file was moved to "{to}" by {who}',
    'removed.deleted': 'This file was deleted or moved',
    'removed.moved': 'This file was moved to "{to}"',
    'removed.detail': 'What is in this tab can no longer be saved. You can create the file again from this content, or close the tab.',
    'removed.detailMoved': 'What is in this tab can no longer be saved. Continue editing at the new location.',
    'removed.openMoved': 'Open the new location',
    'removed.recreate': 'Create again from this content',
    'removed.recreated': 'Created "{name}" again',
    'removed.recreateFailed': 'Could not create the file again: {message}',
    'removed.close': 'Close tab',
    'removed.you': 'you',
    'removed.system': 'an outside program',
    'tabs.removed': 'Deleted or moved',
    'readOnly.offline': 'Reconnecting; you cannot type for now',
    'readOnly.loading': 'Syncing the content; one moment',
    'readOnly.error': 'The file could not be opened',
    'readOnly.badge': 'Read-only',
    'rejected.agentLocked': '{agent} is editing this file, so what you just typed was not accepted.',
    'rejected.readOnly': 'This file is read-only; your change was discarded.',
    'rejected.forbidden': 'You do not have permission to edit this file; your change was discarded.',
    'rejected.fileUnavailable':
      "This file was moved or deleted on the host's disk, or turned into something that cannot be edited here, so it cannot be changed for now. Unsaved content is not lost: the host's conflicts panel keeps a copy that can be restored from there.",
    'notice.dismiss': 'Got it',
    'dropped.epoch': "The host's computer reloaded this file; the latest content has been synced.",
    'dropped.epochRestored': "The host's computer reloaded this file. Your unsaved changes were sent again.",
    'dropped.diverged': "Syncing with the host's computer was interrupted; the document has been synced again.",
    'dropped.divergedRestored': "Syncing with the host's computer was interrupted; the document has been synced again. Your unsaved changes were sent again.",
    'recovery.title': "You have changes that were not saved to the host's computer",
    'recovery.body':
      "The host's computer reloaded this file and its content differs from your version, so the two cannot be merged automatically. Your version is kept here: copy it first, or replace the current content with it (changes other people made in the meantime are overwritten).",
    'recovery.show': { one: 'Show my version ({count} character)', other: 'Show my version ({count} characters)' },
    'recovery.apply': 'Replace with my version',
    'recovery.applyUnavailable': 'Cannot replace right now: the file is read-only or still syncing.',
    'recovery.copy': 'Copy my version',
    'recovery.copied': 'Your version was copied',
    'recovery.copyFailed': 'Could not copy: {message}',
    'recovery.noClipboard': 'This browser does not let web pages copy. Expand your version below, then select and copy it by hand.',
    'recovery.discard': 'Discard my version',
    'save.label': 'Autosave status',
    'save.saving': 'Saving…',
    'save.stale': "Not saved yet: waiting for the host's computer",
    'save.saved': 'Saved automatically ({time})',
    'eol.lf': 'LF (Unix)',
    'eol.crlf': 'CRLF (Windows)',
    'eol.cr': 'CR (classic Mac)',
    'eol.mixed': 'This file mixes different line endings; the first autosave makes them all {eol}.',
    'eol.info': 'Line endings: {eol}',
    'bom.info': 'UTF-8 with BOM',
    'refused.tooLarge': 'This file is larger than 5 MB and cannot be opened in the editor.',
    'refused.binary': 'This is a binary file and cannot be opened in the editor.',
    'refused.encoding': 'This file is not UTF-8 text and cannot be opened in the editor.',
    'refused.notAFile': 'This is not a regular file and cannot be opened in the editor.',
    'refused.notFound': 'This file was not found. It may have been moved or deleted.',
    'refused.other': 'This file cannot be opened.',
    'refused.hint': 'You can download the file and open it with a program on your own computer.',
    'refused.download': 'Download file',
    'refused.retry': 'Open again',
    'refused.close': 'Close tab',
    'download.failed': 'Could not start the download: {message}',
    'presence.label': 'Also in this file',
    'send.menu': 'Send to agent',
    'send.menuLabel': 'Send the selected code to an agent session',
    'send.action': 'Send to agent…',
    'send.needSelection': 'Select the code to send first',
    'send.toOwn': 'Send straight into "{title}"',
    'send.toOther': 'Send as a suggestion to "{title}", opened by {owner}',
    'send.toOtherDraft': 'Draft a suggestion to "{title}", opened by {owner}',
    'send.none': 'No agent session to send to right now',
    'send.tooLarge': 'The selection is too large to send (the limit is 64K characters).',
    'send.empty': 'Nothing is selected.',
    'send.unavailable': 'Suggestions are not ready yet. Try again in a moment.',
    'send.failed': 'Could not send: {message}',
  },
  zhTW,
);
