// zh-TW table of the editor namespace: the same keys as strings.ts (English defines them).
export const zhTW = {
  title: '編輯器',
  'empty.title': '沒有開啟的檔案',
  'empty.hint': '從左側檔案樹開啟檔案。大家可以即時一起編輯，修改會自動儲存。',
  'tabs.label': '已開啟的檔案',
  'tabs.close': '關閉 {name}',
  'tabs.closeHint': '按 Delete 關閉分頁',
  'tabs.agentLocked': '{agent} 正在修改',
  'tabs.unsaved': '尚未儲存',
  'tabs.readOnly': '唯讀',
  'tabs.error': '無法開啟',
  'root.main': '主工作區',
  'root.worktree': 'worktree：{name}',
  'doc.loading': '正在開啟檔案…',
  'doc.syncing': '正在同步內容…',
  'doc.reopening': '重新連線中…',
  'doc.editorLabel': '{path} 的編輯器',
  'doc.infoLabel': '檔案資訊',
  'engine.loading': '正在載入編輯器…',
  'engine.failed': '編輯器載入失敗，請檢查網路後重試。',
  'engine.retry': '重試',
  'lock.agent': '{agent} 正在修改，暫時無法輸入',
  'lock.agentDetail': '修改完成後會自動恢復可編輯。',
  'lock.someAgent': 'agent',
  'lock.mine': '你正在編輯這個檔案，agent 暫時不能修改它。',
  'lock.mineShared': '你和{others}正在編輯這個檔案（共用編輯鎖），agent 暫時不能修改它。',
  'lock.others': '{others}正在編輯這個檔案，agent 暫時不能修改它。',
  'lock.release': '讓 agent 先改',
  'lock.forceRelease': '強制釋放',
  'lock.releaseHint': '離開編輯鎖，讓 agent 可以修改這個檔案。你再次輸入時會重新取得編輯鎖。',
  'lock.releaseFailed': '無法釋放編輯鎖：{message}',
  'readOnly.noPermission': '這個檔案對你是唯讀的',
  'readOnly.removed': '這個檔案已經不在原來的位置，無法再輸入',
  'removed.deletedBy': '這個檔案已被{who}刪除',
  'removed.movedBy': '這個檔案已被{who}移到「{to}」',
  'removed.deleted': '這個檔案已被刪除或移走',
  'removed.moved': '這個檔案已被移到「{to}」',
  'removed.detail': '這個分頁裡的內容已無法儲存。你可以用這些內容重新建立檔案，或關閉分頁。',
  'removed.detailMoved': '這個分頁裡的內容已無法儲存。請改到新位置繼續編輯。',
  'removed.detailStandalone': '這裡顯示的內容已經無法儲存。你可以用這份內容重新建立檔案。',
  'removed.openMoved': '開啟新位置',
  'removed.recreate': '用這些內容重新建立',
  'removed.recreated': '已重新建立「{name}」',
  'removed.recreateFailed': '無法重新建立：{message}',
  'removed.close': '關閉分頁',
  'removed.you': '你',
  'removed.system': '外部程式',
  'tabs.removed': '已刪除或移走',
  'readOnly.offline': '正在重新連線，暫時無法輸入',
  'readOnly.loading': '正在同步內容，請稍候',
  'readOnly.error': '檔案無法開啟',
  'readOnly.badge': '唯讀',
  'rejected.agentLocked': '{agent} 正在修改這個檔案，你剛才輸入的內容沒有被接受。',
  'rejected.readOnly': '這個檔案是唯讀的，你的修改已被捨棄。',
  'rejected.forbidden': '你沒有編輯這個檔案的權限，你的修改已被捨棄。',
  'rejected.fileUnavailable': '這個檔案在主人的磁碟上被移走、刪除，或變成無法在這裡編輯的內容，暫時不能再修改。還沒存檔的內容沒有遺失：主人的衝突面板裡保留了一份，可以從那裡還原。',
  'notice.dismiss': '知道了',
  'dropped.epoch': '主人電腦重新載入了這個檔案，已同步最新內容。',
  'dropped.epochRestored': '主人電腦重新載入了這個檔案。你還沒存到的修改已經重新送出。',
  'dropped.diverged': '和主人電腦的同步中斷過，已重新同步文件內容。',
  'dropped.divergedRestored': '和主人電腦的同步中斷過，已重新同步文件內容。你還沒存到的修改已經重新送出。',
  'recovery.title': '你有修改還沒存到主人電腦',
  'recovery.body':
    '主人電腦重新載入了這個檔案，內容和你的版本不同，無法自動合併。你的版本還保留在這裡：可以先複製，或用它取代目前的內容（這段期間別人的修改會被覆蓋）。',
  'recovery.show': '查看我的版本（{count} 個字元）',
  'recovery.apply': '用我的版本取代',
  'recovery.applyUnavailable': '現在無法取代：檔案是唯讀的，或還在同步。',
  'recovery.copy': '複製我的版本',
  'recovery.copied': '已複製你的版本',
  'recovery.copyFailed': '無法複製：{message}',
  'recovery.noClipboard': '這個瀏覽器不允許網頁複製，請展開「查看我的版本」手動選取複製',
  'recovery.discard': '捨棄我的版本',
  'save.label': '自動儲存狀態',
  'save.saving': '儲存中…',
  'save.stale': '尚未儲存：正在等待主人電腦回應',
  'save.saved': '已自動儲存（{time}）',
  'eol.lf': 'LF（Unix）',
  'eol.crlf': 'CRLF（Windows）',
  'eol.cr': 'CR（舊版 Mac）',
  'eol.mixed': '這個檔案混用了不同的換行符號，第一次自動儲存時會統一成 {eol}。',
  'eol.info': '換行：{eol}',
  'bom.info': 'UTF-8（含 BOM）',
  'refused.tooLarge': '這個檔案超過 5 MB，無法在編輯器中開啟。',
  'refused.binary': '這是二進位檔案，無法在編輯器中開啟。',
  'refused.encoding': '這個檔案不是 UTF-8 文字，無法在編輯器中開啟。',
  'refused.notAFile': '這不是一般檔案，無法在編輯器中開啟。',
  'refused.notFound': '找不到這個檔案，它可能已被移動或刪除。',
  'refused.other': '無法開啟這個檔案。',
  'refused.hint': '你可以下載檔案，用自己電腦上的程式開啟。',
  'refused.download': '下載檔案',
  'refused.retry': '重新開啟',
  'refused.close': '關閉分頁',
  'download.failed': '無法開始下載：{message}',
  'presence.label': '也在這個檔案裡的人',
  'send.menu': '送到 agent',
  'send.menuLabel': '把選取的程式碼送到 agent session',
  'send.action': '送到 agent…',
  'send.needSelection': '先選取要送出的程式碼',
  'send.toOwn': '以訊息送到「{title}」',
  'send.toOther': '以建議送到「{title}」',
  'send.toOtherDraft': '先寫進給「{title}」的建議草稿',
  'send.inTopic': '{topic} · {title}',
  'send.none': '目前沒有可以送出的 agent session',
  'send.tooLarge': '選取範圍太大，無法送出（上限 64K 字元）。',
  'send.empty': '沒有選取任何內容。',
  'send.unavailable': '送到 agent 的功能還沒有準備好，請稍後再試。',
  'send.failed': '無法送出：{message}',
} as const;
