import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the host console feature (members, sessions, suggestions, invites, merge requests, audit log, settings).
// English defines the keys; strings.zh-TW.ts holds the same keys in Traditional Chinese. Role names are never spelled
// out here as labels: `{role}` is filled from the wire catalog (roleLabel); running text says "agent access".
export const t = defineStrings(
  'console',
  {
    // ---- page
    'page.title': 'Host console',
    'page.lead': 'See what every member and every agent is doing, end a session or remove a member with one click, and manage invites, merge requests and settings.',
    'page.notHost.title': 'Only the host can use the console',
    'page.notHost.body': 'The host console is where the host invites members, changes roles, removes members and reads the audit log. Your role is {role}.',
    'nav.label': 'Console sections',
    'nav.members': 'Members',
    'nav.sessions': 'All sessions',
    'nav.suggestions': 'Pending suggestions',
    'nav.merges': 'Merge requests',
    'nav.invites': 'Invite links',
    'nav.audit': 'Audit log',
    'nav.settings': 'Settings',
    'load.loading': 'Loading the console…',
    'load.failed': 'Could not load the console: {message}',
    'load.retry': 'Reload',

    // ---- security notes (SPEC §11)
    'security.title': 'Security notes for the host',
    'security.unsandboxed':
      'Every session, including the ones opened by members with agent access, runs on your computer as you, without a sandbox: it can read and write every file you can, run any command, and use your Claude account.',
    'security.agentRole': 'Give agent access only to people you fully trust. Make everyone else an editor or a viewer.',
    'security.injection':
      'A file a guest writes into the project can carry instructions for an agent (prompt injection). Read a file that a guest changed before you let your agent read it.',
    'security.prompts': 'Keep the permission prompts of Claude Code on: do not use a mode that skips them, and read what the agent wants to do before you allow it.',
    'security.invites': 'An invite link contains the secret for joining. Send it only over a private channel to the person you invite, and revoke the links you no longer need.',

    // ---- members
    'members.title': 'Members ({count})',
    'members.caption': 'Members',
    'members.col.member': 'Member',
    'members.col.status': 'Status',
    'members.col.role': 'Role',
    'members.col.devices': 'Devices',
    'members.col.activity': 'Doing now',
    'members.col.actions': 'Actions',
    'members.you': ' (you)',
    'members.online': 'Online',
    'members.onlineConnections': { one: 'Online ({count} connection)', other: 'Online ({count} connections)' },
    'members.offline': 'Offline',
    'members.roleLabel': 'Role of {name}',
    'members.devices.none': 'No devices',
    'members.device.web': 'browser',
    'members.device.cli': 'terminal',
    'members.device.item': '{name} ({kind})',
    'members.device.lastSeen': 'Last seen {time}',
    'members.device.connected': 'Connected (last active {time})',
    'members.device.revoked': 'Revoked',
    'members.activity.file': 'Viewing {path}',
    'members.activity.fileWorktree': 'Viewing {path} in a worktree',
    'members.activity.sessions': { one: '{count} session running', other: '{count} sessions running' },
    'members.activity.none': 'Nothing in progress',
    'members.kick': 'Remove',
    'members.kickLabel': 'Remove {name}',
    'members.empty': 'No other members yet. Create an invite link to bring your teammates in.',
    'members.roleChanged': 'The role of {name} is now {role}. They reconnect automatically with the new permissions.',
    'members.roleFailed': 'Could not change the role of {name}: {message}',
    'members.hint': 'After a role change the member reconnects automatically with the new permissions. A member who loses agent access also loses the sessions they opened: those sessions end.',

    // ---- kick confirmation
    'kick.title': 'Remove {name}?',
    'kick.lead': 'As soon as you confirm:',
    'kick.sessions': {
      one: 'Every session {name} opened ends at once ({count} session right now).',
      other: 'Every session {name} opened ends at once ({count} sessions right now).',
    },
    'kick.keys': 'The keys of all devices of {name} are revoked. Their old devices and old invite links can no longer connect.',
    'kick.irreversible': 'This cannot be undone. To let {name} back in, create a new invite link.',
    'kick.confirm': 'Remove {name}',
    'kick.done': '{name} was removed.',
    'kick.failed': 'Could not remove {name}: {message}',

    // ---- demotion that ends sessions
    'demote.title': 'Change the role of {name}?',
    'demote.body': {
      one: '{name} has {count} session open. With the role {role} they can no longer use agents: this session will end.',
      other: '{name} has {count} sessions open. With the role {role} they can no longer use agents: these sessions will end.',
    },
    'demote.confirm': 'Change role',

    // ---- agent access: the risk, confirmed before an invite or a role change applies
    'roleRisk.text':
      'Anyone with agent access can have an agent run any command on your computer, read the files in your home directory and use your Claude account. Give it only to people you fully trust.',
    'roleRisk.memberTitle': 'Give {name} agent access?',
    'roleRisk.inviteTitle': 'Create an invite link with agent access?',
    'roleRisk.confirmMember': 'I understand, change the role',
    'roleRisk.confirmInvite': 'I understand, create the link',

    // ---- sessions
    'sessions.title': 'All sessions ({count})',
    'sessions.caption': 'All sessions',
    'sessions.col.title': 'Name',
    'sessions.col.owner': 'Opened by',
    'sessions.col.status': 'Status',
    'sessions.col.where': 'Location',
    'sessions.col.viewers': 'Watching',
    'sessions.col.actions': 'Actions',
    'sessions.kind.agent': 'agent',
    'sessions.kind.terminal': 'terminal',
    'sessions.status.starting': 'Starting',
    'sessions.status.running': 'Running',
    'sessions.status.exited': 'Ended',
    'sessions.status.exitedCode': 'Ended (exit code {code})',
    'sessions.where.main': 'Main workspace',
    'sessions.where.worktreeGone': 'A removed worktree',
    'sessions.viewers': { one: '{count} connection', other: '{count} connections' },
    'sessions.agentFile': 'Working on {path}',
    'sessions.terminate': 'Terminate',
    'sessions.terminateLabel': 'Terminate "{title}", opened by {owner}',
    'sessions.terminated': 'Terminated "{title}", opened by {owner}.',
    'sessions.terminateFailed': 'Could not terminate {title}: {message}',
    'sessions.empty': 'No session is running.',
    'sessions.loadFailed': 'Could not load the sessions: {message}',
    'sessions.showExited': 'Show ended sessions ({count})',
    'sessions.hideExited': 'Hide ended sessions',

    // ---- pending suggestions (read-only)
    'suggestions.title': 'Pending suggestions ({count})',
    'suggestions.lead': 'This list is read-only. Accept or reject a suggestion in the workspace, under Suggestions (the host and members with agent access can).',
    'suggestions.target': '{author} → {title}, opened by {owner}',
    'suggestions.unknownSession': '{author} → a session that no longer exists',
    'suggestions.source': 'With {path}, lines {start}–{end}',
    'suggestions.sourceLine': 'With {path}, line {start}',
    'suggestions.empty': 'No pending suggestions.',
    'suggestions.loadFailed': 'Could not load the suggestions: {message}',

    // ---- invites
    'invites.title': 'Invite links',
    'invites.create': 'Create invite link',
    'invites.role': 'Role',
    'invites.expiry': 'Expires after',
    'invites.expiry.1h': '1 hour',
    'invites.expiry.1d': '1 day',
    'invites.expiry.7d': '7 days',
    'invites.expiry.30d': '30 days',
    'invites.maxUses': 'Number of uses',
    'invites.maxUsesHint': 'Leave empty for no limit until the link expires.',
    'invites.maxUsesInvalid': 'Enter a whole number from 1 to {max}, or leave it empty.',
    'invites.roleHint.agent': 'Can open agents and terminals (they run on your computer with your Claude account) and type into any session.',
    'invites.roleHint.editor': 'Can edit files and make suggestions to sessions, but cannot open an agent or type into a session.',
    'invites.roleHint.viewer': 'Can only browse files and watch sessions.',
    'invites.createFailed': 'Could not create the invite link: {message}',
    'invites.link.title': 'Invite link created',
    'invites.link.once': 'This link is shown only this once. If you lose it, revoke it and create a new one.',
    'invites.link.secret': 'The link contains the secret for joining the workspace. Send it only over a private channel (a direct message, for example) to the person you invite. Do not post it in a group or anywhere public.',
    'invites.link.summary': 'Role: {role}. Expires in {expiry}. {uses}.',
    'invites.link.usesLimited': { one: 'Can be used {count} time', other: 'Can be used {count} times' },
    'invites.link.usesUnlimited': 'No limit on uses until it expires',
    'invites.link.label': 'Invite link',
    'invites.link.copy': 'Copy invite link',
    'invites.link.done': 'I have copied it',
    'invites.caption': 'Invite links',
    'invites.col.role': 'Role',
    'invites.col.created': 'Created',
    'invites.col.expires': 'Expires',
    'invites.col.uses': 'Uses',
    'invites.col.status': 'Status',
    'invites.col.actions': 'Actions',
    'invites.expires.none': 'Never',
    'invites.uses.limited': '{uses} used, {left} left',
    'invites.uses.unlimited': '{uses} used, no limit',
    'invites.status.active': 'Active',
    'invites.status.revoked': 'Revoked',
    'invites.status.expired': 'Expired',
    'invites.status.usedUp': 'Used up',
    'invites.revoke': 'Revoke',
    'invites.revokeLabel': 'Revoke the {role} invite created {time}',
    'invites.revoked': 'The invite link is revoked. Nobody can join with it any more.',
    'invites.revokeFailed': 'Could not revoke the invite link: {message}',
    'invites.empty': 'No active invite links.',
    'invites.showInactive': 'Show inactive invites ({count})',
    'invites.hideInactive': 'Hide inactive invites',

    // ---- merge requests
    'merges.title': 'Merge requests',

    // ---- audit log
    'audit.title': 'Audit log',
    'audit.lead': 'Newest first; new entries appear as they happen. The audit log is stored only on your computer.',
    'audit.caption': 'Audit log',
    'audit.col.time': 'Time',
    'audit.col.actor': 'Who',
    'audit.col.action': 'Action',
    'audit.col.target': 'Target',
    'audit.col.outcome': 'Outcome',
    'audit.col.detail': 'Details',
    'audit.detail.show': 'Details',
    'audit.detail.label': 'Details of this entry',
    'audit.detail.authorName': 'Suggested by',
    'audit.detail.text': 'Suggestion',
    'audit.detail.finalText': 'Text that was sent',
    'audit.detail.rejectReason': 'Reject reason',
    'audit.detail.outcome': 'Decision',
    'audit.detail.accepted': 'Accepted',
    'audit.detail.acceptedModified': 'Accepted with edits',
    'audit.detail.rejected': 'Rejected',
    'audit.detail.withdrawn': 'Withdrawn',
    'audit.detail.conflictFiles': 'Conflicting files',
    'audit.detail.from': 'From',
    'audit.detail.to': 'To',
    'audit.detail.role': 'Role',
    'audit.detail.reason': 'Reason',
    'audit.detail.source': 'Attached code',
    'audit.detail.branch': 'Branch',
    'audit.detail.message': 'Message',
    'audit.outcome.ok': 'OK',
    'audit.outcome.denied': 'Denied',
    'audit.outcome.error': 'Error',
    'audit.loadOlder': 'Load older entries',
    'audit.end': 'No older entries.',
    'audit.limit': 'At most {max} entries are shown.',
    'audit.count': { one: '{count} entry loaded', other: '{count} entries loaded' },
    'audit.empty': 'No entries yet.',
    'audit.olderFailed': 'Could not load older entries: {message}',
    'audit.action.auth.join': 'Joined the workspace',
    'audit.action.auth.connect': 'Connected',
    'audit.action.auth.disconnect': 'Disconnected',
    'audit.action.auth.rejected': 'Connection rejected',
    'audit.action.authz.denied': 'Denied: no permission',
    'audit.action.path.denied': 'Denied: path',
    'audit.action.file.write': 'Wrote a file',
    'audit.action.file.create': 'Created a file',
    'audit.action.file.rename': 'Renamed a file',
    'audit.action.file.delete': 'Deleted a file',
    'audit.action.file.upload': 'Uploaded a file',
    'audit.action.file.download': 'Downloaded a file',
    'audit.action.doc.edit': 'Edited a document',
    'audit.action.agent.edit': 'Agent changed a file',
    'audit.action.external.change': 'Outside program changed a file',
    'audit.action.doc.conflict': 'Edit conflict',
    'audit.action.doc.conflict-resolve': 'Resolved an edit conflict',
    'audit.action.lock.acquire': 'Took a file lock',
    'audit.action.lock.release': 'Released a file lock',
    'audit.action.lock.denied': 'File lock denied',
    'audit.action.lock.force-release': 'Forced a file lock release',
    'audit.action.session.create': 'Opened a session',
    'audit.action.session.end': 'Ended a session',
    'audit.action.session.terminate': 'Terminated a session',
    'audit.action.suggest.create': 'Made a suggestion',
    'audit.action.suggest.edit': 'Edited a suggestion',
    'audit.action.suggest.accept': 'Accepted a suggestion',
    'audit.action.suggest.reject': 'Rejected a suggestion',
    'audit.action.suggest.withdraw': 'Withdrew a suggestion',
    'audit.action.worktree.create': 'Created a worktree',
    'audit.action.worktree.remove': 'Removed a worktree',
    'audit.action.worktree.merge.request': 'Requested a merge',
    'audit.action.worktree.merge.approve': 'Approved a merge',
    'audit.action.worktree.merge.reject': 'Rejected a merge',
    'audit.action.member.role': 'Changed a role',
    'audit.action.member.kick': 'Removed a member',
    'audit.action.member.leave': 'Member left',
    'audit.action.invite.create': 'Created an invite',
    'audit.action.invite.revoke': 'Revoked an invite',
    'audit.action.device.revoke': 'Revoked a device key',
    'audit.action.settings.change': 'Changed settings',

    // ---- settings
    'settings.title': 'Settings',
    'settings.lead': 'Changes apply as soon as you save. No restart is needed.',
    'settings.loading': 'Loading the settings…',
    'settings.sharedDirs': 'Shared folders (read-only in worktrees)',
    'settings.sharedDirsHint':
      'One path per line, relative to the shared folder, for example data or models/checkpoints. A new worktree gets each one as a read-only symbolic link. Use this for large data that is not in git.',
    'settings.humanLockIdle': 'Idle time before an edit lock is released (seconds)',
    'settings.humanLockIdleHint': 'Once the last person editing a file has been idle this long, an agent may change the file. Default: 30 seconds.',
    'settings.agentLockTimeout': 'Agent lock timeout (seconds)',
    'settings.agentLockTimeoutHint': 'The longest an agent keeps its lock while it changes a file. Default: 60 seconds.',
    'settings.diskReserveGb': 'Disk space to keep free (GB)',
    'settings.diskReservePercent': 'Disk space to keep free (%)',
    'settings.diskHint': 'Before an upload starts, the daemon checks that the larger of the two stays free afterwards, and refuses the upload if not. Default: 5 GB or 5%.',
    'settings.save': 'Save settings',
    'settings.reset': 'Reset',
    'settings.saved': 'Settings saved and applied.',
    'settings.saveFailed': 'Could not save the settings: {message}',
    'settings.invalid': { one: '{count} field needs fixing.', other: '{count} fields need fixing.' },
    'settings.error.required': 'Enter a value.',
    'settings.error.number': 'Enter a number.',
    'settings.error.min': 'Enter a number of {min} or more.',
    'settings.error.range': 'Enter a number from {min} to {max}.',
    'settings.error.dir': '"{value}" is not a valid folder path: use a path relative to the shared folder, without a leading / and without . or .. segments.',
    'settings.error.duplicate': '"{value}" is listed twice.',
    'settings.error.tooMany': 'At most {max}.',
  },
  zhTW,
);
