// Traditional Chinese of the `console` namespace: exactly the keys of strings.ts (the English table defines them).
// Only strings.ts imports this file.
export const zhTW = {
  // ---- page
  'page.title': '主人控制台',
  'page.lead': '在這個畫面看到所有成員和所有 agent 在做什麼，一鍵終止 session 或踢出成員，並管理邀請、合併請求、Claude Code 設定和 smurg 的設定。',
  'page.notHost.title': '只有主人可以使用控制台',
  'page.notHost.body': '主人控制台可以邀請成員、變更角色、踢人和查看操作紀錄。你的角色是「{role}」。',
  'nav.label': '控制台區塊',
  'nav.members': '成員',
  'nav.sessions': '所有 session',
  'nav.suggestions': '待處理的建議',
  'nav.merges': '合併請求',
  'nav.invites': '邀請連結',
  'nav.claudeConfig': 'Claude Code 專案設定',
  'nav.hostRules': '我自己的 Claude Code 規則',
  'nav.audit': '操作紀錄',
  'nav.settings': '設定',
  'load.loading': '正在載入控制台資料…',
  'load.failed': '無法載入控制台資料：{message}',
  'load.retry': '重新載入',

  // ---- security notes (SPEC §11)
  'security.title': '主人必讀的安全提醒',
  'security.unsandboxed': '每個 session（包括「可使用 agent」的成員開的）都在你的電腦上、以你的身分執行，沒有沙盒：可以讀寫你能存取的所有檔案、執行任何指令，並使用你的 Claude 帳號。',
  'security.agentRole': '只把「可使用 agent」給你完全信任的人；其他人請給「可編輯」或「旁觀」。',
  'security.injection': '客人寫進專案的檔案可能夾帶給 agent 的指示（prompt injection）。讓你的 agent 讀取客人改過的檔案之前，先看過內容。',
  'security.prompts': '允許之前，先看清楚 agent 請求許可做什麼；要把某一類指令設為一律允許之前請三思。你自己的 Claude Code 設定裡的允許規則，在這裡的 agent 身上也適用：這個頁面會列出它們。',
  'security.account': '這裡的 agent 使用你的 Claude Code 登入。個人的 Pro 或 Max 訂閱只供你自己使用：有其他人在這裡使用 agent 時，請改用 API 金鑰、Team 或 Enterprise 方案。',
  'security.conversations': '每位成員都能讀到所有對話，包括已封存主題的對話和他們加入之前的對話，而且 agent 可能會複述它讀到的內容。身為主人，你可以從對話中移除單一則內容，或把已封存的主題連同其中的一切刪除。',
  'security.invites': '邀請連結含有加入用的密鑰，只透過私人管道傳給要邀請的人；不需要的連結請撤銷。',

  // ---- members
  'members.title': '成員（{count}）',
  'members.caption': '成員',
  'members.col.member': '成員',
  'members.col.status': '狀態',
  'members.col.role': '角色',
  'members.col.devices': '裝置',
  'members.col.activity': '正在做什麼',
  'members.col.actions': '操作',
  'members.you': '（你）',
  'members.online': '線上',
  'members.onlineConnections': '線上（{count} 個連線）',
  'members.offline': '離線',
  'members.roleLabel': '{name} 的角色',
  'members.devices.none': '沒有裝置',
  'members.device.web': '網頁',
  'members.device.cli': '終端機',
  'members.device.item': '{name}（{kind}）',
  'members.device.lastSeen': '最後連線：{time}',
  'members.device.connected': '連線中（{time}連上）',
  'members.device.revoked': '已撤銷',
  'members.activity.file': '正在看 {path}',
  'members.activity.fileWorktree': '正在看 worktree 裡的 {path}',
  'members.activity.sessions': '{count} 個 session 執行中',
  'members.activity.none': '沒有進行中的活動',
  'members.kick': '踢出',
  'members.kickLabel': '踢出 {name}',
  'members.empty': '還沒有其他成員。建立邀請連結，把組員拉進來。',
  'members.roleChanged': '已把 {name} 的角色改為「{role}」，對方會自動重新連線並套用新權限。',
  'members.roleFailed': '無法變更 {name} 的角色：{message}',
  'members.hint': '變更角色後，對方會自動重新連線並套用新的權限。取消「可使用 agent」也會帶走對方開始的東西：他開的終端機和未分主題的 session 會結束，主題的 session 改由你接手。',

  // ---- kick confirmation
  'kick.title': '踢出 {name}？',
  'kick.lead': '按下「踢出」之後會立刻發生：',
  'kick.sessions': '{name} 開的所有終端機和未分主題的 session 立即終止（目前 {count} 個）。',
  'kick.topicSessions': '{name} 開始的主題 session（討論和工作項目）會停止並改由你接手：agent 的這一輪被中斷，還沒回答的選擇題和權限請求會撤回（目前 {count} 個）。',
  'kick.removed': '{name} 設定的東西會移除：他設為一律允許的指令類型、他開始但還沒啟動的工作項目、他放寬的權限模式、他還在等 agent 讀取的訊息，以及他在未回答選擇題上的投票。',
  'kick.responsible': '{name} 不再是任何 session 的負責人（目前 {count} 個）：它們的選擇題改由開始 session 的人決定，或由你決定。',
  'kick.keys': '{name} 所有裝置的金鑰被撤銷，舊的裝置和舊的邀請連結都無法再連進來。',
  'kick.irreversible': '這個動作無法復原。要讓 {name} 回來，必須建立新的邀請連結。',
  'kick.confirm': '踢出 {name}',
  'kick.done': '已踢出 {name}。',
  'kick.failed': '無法踢出 {name}：{message}',

  // ---- a role change that takes something away (DESIGN §3.9)
  'demote.title': '把 {name} 的角色改成「{role}」？',
  'demote.sessions': '{name} 開的終端機和未分主題的 session 會結束（目前 {count} 個）。',
  'demote.topicSessions': '{name} 開始的主題 session（討論和工作項目）改由你接手，並繼續執行（目前 {count} 個）。',
  'demote.removed': '{name} 設定的東西會移除：他設為一律允許的指令類型、他開始但還沒啟動的工作項目、他放寬的權限模式，以及他還在等 agent 讀取的訊息。',
  'demote.viewer': '「旁觀」只能觀看：{name} 在未回答選擇題上的投票會移除，{name} 也不再是任何 session 的負責人（目前 {count} 個）。',
  'demote.viewerNone': '「旁觀」只能觀看：{name} 在未回答選擇題上的投票會移除，{name} 也不能再擔任 session 的負責人。',
  'demote.confirm': '變更角色',

  // ---- 「可使用 agent」: the risk, confirmed before an invite or a role change applies
  'roleRisk.text': '可使用 agent 的人可以請 agent 在你的電腦上執行任何指令、讀取你家目錄裡的檔案，並使用你的 Claude 帳號。只開給你完全信任的人。',
  'roleRisk.memberTitle': '把 {name} 的角色改成「可使用 agent」？',
  'roleRisk.inviteTitle': '建立「可使用 agent」的邀請連結？',
  'roleRisk.confirmMember': '我了解，變更角色',
  'roleRisk.confirmInvite': '我了解，建立邀請連結',

  // ---- sessions
  'sessions.title': '所有 session（{count}）',
  'sessions.caption': '所有 session',
  'sessions.col.title': '名稱',
  'sessions.col.topic': '主題',
  'sessions.col.purpose': '類型',
  'sessions.col.status': '狀態',
  'sessions.col.responsible': '負責人',
  'sessions.col.owner': '開啟的人',
  'sessions.col.where': '位置',
  'sessions.col.actions': '操作',
  'sessions.topic.none': '未分主題',
  'sessions.purpose.discussion': '討論',
  'sessions.purpose.item': '工作項目',
  'sessions.purpose.itemAttempt': '工作項目（第 {attempt} 次）',
  'sessions.purpose.free': 'agent session',
  'sessions.purpose.terminal': '終端機',
  'sessions.responsible.nobody': '無',
  'sessions.status.starting': '啟動中',
  'sessions.status.running': '執行中',
  'sessions.status.exited': '已結束',
  'sessions.status.exitedCode': '已結束（結束代碼 {code}）',
  'sessions.where.main': '主工作區',
  'sessions.where.worktreeGone': '已移除的 worktree',
  'sessions.viewers': '{count} 個連線觀看中',
  'sessions.agentFile': '正在處理 {path}',
  'sessions.terminate': '終止',
  'sessions.terminateLabel': '終止 {owner} 開的「{title}」',
  'sessions.terminated': '已終止 {owner} 開的「{title}」。',
  'sessions.terminateFailed': '無法終止 {title}：{message}',
  'sessions.empty': '目前沒有執行中的 session。',
  'sessions.loadFailed': '無法載入 session：{message}',
  'sessions.showExited': '顯示已結束的 session（{count}）',
  'sessions.hideExited': '隱藏已結束的 session',
  'sessions.confirm.title': '終止「{title}」？',
  'sessions.confirm.discussion': '這是主題「{topic}」的討論。終止之後，在有人重新開始討論之前，沒有人可以請 agent 修改 spec 或產生計畫。spec、計畫和工作項目都會保留。',
  'sessions.confirm.item': '這個 session 正在處理主題「{topic}」的工作項目。終止之後這個項目會停止；它的 worktree 和 agent 目前改過的內容都會保留，可以從計畫再試一次。',

  // ---- the host's Claude account and the disk space of the conversations (above the sessions table)
  'account.title': '你的 Claude 帳號',
  'account.ok': '你的 Claude 帳號：沒有回報任何問題。',
  'account.noticeDismiss': '知道了',
  'account.loggedOut': '你電腦上的 Claude Code 尚未登入。請在自己的終端機執行 claude 並登入。',
  'account.usageLimit': '你的 Claude 帳號已達用量上限。',
  'account.usageLimitUntil': '你的 Claude 帳號已達用量上限，{time} 重置。',
  'account.sessionsWait': '有 {count} 個 agent session 在等。',
  'storage.title': '對話紀錄佔用的磁碟空間',
  'storage.full': '儲存的對話紀錄佔用的磁碟空間超過了 smurg 為它保留的上限。smurg 不會自動移除任何內容：請刪除不再需要的已封存主題。',

  // ---- pending suggestions (read-only)
  'suggestions.title': '待處理的建議（{count}）',
  'suggestions.lead': '這裡只供瀏覽。建議要等你或「可使用 agent」的成員在 session 對話裡的卡片上採用，才會送到 agent。',
  'suggestions.target': '{author} → {title}',
  'suggestions.targetTopic': '{author} → {topic} › {title}',
  'suggestions.open': '開啟',
  'suggestions.openLabel': '在 session 裡開啟 {author} 的建議',
  'suggestions.unknownSession': '{author} → 已不存在的 session',
  'suggestions.source': '附上 {path} 第 {start}–{end} 行',
  'suggestions.empty': '目前沒有待處理的建議。',
  'suggestions.loadFailed': '無法載入建議：{message}',

  // ---- invites
  'invites.title': '邀請連結',
  'invites.create': '建立邀請連結',
  'invites.role': '角色',
  'invites.expiry': '有效期限',
  'invites.expiry.1h': '1 小時',
  'invites.expiry.1d': '1 天',
  'invites.expiry.7d': '7 天',
  'invites.expiry.30d': '30 天',
  'invites.maxUses': '可使用次數',
  'invites.maxUsesHint': '留空表示在期限內不限次數。',
  'invites.maxUsesInvalid': '請輸入 1 到 {max} 之間的整數，或留空。',
  'invites.roleHint.agent': '可以開始主題、開 agent 和終端機（在你的電腦上、用你的 Claude 帳號執行），傳訊息給任何 agent、回答它的權限請求，並採用建議。',
  'invites.roleHint.editor': '可以編輯檔案、對 agent 的選擇題投票、寫建議給 agent，但不能開 agent，也不能直接傳訊息給 agent。',
  'invites.roleHint.viewer': '只能瀏覽檔案和觀看 session。',
  'invites.history': '新成員可以讀到這個工作區先前的所有對話，包括已封存主題的對話。',
  'invites.createFailed': '無法建立邀請連結：{message}',
  'invites.link.title': '邀請連結已建立',
  'invites.link.once': '這個連結只會顯示這一次，關閉之後就看不到了。如果弄丟了，請撤銷它再建立新的。',
  'invites.link.secret': '連結裡含有加入工作區用的密鑰：請只透過私人管道（例如私訊）傳給要邀請的人，不要貼在群組或公開的地方。',
  'invites.link.summary': '角色「{role}」，{expiry}後到期，{uses}。',
  'invites.link.usesLimited': '可以使用 {count} 次',
  'invites.link.usesUnlimited': '期限內不限次數',
  'invites.link.label': '邀請連結',
  'invites.link.copy': '複製邀請連結',
  'invites.link.done': '我已經複製好了',
  'invites.caption': '邀請連結',
  'invites.col.role': '角色',
  'invites.col.created': '建立時間',
  'invites.col.expires': '到期時間',
  'invites.col.uses': '使用次數',
  'invites.col.status': '狀態',
  'invites.col.actions': '操作',
  'invites.expires.none': '沒有期限',
  'invites.uses.limited': '已用 {uses} 次，剩 {left} 次',
  'invites.uses.unlimited': '已用 {uses} 次，不限次數',
  'invites.status.active': '有效',
  'invites.status.revoked': '已撤銷',
  'invites.status.expired': '已過期',
  'invites.status.usedUp': '已用完',
  'invites.revoke': '撤銷',
  'invites.revokeLabel': '撤銷 {time} 建立的「{role}」邀請',
  'invites.revoked': '已撤銷邀請連結，它不能再用來加入。',
  'invites.revokeFailed': '無法撤銷邀請連結：{message}',
  'invites.empty': '目前沒有有效的邀請連結。',
  'invites.showInactive': '顯示已失效的邀請（{count}）',
  'invites.hideInactive': '隱藏已失效的邀請',

  // ---- merge requests
  'merges.title': '合併請求',

  // ---- Claude Code project settings: the trust gate (DESIGN §2.9)
  'claudeConfig.title': 'Claude Code 專案設定',
  'claudeConfig.lead': '資料夾可以帶有自己的 Claude Code 設定（.claude/settings.json、.claude/settings.local.json、.mcp.json）。agent session 只有在你確認過完全相同的內容之後才會載入它們；在那之前不會載入這些設定，也不會載入專案的 CLAUDE.md。',
  'claudeConfig.loading': '正在讀取專案設定…',
  'claudeConfig.loadFailed': '無法讀取專案設定：{message}',
  'claudeConfig.root.waiting': '等你決定',
  'claudeConfig.state.undecided': '你還沒有決定這份內容。這個資料夾裡的 agent session 目前不會載入這些設定。',
  'claudeConfig.state.used': '這個資料夾裡的 agent session 會使用這些設定。',
  'claudeConfig.state.ignored': '這個資料夾裡的 agent session 不會載入這些設定，也不會載入專案的 CLAUDE.md。',
  'claudeConfig.state.none': '這個資料夾沒有 Claude Code 專案設定。',
  'claudeConfig.warning': '只要有 agent 在這個資料夾工作，下面的指令就會以你的身分在你的電腦上執行。任何可以編輯這個資料夾裡檔案的人，都能修改這些指令呼叫的腳本。',
  'claudeConfig.file.trusted': '使用中',
  'claudeConfig.file.ignored': '不載入',
  'claudeConfig.file.changed': '在你決定之後有變動',
  'claudeConfig.file.new': '尚未決定',
  'claudeConfig.file.nothing': '這個檔案不執行指令、不變更權限，也不設定變數。',
  'claudeConfig.file.show': '顯示 {path}',
  'claudeConfig.group.runs': '會執行的指令',
  'claudeConfig.group.permissions': '會變更的權限',
  'claudeConfig.group.env': '會設定的環境變數',
  'claudeConfig.group.other': '其他設定',
  'claudeConfig.group.scripts': '這些指令呼叫的腳本（設定使用期間，透過 smurg 只有你可以修改）',
  'claudeConfig.env.flagged': '可能把你的登入資訊送到其他伺服器',
  'claudeConfig.ack.legend': '使用之前，請勾選你已經讀過的事項',
  'claudeConfig.ack.credentials': '這些設定可能把我的 Claude 登入資訊送到其他伺服器（有標記的變數，或提供 API 金鑰的指令）。',
  'claudeConfig.ack.allowsTools': '這些設定讓 agent 不經詢問就能執行指令、編輯檔案或呼叫 MCP 工具。',
  'claudeConfig.applies': '決定會在 session 的 agent 下次啟動時生效。',
  'claudeConfig.trust': '使用',
  'claudeConfig.ignore': '不載入',
  'claudeConfig.decideFailed': '無法儲存決定：{message}',
  'claudeConfig.choice.title': '這個資料夾有 Claude Code 專案設定',
  'claudeConfig.choice.ignore': '不載入（agent 不會讀 CLAUDE.md）',

  // ---- the host's own Claude Code allow rules: information only (OWNER-DECISIONS Q7)
  'hostRules.title': '我自己的 Claude Code 規則',
  'hostRules.loading': '正在讀取你的規則…',
  'hostRules.loadFailed': '無法讀取你的規則：{message}',
  'hostRules.none': '沒有找到你自己的 Claude Code 設定裡的允許規則。有 agent session 啟動之後，這裡才會列出來。',
  'hostRules.explain': '這裡的每個 agent session 都以你的身分、用你的 Claude Code 設定執行：下面的規則允許的事情不會出現權限請求，不論是誰傳訊息給 agent。smurg 不會增加或移除這些規則。討論 agent 能做的事仍然由 smurg 限制，不受這些規則影響。',
  'hostRules.change': '要變更它們，請在你的電腦上編輯 Claude Code 的設定。session 的 agent 下次啟動時就會依照新的設定。',
  'hostRules.source.user': '你的使用者設定（~/.claude/settings.json）',
  'hostRules.source.project': '專案的設定（.claude/settings.json）',
  'hostRules.source.local': '專案的本機設定（.claude/settings.local.json）',
  'hostRules.source.managed': '受管理的設定（由管理員設定）',

  // ---- removing one entry of a conversation (admin.transcript.redact)
  'redact.title': '移除這則內容？',
  'redact.where': '位於 {title}',
  'redact.replaced': '所有人會在原處看到「{text}」。儲存在你電腦上的對話紀錄也會一併修改。',
  'redact.memory': 'Claude Code 自己另外保存了這段對話：agent 可能仍然知道這則內容說了什麼。',
  'redact.irreversible': '這個動作無法復原。',
  'redact.confirm': '移除內容',
  'redact.done': '已移除這則內容。',
  'redact.failed': '無法移除這則內容：{message}',

  // ---- audit log
  'audit.title': '操作紀錄',
  'audit.lead': '最新的在最上面，新的紀錄會即時出現。操作紀錄只存在你的電腦上。',
  'audit.caption': '操作紀錄',
  'audit.col.time': '時間',
  'audit.col.actor': '誰',
  'audit.col.action': '動作',
  'audit.col.target': '對象',
  'audit.col.outcome': '結果',
  'audit.col.detail': '內容',
  'audit.detail.show': '詳細',
  'audit.detail.label': '這筆紀錄的詳細內容',
  'audit.detail.authorName': '提出者',
  'audit.detail.text': '建議內容',
  'audit.detail.finalText': '採用的內容',
  'audit.detail.rejectReason': '拒絕原因',
  'audit.detail.outcome': '處理方式',
  'audit.detail.accepted': '採用',
  'audit.detail.acceptedModified': '修改後採用',
  'audit.detail.rejected': '拒絕',
  'audit.detail.withdrawn': '撤回',
  'audit.detail.conflictFiles': '衝突的檔案',
  'audit.detail.from': '原本',
  'audit.detail.to': '改為',
  'audit.detail.role': '角色',
  'audit.detail.reason': '原因',
  'audit.detail.source': '附上的程式碼',
  'audit.detail.branch': '分支',
  'audit.detail.message': '說明',
  'audit.detail.command': '指令',
  'audit.detail.tool': '工具',
  'audit.detail.rule': '一律允許的類型',
  'audit.detail.decision': '決定',
  'audit.detail.mode': '模式',
  'audit.detail.purpose': '用途',
  'audit.outcome.ok': '成功',
  'audit.outcome.denied': '拒絕',
  'audit.outcome.error': '錯誤',
  'audit.loadOlder': '載入較舊的紀錄',
  'audit.end': '沒有更舊的紀錄了。',
  'audit.limit': '最多顯示 {max} 筆紀錄。',
  'audit.count': '已載入 {count} 筆',
  'audit.empty': '還沒有任何紀錄。',
  'audit.olderFailed': '無法載入較舊的紀錄：{message}',
  'audit.action.auth.join': '加入工作區',
  'audit.action.auth.connect': '連線',
  'audit.action.auth.disconnect': '中斷連線',
  'audit.action.auth.rejected': '連線被拒絕',
  'audit.action.authz.denied': '權限不足被拒絕',
  'audit.action.path.denied': '路徑被拒絕',
  'audit.action.file.write': '寫入檔案',
  'audit.action.file.create': '建立檔案',
  'audit.action.file.rename': '重新命名檔案',
  'audit.action.file.delete': '刪除檔案',
  'audit.action.file.upload': '上傳檔案',
  'audit.action.file.download': '下載檔案',
  'audit.action.doc.edit': '編輯文件',
  'audit.action.agent.edit': 'agent 修改檔案',
  'audit.action.external.change': '外部程式修改檔案',
  'audit.action.doc.conflict': '編輯衝突',
  'audit.action.doc.conflict-resolve': '處理編輯衝突',
  'audit.action.lock.acquire': '取得檔案鎖',
  'audit.action.lock.release': '釋放檔案鎖',
  'audit.action.lock.denied': '檔案鎖被拒絕',
  'audit.action.lock.force-release': '強制釋放檔案鎖',
  'audit.action.session.create': '開啟 session',
  'audit.action.session.end': '結束 session',
  'audit.action.session.terminate': '終止 session',
  'audit.action.session.message': '傳訊息給 agent',
  'audit.action.smurg.message': 'smurg 傳訊息給 agent',
  'audit.action.session.interrupt': '停止 agent',
  'audit.action.session.retry': '重新啟動失敗的 session',
  'audit.action.session.restart': '重新啟動 session 的 agent',
  'audit.action.session.responsible': '變更負責人',
  'audit.action.session.mode': '變更權限模式',
  'audit.action.session.rule.remove': '移除一律允許的類型',
  'audit.action.session.handover': 'session 改由主人接手',
  'audit.action.responsible.fallback': '負責人自動改派',
  'audit.action.question.submit': '送出答案',
  'audit.action.question.remind': '提醒還沒投票的人',
  'audit.action.permission.decide': '回答權限請求',
  'audit.action.permission.auto': '權限請求自動回答',
  'audit.action.permission.auto-deny': 'smurg 拒絕了工具呼叫',
  'audit.action.agent.command': 'agent 執行指令',
  'audit.action.topic.create': '建立主題',
  'audit.action.topic.rename': '重新命名主題',
  'audit.action.topic.archive': '封存或還原主題',
  'audit.action.topic.delete': '刪除主題',
  'audit.action.topic.discussion.restart': '重新開始討論',
  'audit.action.topic.spec.request': '請 agent 寫 spec',
  'audit.action.topic.rule.add': '新增主題一律允許的類型',
  'audit.action.topic.rule.remove': '移除主題一律允許的類型',
  'audit.action.plan.generate': '請 agent 產生計畫',
  'audit.action.plan.start': '開始工作項目',
  'audit.action.plan.resume': '繼續暫停的計畫',
  'audit.action.plan.assign': '變更工作項目的負責人',
  'audit.action.plan.mode': '變更計畫的指派方式',
  'audit.action.plan.item.retry': '再試一次工作項目',
  'audit.action.plan.item.continue': '請 agent 繼續',
  'audit.action.plan.item.resolve': '請 agent 解決合併衝突',
  'audit.action.scheduler.start': 'smurg 啟動了工作項目',
  'audit.action.scheduler.disarm': 'smurg 沒有啟動工作項目',
  'audit.action.report.register': '登記結果報告',
  'audit.action.report.review': '看過結果報告',
  'audit.action.spec.commit': '提交 spec 和計畫',
  'audit.action.claude-config.decide': '決定 Claude Code 專案設定',
  'audit.action.transcript.redact': '移除對話內容',
  'audit.action.suggest.create': '提出建議',
  'audit.action.suggest.edit': '修改建議',
  'audit.action.suggest.accept': '採用建議',
  'audit.action.suggest.reject': '拒絕建議',
  'audit.action.suggest.withdraw': '撤回建議',
  'audit.action.worktree.create': '建立 worktree',
  'audit.action.worktree.remove': '移除 worktree',
  'audit.action.worktree.merge.request': '請求合併',
  'audit.action.worktree.merge.approve': '核准合併',
  'audit.action.worktree.merge.reject': '拒絕合併',
  'audit.action.member.role': '變更角色',
  'audit.action.member.kick': '踢出成員',
  'audit.action.member.leave': '成員離開',
  'audit.action.invite.create': '建立邀請',
  'audit.action.invite.revoke': '撤銷邀請',
  'audit.action.device.revoke': '撤銷裝置金鑰',
  'audit.action.settings.change': '變更設定',

  // ---- settings
  'settings.title': '設定',
  'settings.lead': '儲存後立即套用，不需要重新啟動。',
  'settings.loading': '正在載入設定…',
  'settings.sharedDirs': '共享資料夾（在 worktree 裡唯讀）',
  'settings.sharedDirsHint': '每行一個相對於分享資料夾的路徑，例如 data 或 models/checkpoints。建立 worktree 時，會以唯讀的符號連結放進去，適合不在 git 裡的大型資料。',
  'settings.humanLockIdle': '編輯鎖閒置釋放時間（秒）',
  'settings.humanLockIdleHint': '最後一位編輯者閒置超過這個時間，agent 就可以修改這個檔案。預設 30 秒。',
  'settings.agentLockTimeout': 'agent 修改鎖逾時（秒）',
  'settings.agentLockTimeoutHint': 'agent 修改檔案時的鎖最多保留多久。預設 60 秒。',
  'settings.diskReserveGb': '保留磁碟空間（GB）',
  'settings.diskReservePercent': '保留磁碟空間（%）',
  'settings.diskHint': '上傳開始前，daemon 確認上傳後仍保留兩者中較大的空間，不足就拒絕上傳。預設 5 GB 或 5%。',
  'settings.agents': 'agent 相關設定',
  'settings.maxLiveAgents': '同時執行的工作項目數量',
  'settings.maxLiveAgentsHint': 'smurg 在你的電腦上最多同時執行幾個工作項目（{min} 到 {max}）。其餘的會等待空出來的 agent。有人傳訊息時一定會有 agent 處理。',
  'settings.escalateAfter': '等多久之後也詢問其他人（分鐘）',
  'settings.escalateAfterHint': '選擇題或權限請求等了這麼久之後，也會送到你和「可使用 agent」的成員那裡。結果報告則是 {factor} 倍的時間。預設 {minutes} 分鐘。',
  'settings.agentMcp': 'agent 可以使用我自己的和這個專案的 MCP 伺服器',
  'settings.agentMcpHint': '關閉：agent 只有 smurg 自己的工具。開啟：任何「可使用 agent」的成員操作的 agent 都能呼叫這些伺服器（郵件、雲端硬碟、聊天等），而且它們的回應所有成員都看得到。討論 agent 永遠不會有這些工具。專案的伺服器還需要你在「Claude Code 專案設定」裡確認。',
  'settings.save': '儲存設定',
  'settings.reset': '還原',
  'settings.saved': '設定已儲存並立即套用。',
  'settings.saveFailed': '無法儲存設定：{message}',
  'settings.invalid': '有 {count} 個欄位需要修正。',
  'settings.error.required': '請輸入數值。',
  'settings.error.number': '請輸入數字。',
  'settings.error.min': '請輸入 {min} 以上的數字。',
  'settings.error.range': '請輸入 {min} 到 {max} 之間的數字。',
  'settings.error.integer': '請輸入 {min} 到 {max} 之間的整數。',
  'settings.error.dir': '「{value}」不是有效的資料夾路徑：請用相對於分享資料夾的路徑，不能以 / 開頭，也不能包含 . 或 .. 這樣的片段。',
  'settings.error.duplicate': '「{value}」重複了。',
  'settings.error.tooMany': '最多 {max} 個。',
  'suggestions.sourceLine': '附上 {path} 第 {start} 行',
} as const;
