import { defineStrings } from '../../strings/catalog.ts';

// Namespace of the host console feature (members, sessions, suggestions, invites, merge requests, audit log, settings).
export const t = defineStrings('console', {
  // ---- page
  'page.title': '主人控制台',
  'page.lead': '在這個畫面看到所有成員和所有 agent 在做什麼，一鍵終止 session 或踢出成員，並管理邀請、合併請求和設定。',
  'page.notHost.title': '只有主人可以使用控制台',
  'page.notHost.body': '主人控制台可以邀請成員、變更角色、踢人和查看操作紀錄。你的角色是「{role}」。',
  'nav.label': '控制台區塊',
  'nav.members': '成員',
  'nav.sessions': '所有 session',
  'nav.suggestions': '待處理的建議',
  'nav.merges': '合併請求',
  'nav.invites': '邀請連結',
  'nav.audit': '操作紀錄',
  'nav.settings': '設定',
  'load.loading': '正在載入控制台資料…',
  'load.failed': '無法載入控制台資料：{message}',
  'load.retry': '重新載入',

  // ---- security notes (SPEC §11)
  'security.title': '主人必讀的安全提醒',
  'security.unsandboxed': '你的 agent 不在沙盒裡：它可以讀寫你電腦上所有你能存取的檔案，也能執行任何指令。',
  'security.injection': '客人寫進專案的檔案可能夾帶給 agent 的指示（prompt injection）。讓你的 agent 讀取客人改過的檔案之前，先看過內容。',
  'security.prompts': '請保持 Claude Code 的權限確認開啟：不要使用略過權限確認的模式，每次都看清楚 agent 要做什麼再允許。',
  'security.invites': '邀請連結含有加入用的密鑰，只透過私人管道傳給要邀請的人；不需要的連結請撤銷。',

  // ---- members
  'members.title': '成員（{count}）',
  'members.caption': '成員',
  'members.col.member': '成員',
  'members.col.status': '狀態',
  'members.col.role': '角色',
  'members.col.devices': '裝置',
  'members.col.activity': '正在做什麼',
  'members.col.actions': '操作',
  'members.you': '（你）',
  'members.online': '線上',
  'members.onlineConnections': '線上（{count} 個連線）',
  'members.offline': '離線',
  'members.roleLabel': '{name} 的角色',
  'members.devices.none': '沒有裝置',
  'members.device.web': '網頁',
  'members.device.cli': '終端機',
  'members.device.item': '{name}（{kind}）',
  'members.device.lastSeen': '最後連線：{time}',
  'members.device.connected': '連線中（{time}連上）',
  'members.device.revoked': '已撤銷',
  'members.activity.file': '正在看 {path}',
  'members.activity.fileWorktree': '正在看 worktree 裡的 {path}',
  'members.activity.sessions': '{count} 個 session 執行中',
  'members.activity.none': '沒有進行中的活動',
  'members.kick': '踢出',
  'members.kickLabel': '踢出 {name}',
  'members.empty': '還沒有其他成員。建立邀請連結，把組員拉進來。',
  'members.roleChanged': '已把 {name} 的角色改為「{role}」，對方會自動重新連線並套用新權限。',
  'members.roleFailed': '無法變更 {name} 的角色：{message}',
  'members.hint': '變更角色後，對方會自動重新連線並套用新的權限；失去「可執行 agent」角色時，他的 session 會結束、暫存目錄會刪除。',

  // ---- kick confirmation
  'kick.title': '踢出 {name}？',
  'kick.lead': '按下「踢出」之後會立刻發生：',
  'kick.sessions': '{name} 的所有 session 立即終止（目前 {count} 個）。',
  'kick.keys': '{name} 所有裝置的金鑰被撤銷，舊的裝置和舊的邀請連結都無法再連進來。',
  'kick.tempDir': '{name}在你電腦上的暫存目錄被刪除，裡面的 Claude 登入資料也一起刪除。',
  'kick.irreversible': '這個動作無法復原。要讓 {name} 回來，必須建立新的邀請連結。',
  'kick.confirm': '踢出 {name}',
  'kick.done': '已踢出 {name}。',
  'kick.failed': '無法踢出 {name}：{message}',

  // ---- demotion that ends sessions
  'demote.title': '變更 {name} 的角色？',
  'demote.body': '{name} 目前有 {count} 個 session。改成「{role}」之後就不能再執行 agent：這些 session 會結束，暫存目錄也會刪除。',
  'demote.confirm': '變更角色',

  // ---- sessions
  'sessions.title': '所有 session（{count}）',
  'sessions.caption': '所有 session',
  'sessions.col.title': '名稱',
  'sessions.col.owner': '擁有者',
  'sessions.col.status': '狀態',
  'sessions.col.where': '位置',
  'sessions.col.sandbox': '沙盒',
  'sessions.col.viewers': '觀看中',
  'sessions.col.actions': '操作',
  'sessions.kind.agent': 'agent',
  'sessions.kind.terminal': '終端機',
  'sessions.status.starting': '啟動中',
  'sessions.status.running': '執行中',
  'sessions.status.exited': '已結束',
  'sessions.status.exitedCode': '已結束（結束代碼 {code}）',
  'sessions.where.main': '主工作區',
  'sessions.where.worktree': 'worktree 分支 {branch}',
  'sessions.where.worktreeGone': '已移除的 worktree',
  'sessions.sandboxed': '沙盒內',
  'sessions.unsandboxed': '無沙盒（主人）',
  'sessions.viewers': '{count} 人',
  'sessions.agentFile': '正在處理 {path}',
  'sessions.terminate': '終止',
  'sessions.terminateLabel': '終止{owner}的「{title}」',
  'sessions.terminated': '已終止{owner}的「{title}」。',
  'sessions.terminateFailed': '無法終止 {title}：{message}',
  'sessions.empty': '目前沒有執行中的 session。',
  'sessions.loadFailed': '無法載入 session：{message}',
  'sessions.showExited': '顯示已結束的 session（{count}）',
  'sessions.hideExited': '隱藏已結束的 session',

  // ---- pending suggestions (read-only)
  'suggestions.title': '待處理的建議（{count}）',
  'suggestions.lead': '這裡只供瀏覽：採用或拒絕由 session 的擁有者在工作區裡處理。',
  'suggestions.target': '{author} → {owner} 的 {title}',
  'suggestions.unknownSession': '{author} → 已不存在的 session',
  'suggestions.source': '附上 {path} 第 {start}–{end} 行',
  'suggestions.empty': '目前沒有待處理的建議。',
  'suggestions.loadFailed': '無法載入建議：{message}',

  // ---- invites
  'invites.title': '邀請連結',
  'invites.create': '建立邀請連結',
  'invites.role': '角色',
  'invites.expiry': '有效期限',
  'invites.expiry.1h': '1 小時',
  'invites.expiry.1d': '1 天',
  'invites.expiry.7d': '7 天',
  'invites.expiry.30d': '30 天',
  'invites.maxUses': '可使用次數',
  'invites.maxUsesHint': '留空表示在期限內不限次數。',
  'invites.maxUsesInvalid': '請輸入 1 到 {max} 之間的整數，或留空。',
  'invites.roleHint.runner': '可以編輯檔案，也可以在沙盒裡開自己的 agent 和終端機。',
  'invites.roleHint.editor': '可以編輯檔案、對別人的 session 提建議，但不能開 agent。',
  'invites.roleHint.viewer': '只能瀏覽檔案和觀看 session。',
  'invites.createFailed': '無法建立邀請連結：{message}',
  'invites.link.title': '邀請連結已建立',
  'invites.link.once': '這個連結只會顯示這一次，關閉之後就看不到了。如果弄丟了，請撤銷它再建立新的。',
  'invites.link.secret': '連結裡含有加入工作區用的密鑰：請只透過私人管道（例如私訊）傳給要邀請的人，不要貼在群組或公開的地方。',
  'invites.link.summary': '角色「{role}」，{expiry}後到期，{uses}。',
  'invites.link.usesLimited': '可以使用 {count} 次',
  'invites.link.usesUnlimited': '期限內不限次數',
  'invites.link.label': '邀請連結',
  'invites.link.copy': '複製邀請連結',
  'invites.link.done': '我已經複製好了',
  'invites.caption': '邀請連結',
  'invites.col.role': '角色',
  'invites.col.created': '建立時間',
  'invites.col.expires': '到期時間',
  'invites.col.uses': '使用次數',
  'invites.col.status': '狀態',
  'invites.col.actions': '操作',
  'invites.expires.none': '沒有期限',
  'invites.uses.limited': '已用 {uses} 次，剩 {left} 次',
  'invites.uses.unlimited': '已用 {uses} 次，不限次數',
  'invites.status.active': '有效',
  'invites.status.revoked': '已撤銷',
  'invites.status.expired': '已過期',
  'invites.status.usedUp': '已用完',
  'invites.revoke': '撤銷',
  'invites.revokeLabel': '撤銷 {time} 建立的「{role}」邀請',
  'invites.revoked': '已撤銷邀請連結，它不能再用來加入。',
  'invites.revokeFailed': '無法撤銷邀請連結：{message}',
  'invites.empty': '目前沒有有效的邀請連結。',
  'invites.showInactive': '顯示已失效的邀請（{count}）',
  'invites.hideInactive': '隱藏已失效的邀請',

  // ---- merge requests
  'merges.title': '合併請求',

  // ---- audit log
  'audit.title': '操作紀錄',
  'audit.lead': '最新的在最上面，新的紀錄會即時出現。操作紀錄只存在你的電腦上。',
  'audit.caption': '操作紀錄',
  'audit.col.time': '時間',
  'audit.col.actor': '誰',
  'audit.col.action': '動作',
  'audit.col.target': '對象',
  'audit.col.outcome': '結果',
  'audit.col.detail': '內容',
  'audit.detail.show': '詳細',
  'audit.detail.label': '這筆紀錄的詳細內容',
  'audit.detail.authorName': '提出者',
  'audit.detail.text': '建議內容',
  'audit.detail.finalText': '採用的內容',
  'audit.detail.rejectReason': '拒絕原因',
  'audit.detail.outcome': '處理方式',
  'audit.detail.accepted': '採用',
  'audit.detail.acceptedModified': '修改後採用',
  'audit.detail.rejected': '拒絕',
  'audit.detail.withdrawn': '撤回',
  'audit.detail.conflictFiles': '衝突的檔案',
  'audit.detail.from': '原本',
  'audit.detail.to': '改為',
  'audit.detail.role': '角色',
  'audit.detail.reason': '原因',
  'audit.detail.source': '附上的程式碼',
  'audit.detail.branch': '分支',
  'audit.detail.message': '說明',
  'audit.outcome.ok': '成功',
  'audit.outcome.denied': '拒絕',
  'audit.outcome.error': '錯誤',
  'audit.loadOlder': '載入較舊的紀錄',
  'audit.end': '沒有更舊的紀錄了。',
  'audit.limit': '最多顯示 {max} 筆紀錄。',
  'audit.count': '已載入 {count} 筆',
  'audit.empty': '還沒有任何紀錄。',
  'audit.olderFailed': '無法載入較舊的紀錄：{message}',
  'audit.action.auth.join': '加入工作區',
  'audit.action.auth.connect': '連線',
  'audit.action.auth.disconnect': '中斷連線',
  'audit.action.auth.rejected': '連線被拒絕',
  'audit.action.authz.denied': '權限不足被拒絕',
  'audit.action.path.denied': '路徑被拒絕',
  'audit.action.file.write': '寫入檔案',
  'audit.action.file.create': '建立檔案',
  'audit.action.file.rename': '重新命名檔案',
  'audit.action.file.delete': '刪除檔案',
  'audit.action.file.upload': '上傳檔案',
  'audit.action.file.download': '下載檔案',
  'audit.action.doc.edit': '編輯文件',
  'audit.action.agent.edit': 'agent 修改檔案',
  'audit.action.external.change': '外部程式修改檔案',
  'audit.action.doc.conflict': '編輯衝突',
  'audit.action.doc.conflict-resolve': '處理編輯衝突',
  'audit.action.lock.acquire': '取得檔案鎖',
  'audit.action.lock.release': '釋放檔案鎖',
  'audit.action.lock.denied': '檔案鎖被拒絕',
  'audit.action.lock.force-release': '強制釋放檔案鎖',
  'audit.action.session.create': '開啟 session',
  'audit.action.session.end': '結束 session',
  'audit.action.session.terminate': '終止 session',
  'audit.action.session.import-config': '匯入個人設定',
  'audit.action.sandbox.refused': '沙盒拒絕啟動',
  'audit.action.suggest.create': '提出建議',
  'audit.action.suggest.edit': '修改建議',
  'audit.action.suggest.accept': '採用建議',
  'audit.action.suggest.reject': '拒絕建議',
  'audit.action.suggest.withdraw': '撤回建議',
  'audit.action.worktree.create': '建立 worktree',
  'audit.action.worktree.remove': '移除 worktree',
  'audit.action.worktree.merge.request': '請求合併',
  'audit.action.worktree.merge.approve': '核准合併',
  'audit.action.worktree.merge.reject': '拒絕合併',
  'audit.action.member.role': '變更角色',
  'audit.action.member.kick': '踢出成員',
  'audit.action.member.leave': '成員離開',
  'audit.action.invite.create': '建立邀請',
  'audit.action.invite.revoke': '撤銷邀請',
  'audit.action.device.revoke': '撤銷裝置金鑰',
  'audit.action.settings.change': '變更設定',

  // ---- settings
  'settings.title': '設定',
  'settings.lead': '儲存後立即套用，不需要重新啟動。',
  'settings.loading': '正在載入設定…',
  'settings.sharedDirs': '共享資料夾（在 worktree 裡唯讀）',
  'settings.sharedDirsHint': '每行一個相對於分享資料夾的路徑，例如 data 或 models/checkpoints。建立 worktree 時，會以唯讀的符號連結放進去，適合不在 git 裡的大型資料。',
  'settings.allowedDomains': '客人沙盒可以連線的額外網域',
  'settings.allowedDomainsHint': '每行一個，例如 example.com、*.example.com 或 example.com:8080。Anthropic 和常見的套件庫已經預設允許。',
  'settings.humanLockIdle': '編輯鎖閒置釋放時間（秒）',
  'settings.humanLockIdleHint': '最後一位編輯者閒置超過這個時間，agent 就可以修改這個檔案。預設 30 秒。',
  'settings.agentLockTimeout': 'agent 修改鎖逾時（秒）',
  'settings.agentLockTimeoutHint': 'agent 修改檔案時的鎖最多保留多久。預設 60 秒。',
  'settings.diskReserveGb': '保留磁碟空間（GB）',
  'settings.diskReservePercent': '保留磁碟空間（%）',
  'settings.diskHint': '上傳開始前，daemon 確認上傳後仍保留兩者中較大的空間，不足就拒絕上傳。預設 5 GB 或 5%。',
  'settings.save': '儲存設定',
  'settings.reset': '還原',
  'settings.saved': '設定已儲存並立即套用。',
  'settings.saveFailed': '無法儲存設定：{message}',
  'settings.invalid': '有 {count} 個欄位需要修正。',
  'settings.error.required': '請輸入數值。',
  'settings.error.number': '請輸入數字。',
  'settings.error.min': '請輸入 {min} 以上的數字。',
  'settings.error.range': '請輸入 {min} 到 {max} 之間的數字。',
  'settings.error.dir': '「{value}」不是有效的資料夾路徑：請用相對於分享資料夾的路徑，不能以 / 開頭，也不能包含 . 或 .. 這樣的片段。',
  'settings.error.domain': '「{value}」不是有效的網域，請寫成 example.com、*.example.com 或 example.com:8080。',
  'settings.error.duplicate': '「{value}」重複了。',
  'settings.error.tooMany': '最多 {max} 個。',
});
