import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the topics feature: the New topic dialog, the spec, plan, report and Changes columns, the Start dialog
// and a topic's small dialogs (UX §6; DESIGN §5.12 items 18–23). English defines the keys; strings.zh-TW.ts holds the
// same keys in Traditional Chinese. Plan badges, the Start dialog's lines and a report's headings are composed here
// from structured fields; text people or agents wrote is never translated.
export const t = defineStrings(
  'topics',
  {
    sep: ' · ',
    loading: 'Loading…',
    'people.host': 'the host',
    'archived.note': 'This topic is archived. Restore it to continue.',

    // ---- views and menus
    'view.read': 'Read',
    'view.edit': 'Edit',
    'view.edit.viewer': 'Viewers read. Editing needs the role Editor or above.',
    'view.items': 'Items',
    'view.file': 'File',
    'menu.openInCode': 'Open the file in code mode',
    'menu.rename': 'Rename topic',
    'menu.restore': 'Restore topic',

    // ---- the box that sends text to an agent
    'ask.close': 'Close',
    'ask.failed': 'Not sent: {reason}',
    'ask.offline': 'You are offline. What you typed stays here.',
    'ask.removeQuote': 'Remove the quoted section',
    'ask.tooLong': 'The text is too long (at most {max} characters).',
    'revise.open': 'Ask the agent to revise',
    'revise.section': 'Ask the agent to revise "{heading}"',
    'revise.label': 'What should the agent change?',
    'revise.placeholder': 'What should the agent change?',
    'revise.hint': "Goes to the topic's discussion session. The agent edits this file; you see the change here.",
    'revise.hint.suggestion': 'Goes to {names} as a suggestion: your role cannot message agents.',
    'revise.send': 'Ask the agent',
    'revise.send.suggestion': 'Send suggestion',
    'revise.quote': 'About the quoted text',
    'revise.quote.section': 'About the section "{heading}"',
    'sent.discussion': 'Sent to the discussion.',
    'sent.item': "Sent to this item's session.",
    'sent.suggestion': 'Sent as a suggestion to {names}.',

    // ---- the discussion's status line
    'discussion.open': 'Open the discussion',
    'discussion.restart': 'Restart discussion',
    'discussion.closed': 'The discussion of this topic is closed.',
    'discussion.idle': 'Discussion: Claude is idle.',
    'discussion.working': 'Discussion: Claude is working.',
    'discussion.workingFor': 'Discussion: Claude is working · {time}',
    'discussion.compacting': 'Discussion: Claude is shortening the conversation.',
    'discussion.question': 'Discussion: Claude asks a question.',
    'discussion.permission': 'Discussion: Claude asks for permission.',
    'discussion.failed': 'Discussion: the session failed.',
    'restart.title': 'Restart the discussion?',
    'restart.lead': 'The topic gets a new discussion session. It reads the spec and the plan again but does not know what was said before. The earlier discussion stays readable.',
    'restart.lead.lost': 'The discussion session of this topic ended. A new one reads the spec and the plan but does not know what was said before. The earlier discussion stays readable.',
    'restart.failed': 'Could not restart the discussion: {reason}',

    // ---- spec column
    'spec.view': 'Spec view',
    'spec.read.label': 'The spec',
    'spec.empty.title': 'No spec yet',
    'spec.empty.body': 'Discuss with the agent first; it writes the first draft.',
    'spec.request': 'Ask the agent to write the spec now',
    'spec.request.failed': 'Could not ask for the spec: {reason}',
    'spec.blank': 'The file is empty.',
    'spec.unreadable': 'The file could not be opened. Switch to Edit to see why.',
    'spec.changed': 'Changed by Claude at {time}',
    'spec.changedAsked': 'Changed by Claude at {time}, asked by {name}',
    'spec.showInDiscussion': 'Show in the discussion',
    'spec.generate.failed': 'Could not ask for the plan: {reason}',
    // One person or several (the count itself is not shown: two keys, chosen by `oneOrMany`).
    'spec.odd.editing.one': '{names} is editing the spec now.',
    'spec.odd.editing.many': '{names} are editing the spec now.',
    'spec.odd.openQuestions': { one: 'The spec lists {count} open question.', other: 'The spec lists {count} open questions.' },
    'spec.odd.question': 'A question is open in the discussion.',
    'spec.confirm.title': 'Generate the plan now?',
    'spec.confirm.titleUpdate': 'Update the plan now?',
    'spec.confirm.go': 'Generate plan',
    'spec.confirm.goUpdate': 'Update plan',

    // ---- plan column
    'plan.view': 'Plan view',
    'plan.generate': 'Generate plan',
    'plan.update': 'Update plan',
    'plan.generating': 'Claude is writing the plan…',
    'plan.generating.update': 'Claude is updating the plan…',
    'plan.empty.title': 'No plan yet',
    'plan.empty.body': 'Generate it from the spec.',
    'plan.empty.noSpec': 'A plan is generated from the spec, and there is no spec yet.',
    'plan.empty.openSpec': 'Open spec',
    'plan.loadFailed': 'The plan could not be loaded.',
    'plan.reload': 'Load again',
    'plan.items.label': 'Work items',
    'plan.invalid.title': 'smurg cannot read the work items from PLAN.md.',
    'plan.invalid.titleLine': 'smurg cannot read the work items from PLAN.md (line {line}).',
    'plan.invalid.last': 'Below is the last plan smurg could read. Nothing can start until the file is fixed.',
    'plan.invalid.openFile': 'Open the file',
    'plan.invalid.fix': 'Ask the agent to fix it',
    'plan.invalid.fixText': 'PLAN.md cannot be read as work items. Please fix it and check it again.',
    'plan.stale': 'The spec changed after this plan was written.',
    'plan.paused.title': "smurg was restarted on the host's computer",
    'plan.paused.body': 'Nothing in this plan runs until someone continues it.',
    'plan.paused.body.others': 'Nothing in this plan runs until it is continued. {names} can continue it.',
    'plan.paused.continue': 'Continue all',
    'plan.paused.failed': 'Could not continue: {reason}',
    'plan.removed.title': 'No longer in the plan',
    'plan.removed.body': 'These items were started and then removed from PLAN.md. They do not count for the topic.',
    'summary.items': { one: '{count} work item', other: '{count} work items' },
    'summary.canStart': '{count} can start now',
    'summary.waitsOthers': { one: '{count} waits for others', other: '{count} wait for others' },
    'summary.reviewed': '{reviewed} of {total} reviewed',
    'summary.toReview': { one: '{count} report to review', other: '{count} reports to review' },
    'summary.waitPerson': { one: '{count} waits for a person', other: '{count} wait for a person' },
    'summary.running': '{count} running',
    'summary.notStarted': '{count} not started',
    'summary.merged': '{count} merged',
    'waiting.line': 'Waiting for: {who}',
    'waiting.person': '{name} {what} ({time})',
    'waiting.questions': { one: '{count} question', other: '{count} questions' },
    'waiting.permissions': { one: '{count} permission request', other: '{count} permission requests' },
    'waiting.reports': { one: '{count} report', other: '{count} reports' },
    'split.load': '{name} {count}',

    // ---- who is responsible
    'assign.heading': 'Who is responsible',
    'assign.mode.assigned': 'Assigned',
    'assign.mode.everyone': 'No one assigned: everyone watches',
    'assign.everyone.text': 'Nobody is assigned. Permission requests go to {names}. Anyone but a viewer can review a report. Questions are decided by the person who presses Start.',
    'assign.assigned.text': "The responsible person gets the item's questions, permission requests and result report in their inbox. Change any of them below.",
    'assign.split.agent': 'Claude suggests this split among the people with agent access who are here.',
    'assign.split.agentReason': 'Claude suggests this split among the people with agent access who are here: "{reason}"',
    'assign.split.smurg': 'Suggested split: an even load across the people with agent access (sizes S / M / L).',
    'assign.suggestAgain': 'Suggest again',
    'assign.suggested': 'suggested',
    'assign.offline': 'offline',
    'assign.you': '{name} (you)',
    'assign.nobody': 'Nobody assigned',
    'assign.nobody.title': 'Nobody is assigned to this item: everyone watches it.',
    'assign.nobody.option': 'No one: everyone watches',
    'assign.title': 'Responsible: {name}',
    'assign.change': 'Responsible for item {number}: {name}. Change',
    'assign.change.nobody': 'Nobody is responsible for item {number}. Change',
    'assign.person.offline': '{name} (offline)',
    'assign.hint': '{role} · {items}',
    'assign.items': { one: '{count} item', other: '{count} items' },
    'assign.editorNote': '{name} reviews the report and votes. Commands are allowed by {names}.',
    'assign.failed': 'Could not change who is responsible: {reason}',

    // ---- allowed in this topic
    'rules.label': 'Allowed in this topic',
    'rules.none': 'Nothing yet: every command asks first.',
    'rules.add': 'Add a kind',
    'rules.remove': 'Stop allowing {rule}',
    'rules.tool': 'What to allow',
    'rules.tool.bash': 'A kind of command',
    'rules.tool.web': 'Reading a website',
    'rules.pattern.bash': 'Command',
    'rules.pattern.web': 'Website',
    'rules.hint.bash': 'Two or three words, then a space and a star, as in: pnpm test *',
    'rules.hint.web': 'The host name of the site, as in: docs.example.com',
    'rules.save': 'Allow',
    'rules.failed': 'Could not change what is allowed: {reason}',
    'rules.refused.form.bash': 'Write two or three plain words, then a space and a star.',
    'rules.refused.form.web': 'Write a host name such as docs.example.com (no address, no path).',
    'rules.refused.interpreter': 'This program runs whatever follows it, so it cannot be always allowed.',
    'rules.refused.fetches-code': 'This downloads and runs code, so it cannot be always allowed.',
    'rules.refused.one-word': 'One word allows too much. Name the subcommand as well.',

    // ---- work items
    'item.prefix': 'Item {number}: ',
    'item.after': 'after {items}',
    'item.attempt': 'attempt {attempt}',
    'item.session': 'Session',
    'item.report': 'Report',
    'item.retry': 'Try again',
    'item.continue': 'Continue',
    'item.start': 'Start this one',
    'item.startAgain': 'Start again',
    'item.resolve': 'Ask the agent to resolve',
    'item.startError': 'Could not start: {reason}',
    'item.failed': '{item}: {reason}',
    'size.s': 'Size: small',
    'size.m': 'Size: medium',
    'size.l': 'Size: large',
    'badge.ready': 'Ready to start',
    'badge.waits': 'Waits for {items}',
    'badge.waitsMerge': 'Waits for the host to merge {items}',
    'badge.queued': 'Waiting for a free agent: {inUse} of {max} in use, {people}',
    'badge.queued.people': { one: '{count} waits for a person', other: '{count} wait for a person' },
    'badge.running': 'Running',
    'badge.question': 'Waiting for an answer',
    'badge.permission': 'Waiting for permission',
    'badge.stalled.agent': 'Stopped without a report',
    'badge.stalled.restart': 'Paused: smurg was restarted',
    'badge.stalled.stopped': 'Stopped by a person, no report',
    'badge.stalled.error': 'Stopped on an error, no report',
    'badge.done': 'Done',
    'badge.report': 'Report to review',
    'badge.reportUnfinished': 'Report to review · {outcome}',
    'badge.reportInvalid': 'The report cannot be read',
    'badge.changesAsked': 'Changes asked by {name}',
    'badge.changedAfterReview': 'Changed after the review',
    'badge.reviewed': 'Reviewed',
    'badge.reviewedWaitsMerge': 'Reviewed · waits for the host to merge',
    'badge.merged': 'Reviewed · merged',
    'badge.conflict': 'Reviewed · merge conflict',
    'badge.mergeRejected': 'Reviewed · the host rejected the merge',
    'badge.failed': 'Failed',
    'badge.stopped': 'Session ended',
    'badge.planChanged': 'The plan changed: Start again',
    'badge.starterRemoved': 'The person who started it left: Start again',
    'badge.startFailed': 'Could not start',

    // ---- the plan's foot
    'foot.start': 'Start opens one agent session per item, each in its own worktree.',
    'foot.start.others': '{names} can start the plan.',
    'foot.noGit': 'This folder is not a git repository yet, so work items cannot start: they run in git worktrees.',
    'foot.startsByItself.one': 'Item {number} starts by itself when {items} is merged.',
    'foot.startsByItself.many': 'Item {number} starts by itself when {items} are merged.',
    'foot.startAll': { one: 'Start {count} item', other: 'Start {count} items' },
    'foot.startMore': { one: 'Start {count} more item', other: 'Start {count} more items' },
    'foot.watch': 'Watch running sessions side by side',
    'foot.nextMerge': 'Open the next one to merge',

    // ---- topic complete, archive, delete, rename
    'complete.title': 'Topic complete',
    'complete.body': 'Every result report has been reviewed.',
    'complete.body.unmerged': "Every result report has been reviewed. Not merged yet: {items} (in the host's inbox).",
    'archive.action': 'Archive topic',
    'archive.title': 'Archive "{topic}"?',
    'archive.lead': "Archiving ends this topic's sessions and removes their worktrees. The spec, the plan and the reports stay in the project, and every conversation stays readable. You can restore the topic later.",
    'archive.notMerged': 'Reviewed, but not merged into the main workspace yet:',
    'archive.unmerged.title': {
      one: '{count} work item has changes that were never merged',
      other: '{count} work items have changes that were never merged',
    },
    'archive.unmerged.body': 'Keep their worktrees so the changes can still be merged, or delete them with the changes.',
    'archive.unmerged.keep': 'Keep them',
    'archive.unmerged.delete': 'Delete them',
    'archive.done': 'Archived "{topic}".',
    'archive.failed': 'Could not archive the topic: {reason}',
    'restore.done': 'Restored "{topic}".',
    'restore.failed': 'Could not restore the topic: {reason}',
    'delete.action': 'Delete topic',
    'delete.title': 'Delete "{topic}"?',
    'delete.lead': "This removes the topic and its conversations from the host's computer for everyone. The files in {folder} stay in the project. This cannot be undone.",
    'delete.done': 'Deleted "{topic}".',
    'delete.failed': 'Could not delete the topic: {reason}',
    'rename.title': 'Rename topic',
    'rename.hint': 'The folder stays {folder}.',
    'rename.submit': 'Rename',
    'rename.failed': 'Could not rename the topic: {reason}',

    // ---- new topic
    'new.title': 'New topic',
    'new.name': 'Name',
    'new.name.hint': 'One feature or task. Shown in the session list.',
    'new.name.tooLong': 'The name is too long (at most {max} characters).',
    'new.name.invalid': 'The name must be one line without control characters.',
    'new.message': 'What do you want to build? (optional)',
    'new.message.hint': 'Sent to the agent as the first message of the discussion.',
    'new.folder': 'Folder for the spec and the plan (inside specs/)',
    'new.folder.hint': 'SPEC.md and PLAN.md will be files in {path}, versioned with the project.',
    'new.folder.hint.empty': 'Filled in from the name.',
    'new.folder.hint.latin': 'The folder name uses Latin letters; the topic keeps its own name.',
    'new.folder.invalid': 'Use lower-case letters, digits and hyphens, starting with a letter or a digit.',
    'new.info': "Starting a topic opens its discussion session: an agent on the host's computer, with the host's Claude account. It may read the code and write only this folder.",
    'new.settings.unconfirmed': "The host has not confirmed this folder's Claude Code project settings. The discussion will run without them and without the project's CLAUDE.md until {host} confirms.",
    'new.submit': 'Start discussion',
    'new.failed': 'The topic was not created: {reason}',
    'new.trustFailed': 'The Claude Code settings could not be confirmed: {reason}',
    'new.cannot.editor': "With the role {role} you cannot start a topic: starting one opens an agent session on the host's computer. You can take part in every topic: vote, comment, edit the spec and make suggestions.",
    'new.cannot.viewer': 'With the role {role} you cannot start a topic. When the host or a member with agent access starts one, it appears in the session list and you can read everything in it.',
    'trust.title': 'This folder has Claude Code project settings',
    'trust.loading': "Reading the folder's Claude Code project settings…",
    'trust.loadFailed': "The folder's Claude Code project settings could not be read: {reason} The discussion will run without them.",
    'trust.runs': 'Runs commands',
    'trust.permissions': 'Changes permissions',
    'trust.env': 'Sets environment',
    'trust.env.flagged': 'can send your Claude login to another server',
    'trust.other': 'Other settings',
    'trust.text': 'These commands run as you, on your computer, whenever an agent works here. Anyone who can edit files in this folder can change the scripts they call.',
    'trust.use': 'Use them',
    'trust.ignore': 'Run without them (agents will not read CLAUDE.md)',
    'trust.showFiles': 'Show the files',
    'trust.hideFiles': 'Hide the files',
    'trust.ack.credentials': 'I see that these settings can send my Claude login to another server.',
    'trust.ack.allows-tools': 'I see that these settings let agents run tools without asking.',

    // ---- the Start dialog
    'start.title': 'Start',
    'start.titleCount': { one: 'Start {count} item', other: 'Start {count} items' },
    'start.lead': 'What happens when you press Start.',
    'start.go': 'Start',
    'start.loading': 'Checking what a Start would do…',
    'start.loadFailed': 'Could not check the plan: {reason}',
    'start.failed': 'Nothing was started: {reason}',
    'start.changed': 'The spec or the plan changed while this was open. Nothing was started. Look at the list again before you start.',
    'start.done': { one: 'Started {count} item.', other: 'Started {count} items.' },
    'start.blocker': 'Cannot start:',
    'start.now': { one: '{count} item starts now: {items}.', other: '{count} items start now: {items}.' },
    'start.now.none': 'No item starts now.',
    'start.waits.one': '{item} starts by itself when {items} is merged, if the spec and the plan are still what you see now.',
    'start.waits.many': '{item} starts by itself when {items} are merged, if the spec and the plan are still what you see now.',
    'start.waitsMore': { one: '{count} more item waits for others.', other: '{count} more items wait for others.' },
    'start.already': 'Already started, not touched: {items}.',
    'start.responsible': 'Responsible: {who}.',
    'start.offline.one': '{names} is offline right now: their items start and wait for them.',
    'start.offline.many': '{names} are offline right now: their items start and wait for them.',
    'start.youDecide': { one: 'You will decide the questions of {count} session.', other: 'You will decide the questions of these {count} sessions.' },
    'start.commit': "smurg commits SPEC.md and PLAN.md to the branch {branch} of the host's folder, as {name}.",
    'start.commit.you': "smurg commits SPEC.md and PLAN.md to the branch {branch} of the host's folder, as you.",
    'start.commit.clean': 'SPEC.md and PLAN.md are already committed on the branch {branch}: nothing new is committed.',
    'start.commit.also': 'Also in the folder and NOT committed: {files}.',
    'start.handEdits': 'Edited by hand since the last Start: {who}.',
    'start.showChanges': 'Show the changes',
    'start.hideChanges': 'Hide the changes',
    'start.invisible.one': '{files} contains characters you cannot see. Look at the changes before you start.',
    'start.invisible.many': '{files} contain characters you cannot see. Look at the changes before you start.',
    'start.stale': 'The spec changed after this plan was written.',
    'start.updateFirst': 'Update plan first',
    'start.openQuestion': 'A question is open in the discussion.',
    'start.editingNow.one': '{names} is editing the spec or the plan right now.',
    'start.editingNow.many': '{names} are editing the spec or the plan right now.',
    'start.specOpenQuestions': { one: 'The spec lists {count} open question.', other: 'The spec lists {count} open questions.' },
    'start.settings.used': "The folder's Claude Code project settings are confirmed: agents read CLAUDE.md.",
    'start.settings.ignored': "The host has not confirmed this folder's Claude Code project settings: agents will not read CLAUDE.md.",
    'start.shared': 'Each item gets a fresh checkout. Shared into every checkout: {dirs}.',
    'start.shared.none': 'Each item gets a fresh checkout. Nothing is shared into it, so agents install what they need first.',
    'start.sharedSetting': 'Shared directories',
    'start.rules.note': 'Everything else asks first.',
    'handEdit.entry': '{name} ({file}, {time})',
    'handEdit.outside': 'a program outside smurg',
    'changes.title': 'Changes of the spec and the plan',
    'changes.titleOf': 'Changes of the spec and the plan: {topic}',
    'changes.lead': 'What changed in SPEC.md and PLAN.md since the last Start that someone confirmed.',
    'changes.none': 'Nothing changed in SPEC.md or PLAN.md.',
    'changes.failed': 'The changes could not be loaded: {reason}',
    'changes.truncated': 'This diff is too large to show completely. Open the file to read the rest.',
    'changes.diffLabel': 'Changes of {file}',

    // ---- result report
    'report.loadFailed': 'The report could not be loaded: {reason}',
    'report.section.done': 'What was done',
    'report.section.why': 'Why it was done this way',
    'report.section.verified': 'How it was verified',
    'report.section.watchOut': 'What to watch out for',
    'report.section.changes': 'Changes',
    'report.section.followUps': 'Follow-ups the agent suggests',
    'report.section.questions': 'Asked about this result',
    'report.checks': '{passed} passed · {notVerified} not verified',
    'report.check.passed': 'Passed:',
    'report.check.notVerified': 'Not verified:',
    'report.verified.none': 'The report lists no checks.',
    'report.written': 'Written by Claude, {time}',
    'report.writtenVersion': 'Written by Claude, {time} (version {version})',
    'report.openSession': 'Open the session',
    'report.agent': 'Claude',
    'report.invalid': 'smurg cannot read this report.',
    'report.invalidLine': 'smurg cannot read this report (line {line}).',
    'report.changesAsked': '{name} asked for changes at {time}. Claude writes a new version of this report when it is done.',
    'report.changes.counts': '{files} · +{additions} −{deletions}',
    'report.changes.files': { one: '{count} file', other: '{count} files' },
    'report.changes.none': 'This item changed no files.',
    'report.noChanges.host-only-paths': 'The changes are not shown: they touch files only the host may change. The host looks at the worktree directly.',
    'report.noChanges.spec-files': 'The changes are not shown: they touch the spec or the plan, which a work item must not change.',
    'report.noChanges.conflict-markers': 'The changes are not shown: files still contain merge conflict markers.',
    'report.question.cut': 'Shortened here. The whole text is in the session.',
    'report.question.waiting': 'Claude has not answered yet.',
    'report.state.reviewed': 'Reviewed by {name}, {time}',
    'report.state.waitsYou': 'Waiting for your review',
    'report.state.waitsFor': 'Waiting for {name}',
    'report.state.waits': 'Waiting for a review',
    'report.state.changed': 'Changed after the review · {waits}',
    'report.closed': 'This item is merged and its session has ended. Ask in the discussion.',
    'followUp.label': 'Ask about this result, or tell Claude what to change',
    'followUp.label.suggestion': 'Suggest a question or a change',
    'followUp.hint': 'Goes to the session of this item. The answer appears here.',
    'followUp.send': 'Send',
    'review.action': "I've reviewed this",
    'review.instead': 'Review instead of {name}',
    'review.lead': 'Press it when you have read the report and understand the change. It leaves your inbox, and the plan counts the item as reviewed.',
    'review.again': 'Claude changed this report after it was reviewed. Read it again, then confirm.',
    'review.others.one': '{name} is responsible for this item and reviews this report. Everyone can read it and ask follow-ups.',
    'review.others.many': 'Nobody is assigned to this item: anyone but a viewer can review it. Everyone can read it and ask follow-ups.',
    'review.unfinished': 'This report says the work is {outcome}. Mark unfinished work as reviewed?',
    'review.unfinished.confirm': 'Mark as reviewed',
    'review.done': 'Marked as reviewed.',
    'review.changed': 'Claude wrote a newer version of this report. Read it, then confirm again.',
    'review.failed': 'Not marked as reviewed: {reason}',
    'review.invalid': 'This report cannot be reviewed until the agent fixes it.',
    'review.by': 'Reviewed by {name} at {time}.',
    'review.insteadOf': '(instead of {name})',
    'review.ready': "The change is in the host's inbox, ready to merge.",
    'review.ready.host': 'The change is ready for you to merge.',
    'review.merged': 'Merged into the main workspace.',
    'review.mergedAt': 'Merged into the main workspace at {time}.',
    'review.noChanges': 'There is nothing to merge.',
    'review.conflict': 'The merge stopped on a conflict.',
    'review.rejected': 'The host rejected the merge.',
    'review.rejectedReason': 'The host rejected the merge: {reason}',
    'review.merge': 'Merge…',
    'review.request': 'Request merge',
    'review.requested': 'Merge requested. It waits for the host.',
    'review.requestFailed': 'Could not request the merge: {reason}',
  },
  zhTW,
);
