// Traditional Chinese (Taiwan) of the topics feature: the same keys as strings.ts. Latin terms the glossary keeps
// (agent, session, spec, worktree, Claude Code) have a space on both sides; role names stand in 「」 inside a sentence.
export const zhTW = {
  sep: ' · ',
  loading: '載入中…',
  'people.host': '主人',
  'archived.note': '這個主題已封存，還原後才能繼續。',

  'view.read': '閱讀',
  'view.edit': '編輯',
  'view.edit.viewer': '「旁觀」只能閱讀；編輯需要「可編輯」以上的角色。',
  'view.items': '項目',
  'view.file': '檔案',
  'menu.openInCode': '在手寫 code 模式開啟這個檔案',
  'menu.rename': '重新命名主題',
  'menu.restore': '還原主題',

  'ask.close': '關閉',
  'ask.failed': '沒有送出：{reason}',
  'ask.offline': '你目前離線，輸入的內容會留在這裡。',
  'ask.removeQuote': '移除引用的章節',
  'ask.tooLong': '文字太長（最多 {max} 個字元）。',
  'revise.open': '請 agent 修改',
  'revise.section': '請 agent 修改「{heading}」',
  'revise.label': '要請 agent 改什麼？',
  'revise.placeholder': '要請 agent 改什麼？',
  'revise.hint': '會送到這個主題的討論 session。agent 會修改這個檔案，變更會顯示在這裡。',
  'revise.hint.suggestion': '會以建議的形式送給 {names}：你的角色不能直接傳訊息給 agent。',
  'revise.send': '請 agent 修改',
  'revise.send.suggestion': '送出建議',
  'revise.quote': '關於引用的文字',
  'revise.quote.section': '關於「{heading}」這一節',
  'sent.discussion': '已送到討論。',
  'sent.item': '已送到這個項目的 session。',
  'sent.suggestion': '已以建議的形式送給 {names}。',

  'discussion.open': '開啟討論',
  'discussion.restart': '重新開始討論',
  'discussion.closed': '這個主題的討論已結束。',
  'discussion.idle': '討論：Claude 待命中。',
  'discussion.working': '討論：Claude 工作中。',
  'discussion.workingFor': '討論：Claude 工作中 · {time}',
  'discussion.compacting': '討論：Claude 正在縮短對話。',
  'discussion.question': '討論：Claude 提出了選擇題。',
  'discussion.permission': '討論：Claude 請求許可。',
  'discussion.failed': '討論：session 失敗了。',
  'restart.title': '要重新開始討論嗎？',
  'restart.lead': '這個主題會有一個新的討論 session。它會重新讀 spec 和計畫，但不知道之前說過什麼。之前的討論仍然可以閱讀。',
  'restart.lead.lost': '這個主題的討論 session 已經結束。新的 session 會讀 spec 和計畫，但不知道之前說過什麼。之前的討論仍然可以閱讀。',
  'restart.failed': '無法重新開始討論：{reason}',

  'spec.view': 'spec 的檢視方式',
  'spec.read.label': 'spec 內容',
  'spec.empty.title': '還沒有 spec',
  'spec.empty.body': '先和 agent 討論，它會寫出第一版。',
  'spec.request': '請 agent 現在寫 spec',
  'spec.request.failed': '無法請 agent 寫 spec：{reason}',
  'spec.blank': '這個檔案是空的。',
  'spec.unreadable': '無法開啟這個檔案。切換到「編輯」可以看到原因。',
  'spec.changed': 'Claude 在 {time} 修改',
  'spec.changedAsked': 'Claude 在 {time} 修改，{name} 提出',
  'spec.showInDiscussion': '在討論裡顯示',
  'spec.generate.failed': '無法請 agent 寫計畫：{reason}',
  'spec.odd.editing.one': '{names} 正在編輯 spec。',
  'spec.odd.editing.many': '{names} 都在編輯 spec。',
  'spec.odd.openQuestions': 'spec 裡列了 {count} 個未決事項。',
  'spec.odd.question': '討論裡還有一題選擇題沒回答。',
  'spec.confirm.title': '現在就產生計畫嗎？',
  'spec.confirm.titleUpdate': '現在就更新計畫嗎？',
  'spec.confirm.go': '產生計畫',
  'spec.confirm.goUpdate': '更新計畫',

  'plan.view': '計畫的檢視方式',
  'plan.generate': '產生計畫',
  'plan.update': '更新計畫',
  'plan.generating': 'Claude 正在寫計畫…',
  'plan.generating.update': 'Claude 正在更新計畫…',
  'plan.empty.title': '還沒有計畫',
  'plan.empty.body': '從 spec 產生計畫。',
  'plan.empty.noSpec': '計畫是從 spec 產生的，而現在還沒有 spec。',
  'plan.empty.openSpec': '開啟 spec',
  'plan.loadFailed': '無法載入計畫。',
  'plan.reload': '重新載入',
  'plan.items.label': '工作項目',
  'plan.invalid.title': 'smurg 無法從 PLAN.md 讀出工作項目。',
  'plan.invalid.titleLine': 'smurg 無法從 PLAN.md 讀出工作項目（第 {line} 行）。',
  'plan.invalid.last': '下面是 smurg 最後一次讀得懂的計畫。檔案修正之前，任何項目都不能開始。',
  'plan.invalid.openFile': '開啟檔案',
  'plan.invalid.fix': '請 agent 修正',
  'plan.invalid.fixText': 'PLAN.md 無法讀成工作項目，請修正後再檢查一次。',
  'plan.stale': 'spec 在這份計畫寫好之後有變動。',
  'plan.paused.title': '主人電腦上的 smurg 重新啟動過',
  'plan.paused.body': '有人按下繼續之前，這份計畫不會執行任何項目。',
  'plan.paused.body.others': '按下繼續之前，這份計畫不會執行任何項目。{names} 可以按下繼續。',
  'plan.paused.continue': '全部繼續',
  'plan.paused.failed': '無法繼續：{reason}',
  'plan.removed.title': '已不在計畫裡',
  'plan.removed.body': '這些項目開始之後又從 PLAN.md 移除了，不計入這個主題的進度。',
  'summary.items': '{count} 個工作項目',
  'summary.canStart': '{count} 個現在可以開始',
  'summary.waitsOthers': '{count} 個要等其他項目',
  'summary.reviewed': '{reviewed} / {total} 已看過',
  'summary.toReview': '{count} 份報告待看',
  'summary.waitPerson': '{count} 個等人處理',
  'summary.running': '{count} 個執行中',
  'summary.notStarted': '{count} 個尚未開始',
  'summary.merged': '{count} 個已合併',
  'waiting.line': '在等：{who}',
  'waiting.person': '{name} {what}（{time}）',
  'waiting.questions': '{count} 題選擇題',
  'waiting.permissions': '{count} 個權限請求',
  'waiting.reports': '{count} 份報告',
  'split.load': '{name} {count}',

  'assign.heading': '誰負責',
  'assign.mode.assigned': '指派負責人',
  'assign.mode.everyone': '不指派：大家一起看',
  'assign.everyone.text': '不指派負責人。權限請求會送給 {names}。除了「旁觀」，任何人都可以看報告。選擇題由按下「開始」的人決定。',
  'assign.assigned.text': '負責人會在收件夾收到該項目的選擇題、權限請求和結果報告。下面每一項都可以更改。',
  'assign.split.agent': 'Claude 為現在在場、可使用 agent 的人建議了這樣的分工。',
  'assign.split.agentReason': 'Claude 為現在在場、可使用 agent 的人建議了這樣的分工：「{reason}」',
  'assign.split.smurg': '建議的分工：讓可使用 agent 的人平均分擔（依大小 S / M / L）。',
  'assign.suggestAgain': '重新建議',
  'assign.suggested': '建議',
  'assign.offline': '離線',
  'assign.you': '{name}（你）',
  'assign.nobody': '不指派',
  'assign.nobody.title': '這個項目沒有指派負責人：大家一起看。',
  'assign.nobody.option': '不指派：大家一起看',
  'assign.title': '負責人：{name}',
  'assign.change': '項目 {number} 的負責人：{name}。變更',
  'assign.change.nobody': '項目 {number} 沒有負責人。變更',
  'assign.person.offline': '{name}（離線）',
  'assign.hint': '{role} · {items}',
  'assign.items': '{count} 個項目',
  'assign.editorNote': '{name} 負責看結果報告和投票；指令由 {names} 允許。',
  'assign.failed': '無法變更負責人：{reason}',

  'rules.label': '這個主題一律允許',
  'rules.none': '目前沒有：每個指令都會先問。',
  'rules.add': '新增一類',
  'rules.remove': '不再允許 {rule}',
  'rules.tool': '要允許什麼',
  'rules.tool.bash': '一類指令',
  'rules.tool.web': '讀取某個網站',
  'rules.pattern.bash': '指令',
  'rules.pattern.web': '網站',
  'rules.hint.bash': '兩到三個字，接著一個空格和星號，例如：pnpm test *',
  'rules.hint.web': '網站的主機名稱，例如：docs.example.com',
  'rules.save': '允許',
  'rules.failed': '無法變更允許的項目：{reason}',
  'rules.refused.form.bash': '請寫兩到三個單純的字，接著一個空格和星號。',
  'rules.refused.form.web': '請寫主機名稱，例如 docs.example.com（不要寫位址或路徑）。',
  'rules.refused.interpreter': '這個程式會執行接在後面的任何東西，所以不能一律允許。',
  'rules.refused.fetches-code': '這會下載並執行程式碼，所以不能一律允許。',
  'rules.refused.one-word': '只寫一個字允許的範圍太大，請把子指令也寫出來。',

  'item.prefix': '項目 {number}：',
  'item.after': '在 {items} 之後',
  'item.attempt': '第 {attempt} 次嘗試',
  'item.session': 'session',
  'item.report': '報告',
  'item.retry': '再試一次',
  'item.continue': '繼續',
  'item.start': '只開始這個',
  'item.startAgain': '重新開始',
  'item.resolve': '請 agent 解決衝突',
  'item.startError': '無法開始：{reason}',
  'item.failed': '{item}：{reason}',
  'size.s': '大小：小',
  'size.m': '大小：中',
  'size.l': '大小：大',
  'badge.ready': '可以開始',
  'badge.waits': '等待 {items}',
  'badge.waitsMerge': '等主人合併 {items}',
  'badge.queued': '等待空閒的 agent：{max} 個裡有 {inUse} 個使用中，{people}',
  'badge.queued.people': '{count} 個在等人處理',
  'badge.running': '執行中',
  'badge.question': '等待回答',
  'badge.permission': '等待許可',
  'badge.stalled.agent': '沒寫報告就停下了',
  'badge.stalled.restart': '已暫停：smurg 重新啟動過',
  'badge.stalled.stopped': '被人停止，沒有報告',
  'badge.stalled.error': '因錯誤停止，沒有報告',
  'badge.done': '完成',
  'badge.report': '報告待看',
  'badge.reportUnfinished': '報告待看 · {outcome}',
  'badge.reportInvalid': '無法讀取報告',
  'badge.changesAsked': '{name} 要求修改',
  'badge.changedAfterReview': '看過之後又有變動',
  'badge.reviewed': '已看過',
  'badge.reviewedWaitsMerge': '已看過 · 等主人合併',
  'badge.merged': '已看過 · 已合併',
  'badge.conflict': '已看過 · 合併衝突',
  'badge.mergeRejected': '已看過 · 主人拒絕合併',
  'badge.failed': '失敗',
  'badge.stopped': 'session 已結束',
  'badge.planChanged': '計畫有變動：請重新開始',
  'badge.starterRemoved': '按下開始的人已離開：請重新開始',
  'badge.startFailed': '無法開始',

  'foot.start': '「開始」會為每個項目開一個 agent session，各自在自己的 worktree。',
  'foot.start.others': '{names} 可以開始執行計畫。',
  'foot.noGit': '這個資料夾還不是 git 儲存庫，所以工作項目無法開始：它們要在 git worktree 裡執行。',
  'foot.startsByItself.one': '項目 {number} 會在 {items} 合併後自動開始。',
  'foot.startsByItself.many': '項目 {number} 會在 {items} 都合併後自動開始。',
  'foot.startAll': '開始 {count} 個項目',
  'foot.startMore': '再開始 {count} 個項目',
  'foot.watch': '並排觀看執行中的 session',
  'foot.nextMerge': '開啟下一個要合併的項目',

  'complete.title': '主題完成',
  'complete.body': '每一份結果報告都有人看過了。',
  'complete.body.unmerged': '每一份結果報告都有人看過了。還沒合併：{items}（在主人的收件夾）。',
  'archive.action': '封存主題',
  'archive.title': '要封存「{topic}」嗎？',
  'archive.lead': '封存會結束這個主題的 session 並移除它們的 worktree。spec、計畫和報告會留在專案裡，每一段對話也都還能閱讀。之後可以還原主題。',
  'archive.notMerged': '已看過，但還沒合併到主工作區：',
  'archive.unmerged.title': '有 {count} 個工作項目的變更從未合併',
  'archive.unmerged.body': '保留它們的 worktree，之後還能合併；或者連同變更一起刪除。',
  'archive.unmerged.keep': '保留',
  'archive.unmerged.delete': '刪除',
  'archive.done': '已封存「{topic}」。',
  'archive.failed': '無法封存主題：{reason}',
  'restore.done': '已還原「{topic}」。',
  'restore.failed': '無法還原主題：{reason}',
  'delete.action': '刪除主題',
  'delete.title': '要刪除「{topic}」嗎？',
  'delete.lead': '這會從主人的電腦移除這個主題和它的對話，所有人都看不到了。{folder} 裡的檔案會留在專案裡。這個動作無法復原。',
  'delete.done': '已刪除「{topic}」。',
  'delete.failed': '無法刪除主題：{reason}',
  'rename.title': '重新命名主題',
  'rename.hint': '資料夾維持 {folder}。',
  'rename.submit': '重新命名',
  'rename.failed': '無法重新命名主題：{reason}',

  'new.title': '新增主題',
  'new.name': '名稱',
  'new.name.hint': '一個功能或一件工作，會顯示在 session 清單。',
  'new.name.tooLong': '名稱太長（最多 {max} 個字元）。',
  'new.name.invalid': '名稱必須是一行，而且不能有控制字元。',
  'new.message': '想做什麼？（選填）',
  'new.message.hint': '會當成討論的第一則訊息送給 agent。',
  'new.folder': 'spec 與計畫的資料夾（在 specs/ 底下）',
  'new.folder.hint': 'SPEC.md 和 PLAN.md 會是 {path} 裡的檔案，跟著專案一起記錄版本。',
  'new.folder.hint.empty': '會依名稱自動填入。',
  'new.folder.hint.latin': '資料夾名稱使用英文字母；主題會保留自己的名稱。',
  'new.folder.invalid': '請使用小寫英文字母、數字和連字號，並以字母或數字開頭。',
  'new.info': '開始主題會開啟它的討論 session：在主人電腦上執行的 agent，使用主人的 Claude 帳號。它只能讀程式碼，只能寫這個資料夾。',
  'new.settings.unconfirmed': '主人還沒確認這個資料夾的 Claude Code 專案設定。在 {host} 確認之前，討論不會載入它們，也不會載入專案的 CLAUDE.md。',
  'new.submit': '開始討論',
  'new.failed': '沒有建立主題：{reason}',
  'new.trustFailed': '無法確認 Claude Code 設定：{reason}',
  'new.cannot.editor': '你的角色是「{role}」，不能開始主題：開始主題會在主人的電腦上開一個 agent session。你可以參與每個主題：投票、留言、編輯 spec 和提出建議。',
  'new.cannot.viewer': '你的角色是「{role}」，不能開始主題。主人或「可使用 agent」的成員開始主題後，它會出現在 session 清單，你可以閱讀裡面的所有內容。',
  'new.settings.reading': '正在讀取這個資料夾的 Claude Code 專案設定…',
  'new.settings.unread': '無法讀取這個資料夾的 Claude Code 專案設定：{reason} 討論不會載入它們。',

  'start.title': '開始',
  'start.titleCount': '開始 {count} 個項目',
  'start.lead': '按下「開始」之後會發生的事。',
  'start.go': '開始',
  'start.loading': '正在檢查按下「開始」會發生什麼事…',
  'start.loadFailed': '無法檢查計畫：{reason}',
  'start.failed': '沒有開始任何項目：{reason}',
  'start.changed': '這個視窗開著的時候，spec 或計畫有了變動。沒有開始任何項目。開始之前請再看一次清單。',
  'start.done': '已開始 {count} 個項目。',
  'start.blocker': '無法開始：',
  'start.now': '{count} 個項目現在開始：{items}。',
  'start.now.none': '沒有項目會現在開始。',
  'start.waits.one': '{item} 會在 {items} 合併後自動開始，前提是 spec 和計畫還是你現在看到的內容。',
  'start.waits.many': '{item} 會在 {items} 都合併後自動開始，前提是 spec 和計畫還是你現在看到的內容。',
  'start.waitsMore': '另外還有 {count} 個項目要等其他項目。',
  'start.already': '已經開始、不會更動的項目：{items}。',
  'start.responsible': '負責人：{who}。',
  'start.offline.one': '{names} 目前離線：他負責的項目會開始，然後等他。',
  'start.offline.many': '{names} 目前離線：他們負責的項目會開始，然後等他們。',
  'start.youDecide': '這 {count} 個 session 的選擇題會由你決定。',
  'start.commit': 'smurg 會以 {name} 的身分，把 SPEC.md 和 PLAN.md 提交到主人資料夾的 {branch} 分支。',
  'start.commit.you': 'smurg 會以你的身分，把 SPEC.md 和 PLAN.md 提交到主人資料夾的 {branch} 分支。',
  'start.commit.clean': 'SPEC.md 和 PLAN.md 已經提交在 {branch} 分支：不會有新的提交。',
  'start.commit.also': '資料夾裡還有、但不會提交的檔案：{files}。',
  'start.handEdits': '上次開始之後手動編輯過的人：{who}。',
  'start.showChanges': '顯示變更',
  'start.hideChanges': '隱藏變更',
  'start.invisible.one': '{files} 裡有你看不到的字元。開始之前請先看變更。',
  'start.invisible.many': '{files} 裡都有你看不到的字元。開始之前請先看變更。',
  'start.stale': 'spec 在這份計畫寫好之後有變動。',
  'start.updateFirst': '先更新計畫',
  'start.openQuestion': '討論裡還有一題選擇題沒回答。',
  'start.editingNow.one': '{names} 正在編輯 spec 或計畫。',
  'start.editingNow.many': '{names} 都在編輯 spec 或計畫。',
  'start.specOpenQuestions': 'spec 裡列了 {count} 個未決事項。',
  'start.settings.used': '這個資料夾的 Claude Code 專案設定已確認：agent 會讀 CLAUDE.md。',
  'start.settings.ignored': '主人還沒確認這個資料夾的 Claude Code 專案設定：agent 不會讀 CLAUDE.md。',
  'start.shared': '每個項目都有一份全新的 checkout。共用到每份 checkout 的目錄：{dirs}。',
  'start.shared.none': '每個項目都有一份全新的 checkout，沒有共用任何目錄，所以 agent 會先安裝需要的東西。',
  'start.sharedSetting': '共用目錄',
  'start.rules.note': '其他都會先問。',
  'handEdit.entry': '{name}（{file}，{time}）',
  'handEdit.outside': 'smurg 以外的程式',
  'changes.title': 'spec 和計畫的變更',
  'changes.titleOf': 'spec 和計畫的變更：{topic}',
  'changes.lead': '上次有人確認開始之後，SPEC.md 和 PLAN.md 的變動。',
  'changes.none': 'SPEC.md 和 PLAN.md 都沒有變動。',
  'changes.failed': '無法載入變更：{reason}',
  'changes.truncated': '這份差異太大，無法完整顯示。請開啟檔案閱讀其餘部分。',
  'changes.diffLabel': '{file} 的變更',

  'report.loadFailed': '無法載入報告：{reason}',
  'report.section.done': '做了什麼',
  'report.section.why': '為什麼這樣做',
  'report.section.verified': '怎麼驗證的',
  'report.section.watchOut': '要注意什麼',
  'report.section.changes': '變更',
  'report.section.followUps': 'agent 建議的後續工作',
  'report.section.questions': '關於這個結果的追問',
  'report.checks': '{passed} 項通過 · {notVerified} 項未驗證',
  'report.check.passed': '通過：',
  'report.check.notVerified': '未驗證：',
  'report.verified.none': '報告裡沒有列出任何檢查。',
  'report.written': 'Claude 撰寫，{time}',
  'report.writtenVersion': 'Claude 撰寫，{time}（第 {version} 版）',
  'report.openSession': '開啟 session',
  'report.agent': 'Claude',
  'report.invalid': 'smurg 無法讀取這份報告。',
  'report.invalidLine': 'smurg 無法讀取這份報告（第 {line} 行）。',
  'report.changesAsked': '{name} 在 {time} 要求修改。Claude 完成後會寫出這份報告的新版本。',
  'report.changes.counts': '{files} · +{additions} −{deletions}',
  'report.changes.files': '{count} 個檔案',
  'report.changes.none': '這個項目沒有變更任何檔案。',
  'report.noChanges.host-only-paths': '變更沒有顯示：它們改到了只有主人能改的檔案。主人會直接查看 worktree。',
  'report.noChanges.spec-files': '變更沒有顯示：它們改到了 spec 或計畫，而工作項目不能改這兩個檔案。',
  'report.noChanges.conflict-markers': '變更沒有顯示：檔案裡還留著合併衝突的標記。',
  'report.question.cut': '這裡只顯示一部分，完整內容在 session 裡。',
  'report.question.waiting': 'Claude 還沒回答。',
  'report.state.reviewed': '{name} 已看過，{time}',
  'report.state.waitsYou': '等你看',
  'report.state.waitsFor': '等 {name} 看',
  'report.state.waits': '等人看',
  'report.state.changed': '看過之後又有變動 · {waits}',
  'report.closed': '這個項目已經合併，它的 session 也結束了。請到討論裡提問。',
  'followUp.label': '追問這個結果，或告訴 Claude 要改什麼',
  'followUp.label.suggestion': '建議一個追問或修改',
  'followUp.hint': '會送到這個項目的 session，回答會顯示在這裡。',
  'followUp.send': '送出',
  'review.action': '我已看過',
  'review.instead': '代替 {name} 看',
  'review.lead': '看完報告、理解這次變更之後再按。它會離開你的收件夾，計畫也會把這個項目算成已看過。',
  'review.again': 'Claude 在報告被看過之後又修改了它。請再讀一次，然後確認。',
  'review.others.one': '{name} 是這個項目的負責人，由他看這份報告。每個人都可以閱讀和追問。',
  'review.others.many': '這個項目沒有指派負責人：除了「旁觀」，任何人都可以看。每個人都可以閱讀和追問。',
  'review.unfinished': '這份報告說工作的狀態是「{outcome}」。要把還沒完成的工作標成已看過嗎？',
  'review.unfinished.confirm': '標成已看過',
  'review.done': '已標成看過。',
  'review.changed': 'Claude 寫了這份報告的新版本。請先閱讀，再確認一次。',
  'review.failed': '沒有標成已看過：{reason}',
  'review.invalid': '在 agent 修正之前，這份報告不能標成已看過。',
  'review.by': '{name} 在 {time} 看過了。',
  'review.insteadOf': '（代替 {name}）',
  'review.ready': '這份變更已經在主人的收件夾，可以合併。',
  'review.ready.host': '這份變更可以由你合併了。',
  'review.merged': '已合併到主工作區。',
  'review.mergedAt': '已在 {time} 合併到主工作區。',
  'review.noChanges': '沒有需要合併的內容。',
  'review.conflict': '合併因為衝突而停下了。',
  'review.rejected': '主人拒絕了合併。',
  'review.rejectedReason': '主人拒絕了合併：{reason}',
  'review.merge': '合併…',
  'review.request': '請求合併',
  'review.requested': '已請求合併，等主人處理。',
  'review.requestFailed': '無法請求合併：{reason}',
} as const;
