// Traditional Chinese of the `activity` namespace: exactly the keys of strings.ts (the English table defines them).
// Only strings.ts imports this file.
export const zhTW = {
  'feed.label': '活動動態',
  'feed.empty': '還沒有任何活動',
  'feed.emptyHint': 'agent 和組員修改、新增、刪除或上傳檔案時，會即時出現在這裡。',
  'feed.emptyFiltered': '沒有符合篩選條件的活動',
  'feed.loading': '正在載入活動…',
  'feed.error': '無法載入活動：{message}',
  'feed.retry': '重試',
  'feed.older': '載入更早的活動',
  'feed.openFile': '開啟 {path}',
  'feed.deletedFile': '{path}（已刪除）',
  'feed.inWorktree': '{path}（worktree：{name}）',
  'feed.showConflicts': '查看衝突',
  'feed.showSession': '顯示這個 session',
  'feed.showSessionOf': '在編輯器旁邊顯示 {agent} 的 session',
  'filter.label': '篩選活動',
  'filter.all': '全部活動',
  'filter.agents': 'agent 的修改',
  'filter.people': '組員的操作',
  'filter.problems': '衝突與被擋下的修改',
  'kind.agent.edit': 'agent 修改',
  'kind.human.edit': '編輯',
  'kind.file.create': '新增',
  'kind.file.delete': '刪除',
  'kind.file.rename': '重新命名',
  'kind.file.upload': '上傳',
  'kind.external.change': '外部變更',
  'kind.conflict': '衝突',
  'kind.lock.denied': '被擋下',
  'kind.merge': '合併',
  'actor.system': '外部程式',
  'via.shell': '透過指令',
  'via.shellHint': '這個修改來自 {agent} 執行的 shell 指令（Bash），由主人電腦依指令執行的時間判斷是它改的。',
  'notify.label': '給你的通知',
  'notify.title': '{from} 通知你',
  'notify.dismiss': '知道了',
  'notify.open': '開啟檔案',
  'conflicts.label': '衝突面板',
  'conflicts.empty': '沒有待處理的衝突',
  'conflicts.emptyHint':
    '有人正在編輯的檔案被 agent 或其他程式（例如 Bash、格式化工具、git）修改時，重疊的部分會保留編輯中的內容，另一方的版本會出現在這裡。',
  'conflicts.loading': '正在載入衝突…',
  'conflicts.error': '無法載入衝突：{message}',
  'conflicts.retry': '重試',
  'conflicts.resolved': '已處理的衝突（{count}）',
  'conflict.summary': '{source}在 {time} 修改了這個檔案，和{humans}正在編輯的內容重疊。',
  'conflict.summaryNobody': '{source}在 {time} 修改了這個檔案，和正在編輯的內容重疊。',
  'conflict.kept': '檔案裡保留的是編輯中的內容；{source}的版本列在右側。',
  'conflict.hunk': '第 {line} 行起',
  'conflict.human': '編輯中的內容（目前保留）',
  'conflict.agent': '{source}的版本',
  'conflict.lineNumber': '行號',
  'conflict.noLines': '（沒有內容）',
  'conflict.base': '修改前的內容',
  'conflict.truncated': '這段內容太長，只顯示前 64 KB。',
  'conflict.omitted': '另有 {count} 處重疊沒有列出；「查看完整版本」可以看到另一方寫入的全部內容。',
  'conflict.status.open': '待處理',
  'conflict.status.dismissed': '已保留編輯中的內容',
  'conflict.status.applied': '已套用另一方的版本',
  'conflict.openFile': '開啟檔案',
  'conflict.dismiss': '保留編輯中的內容',
  'conflict.dismissHint': '關閉這個衝突，檔案維持目前的內容。',
  'conflict.apply': '套用這個版本…',
  'conflict.applyHint': '用{source}寫入的完整版本取代整個檔案。',
  'conflict.viewFull': '查看完整版本',
  'conflict.applyTitle': '要套用{source}的版本嗎？',
  'conflict.applyText':
    '整個檔案會換成{source}寫入的完整版本（{size}），檔案裡目前編輯中的內容會被取代。所有人都會看到這個變更，並記錄在操作紀錄中。',
  'conflict.applyConfirm': '套用',
  'conflict.cancel': '取消',
  'conflict.fullTitle': '{source}寫入的完整版本',
  'conflict.fullDescription': '{path}（{size}）',
  'conflict.fullLoading': '正在載入…',
  'conflict.fullError': '無法載入完整版本：{message}',
  'conflict.fullTruncated': '內容太長，只顯示前 {shown} 個字元。',
  'conflict.close': '關閉',
  'conflict.failed': '無法處理衝突：{message}',
  'conflict.agentLocked': '{agent} 正在修改這個檔案，請稍後再試。',
  'conflict.hostOnly': '這個檔案只有主人可以修改，衝突也只有主人可以處理。',
  'actor.systemInText': '外部程式',
} as const;
