import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the activity feature (activity feed, conflict panel). English defines the keys; strings.zh-TW.ts holds
// the same keys in Traditional Chinese. The sentence of a feed entry and a daemon-written notification are NOT here:
// they are wire messages (@smurg/protocol/i18n), rendered in the viewer's language.
export const t = defineStrings(
  'activity',
  {
    'feed.label': 'Activity feed',
    'feed.empty': 'No activity yet',
    'feed.emptyHint': 'Changes, new files, deletions and uploads by agents and teammates appear here as they happen.',
    'feed.emptyFiltered': 'No activity matches the filter',
    'feed.loading': 'Loading activity…',
    'feed.error': 'Could not load the activity: {message}',
    'feed.retry': 'Retry',
    'feed.older': 'Load earlier activity',
    'feed.openFile': 'Open {path}',
    'feed.deletedFile': '{path} (deleted)',
    'feed.inWorktree': '{path} (worktree: {name})',
    'feed.showConflicts': 'View conflicts',
    'feed.showSession': 'Show the session',
    'feed.showSessionOf': 'Show the session of {agent} beside the editor',
    'filter.label': 'Filter activity',
    'filter.all': 'All activity',
    'filter.agents': 'Changes by agents',
    'filter.people': 'Actions by teammates',
    'filter.problems': 'Conflicts and blocked changes',
    'kind.agent.edit': 'Agent edit',
    'kind.human.edit': 'Edit',
    'kind.file.create': 'Created',
    'kind.file.delete': 'Deleted',
    'kind.file.rename': 'Renamed',
    'kind.file.upload': 'Uploaded',
    'kind.external.change': 'Outside change',
    'kind.conflict': 'Conflict',
    'kind.lock.denied': 'Blocked',
    'kind.merge': 'Merge',
    'actor.system': 'Outside program',
    // The same actor inside a sentence ("the version written by an outside program").
    'actor.systemInText': 'an outside program',
    'via.shell': 'via a command',
    'via.shellHint': "This change came from a shell command (Bash) that {agent} ran. The host's computer attributes it to that agent by the time the command ran.",
    'notify.label': 'Notifications for you',
    'notify.title': '{from} notified you',
    'notify.dismiss': 'Got it',
    'notify.open': 'Open file',
    'conflicts.label': 'Conflict panel',
    'conflicts.empty': 'No open conflicts',
    'conflicts.emptyHint':
      'When an agent or another program (Bash, a formatter or git, for example) changes a file that someone is editing, the overlapping part keeps the text being edited, and the other version appears here.',
    'conflicts.loading': 'Loading conflicts…',
    'conflicts.error': 'Could not load the conflicts: {message}',
    'conflicts.retry': 'Retry',
    'conflicts.resolved': 'Resolved conflicts ({count})',
    'conflict.summary': 'This file was changed at {time} by {source}, overlapping edits in progress by {humans}.',
    'conflict.summaryNobody': 'This file was changed at {time} by {source}, overlapping edits in progress.',
    'conflict.kept': 'The file keeps the text being edited. The version written by {source} is on the right.',
    'conflict.hunk': 'From line {line}',
    'conflict.human': 'Text being edited (kept for now)',
    'conflict.agent': 'Version by {source}',
    'conflict.lineNumber': 'Line number',
    'conflict.noLines': '(empty)',
    'conflict.base': 'Text before the change',
    'conflict.truncated': 'This part is too long: only the first 64 KB are shown.',
    'conflict.omitted': {
      one: '{count} more overlap is not listed. "View full version" shows everything the other side wrote.',
      other: '{count} more overlaps are not listed. "View full version" shows everything the other side wrote.',
    },
    'conflict.status.open': 'Open',
    'conflict.status.dismissed': 'Kept the text being edited',
    'conflict.status.applied': 'Applied the other version',
    'conflict.openFile': 'Open file',
    'conflict.dismiss': 'Keep the text being edited',
    'conflict.dismissHint': 'Closes this conflict. The file stays as it is.',
    'conflict.apply': 'Apply this version…',
    'conflict.applyHint': 'Replaces the whole file with the full version written by {source}.',
    'conflict.viewFull': 'View full version',
    'conflict.applyTitle': 'Apply the version written by {source}?',
    'conflict.applyText':
      'The whole file is replaced with the full version written by {source} ({size}); the text being edited in the file is lost. Everyone sees the change, and it is recorded in the audit log.',
    'conflict.applyConfirm': 'Apply',
    'conflict.cancel': 'Cancel',
    'conflict.fullTitle': 'Full version written by {source}',
    'conflict.fullDescription': '{path} ({size})',
    'conflict.fullLoading': 'Loading…',
    'conflict.fullError': 'Could not load the full version: {message}',
    'conflict.fullTruncated': 'The content is too long: only the first {shown} characters are shown.',
    'conflict.close': 'Close',
    'conflict.failed': 'Could not resolve the conflict: {message}',
    'conflict.agentLocked': '{agent} is changing this file. Try again in a moment.',
    'conflict.hostOnly': 'Only the host can change this file, so only the host can resolve this conflict.',
  },
  zhTW,
);
