import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { RELAY_DEV_PROXY_PREFIXES } from '@smurg/protocol/relay';
import react from '@vitejs/plugin-react';
import { defineConfig, type Plugin, type ProxyOptions } from 'vite';
import { bundledPackageOf, generateNotices, NOTICES_FILES, ROOT, uncoveredPackages } from '../../scripts/third-party-notices.ts';

/** Build tools whose virtual modules (`\0vite/preload-helper.js`, `\0rolldown/runtime.js`) end up in the bundle. */
const HELPER_MODULE_TOOLS = new Set(['vite', 'rolldown']);

/**
 * The third-party notices (public/third-party-notices.txt, copied into dist and served as /third-party-notices.txt;
 * generated by scripts/third-party-notices.ts): a build refuses a file that is not what pnpm-lock.yaml and
 * node_modules give now, and a bundled npm package (or build-tool helper) the file does not list. The worker bundles
 * (`?worker`, `new Worker(new URL(…))`) are checked by the same plugin without the freshness check.
 */
export function thirdPartyNotices(options: { readonly freshness: boolean }): Plugin {
  return {
    name: 'smurg-third-party-notices',
    apply: 'build',
    buildStart() {
      if (!options.freshness) return;
      if (readFileSync(join(ROOT, NOTICES_FILES.web), 'utf8') !== generateNotices('web')) {
        this.error(`${NOTICES_FILES.web} is out of date (pnpm-lock.yaml changed): run  node scripts/third-party-notices.ts  and commit the result`);
      }
    },
    generateBundle(_output, bundle) {
      const packages = new Set<string>();
      const unknown: string[] = [];
      for (const chunk of Object.values(bundle)) {
        if (chunk.type !== 'chunk') continue;
        for (const id of Object.keys(chunk.modules)) {
          if (id.startsWith('\0')) {
            const tool = id.slice(1).split(/[/?]/)[0] ?? '';
            if (HELPER_MODULE_TOOLS.has(tool)) packages.add(tool);
            else unknown.push(id.slice(1));
            continue;
          }
          const name = bundledPackageOf(id.replace(/\?.*$/, ''));
          if (name !== null) packages.add(name);
        }
      }
      const missing = uncoveredPackages('web', packages);
      if (missing.length > 0) this.error(`the bundle contains ${missing.join(', ')}, which ${NOTICES_FILES.web} does not list: add the package to apps/web's dependencies (pnpm-lock.yaml) and run  node scripts/third-party-notices.ts`);
      if (unknown.length > 0) this.error(`the bundle contains virtual modules of an unknown tool (${unknown.join(', ')}): add the tool to the web notices (scripts/third-party-notices.ts SPECS.web.buildTools) and to HELPER_MODULE_TOOLS`);
    },
  };
}

// Relay dev server (`pnpm dev:relay`: wrangler dev --env dev). The browser only ever talks to the Vite origin, so the
// relay's session cookie and its WebSocket Origin check see one same-origin app, as in production where the relay
// Worker serves this SPA itself (relay.md §1.4). SMURG_RELAY_DEV_ORIGIN lets parallel checkouts use other ports.
// Keep the SAME hostname as the relay's issuer (localhost): the dev login is only enabled for local hostnames and the
// cookie is per host.
const RELAY_DEV_ORIGIN = process.env['SMURG_RELAY_DEV_ORIGIN'] ?? 'http://127.0.0.1:8787';

const toRelay: ProxyOptions = { target: RELAY_DEV_ORIGIN, ws: true, changeOrigin: false };

export default defineConfig({
  plugins: [react(), thirdPartyNotices({ freshness: true })],
  worker: {
    plugins: () => [thirdPartyNotices({ freshness: false })],
  },
  resolve: {
    alias: [
      // y-monaco 0.1.6 deep-imports 'monaco-editor/esm/vs/editor/editor.api.js'; monaco >= 0.56's exports map turns
      // that into esm/vs/esm/vs/… and the build fails without this re-mapping (yjs-monaco.md Q2, F16).
      { find: /^monaco-editor\/esm\/vs\/(.*)$/, replacement: 'monaco-editor/$1' },
    ],
    // One Yjs instance in the bundle: two copies break `instanceof` checks and corrupt documents.
    dedupe: ['yjs', 'y-protocols', 'lib0'],
  },
  server: {
    host: 'localhost',
    port: 5173,
    strictPort: true,
    // Same prefixes as the relay's `run_worker_first` (single source: @smurg/protocol/relay).
    proxy: Object.fromEntries(RELAY_DEV_PROXY_PREFIXES.map((prefix) => [prefix, toRelay])),
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    // scripts/check-chunks.ts reads it to prove Monaco and xterm stay out of the entry chunk.
    manifest: true,
    // Monaco's own lazy chunk is ~4 MB by design (yjs-monaco.md Q2); the entry chunk is checked separately.
    chunkSizeWarningLimit: 4800,
  },
});
