// Traditional Chinese of the `agents` namespace: exactly the keys of strings.ts (the English table defines them).
// Only strings.ts imports this file.
export const zhTW = {
  title: 'agent',
  'tabs.label': 'session 分頁',
  'tab.label': '{title}（{owner} 開的）',
  'tab.pending': '{count} 則建議等待你處理',
  // An ended session's tab is closed in one's own panel only (ARCHITECTURE §9); a running session has no such control.
  'tab.close': '關閉 {title}',
  'tab.closeHint': '按 Delete 關閉這個已結束的分頁',
  'empty.title': '目前沒有 session',
  'empty.canCreate': '開一個 agent session 或終端機，所有組員都能即時看到它在做什麼。',
  'empty.cannotCreate': '主人或「可使用 agent」的成員開啟 session 後，你可以在這裡即時觀看。',
  loading: '正在載入 session…',
  loadError: '無法載入 session 清單：{message}',
  'notice.pausedKeepAlive': '這個分頁暫時沒有顯示終端機（為了節省記憶體），選取後會重新連接。',

  'action.new': '新增 session',
  'action.end': '結束 session',
  'action.endShort': '結束 session',
  'action.terminate': '強制終止',
  'action.closeTab': '關閉分頁',
  'action.closeTabHint': '只會從你自己的面板移除這個已結束的 session，其他成員仍然看得到。',
  'action.scale': '縮放以符合寬度',
  'action.unscale': '以原始大小顯示',
  'action.retry': '重新連接終端機',
  'action.details': '詳細資訊',
  'action.attach': '在自己的終端機接上',
  'attach.title': '在自己的終端機接上這個 session',
  'attach.lead': '用 smurg 指令，就可以在你電腦上的終端機操作這個 session，用法和平常的 Claude Code 一樣。主人和「可使用 agent」的成員可以輸入，其他人只能觀看。',
  'attach.leadHost': '在分享這個工作區的電腦上執行下面的指令，就可以在終端機接上這個 session。',
  'attach.firstTitle': '第一次在這台電腦上使用',
  'attach.firstNote': '請主人在控制台建立一個和你相同角色的新邀請連結給你（瀏覽器加入時用過的連結已經失效）。先登入，再執行第二行指令並貼上這個連結（貼上時不會顯示）。',
  'attach.thenTitle': '之後每次接上',
  'attach.hostTitle': '接上 session',
  'attach.detachNote': '按 Ctrl-] 離開，session 會繼續執行。',
  'attach.copy': '複製指令',
  'attach.close': '完成',
  'action.maximize': '放大 agent 面板（取代編輯器的位置）',
  'action.restoreWidth': '還原 agent 面板大小',
  'terminal.watchOnly': '只能觀看',

  'kind.agent': 'agent（Claude Code）',
  'kind.terminal': '終端機',
  'status.starting': '啟動中',
  'status.running': '執行中',
  'status.exited': '已結束',
  'status.exitedCode': '已結束（結束代碼 {code}）',
  'status.terminated': '已被主人終止',
  'status.terminatedBy': '已被主人（{name}）終止',
  'status.kicked': '已結束（開啟它的人已被移出工作區）',
  'status.left': '已結束（開啟它的人已離開工作區）',
  'status.roleChanged': '已結束（開啟它的人已不能使用 agent）',
  'status.stopped': '已結束（主人已停止分享）',
  'info.label': '{title} 的資訊',
  'info.detailsLabel': '{title} 的詳細資訊',
  'info.owner': '開啟的人',
  'info.kind': '類型',
  'info.status': '狀態',
  'info.where': '位置',
  'info.runsAs': '執行於',
  'info.viewers': '觀看中',
  'owner.you': '你開的',
  'owner.other': '{name} 開的',
  'owner.self': '你',
  'runsAs.value': '主人的電腦，使用主人的 Claude 帳號',
  'where.main': '主工作區',
  'where.worktree': 'worktree：{branch}',
  viewers: '{count} 個連線',

  'terminal.label': '{owner} 開的「{title}」終端機',
  'terminal.connecting': '正在連接終端機…',
  'terminal.loadFailed': '無法載入終端機元件，請重新整理頁面。',
  'terminal.attachFailed': '無法連接終端機：{message}',
  'terminal.readOnly': '這是 {owner} 開的 session，你只能觀看。想讓它做什麼，請在下方的「建議」提出，由主人或「可使用 agent」的成員決定是否採用。',
  'terminal.readOnlyViewer': '這是 {owner} 開的 session，你只能觀看。',
  'terminal.exited': '這個 session 已結束，終端機只能檢視。',
  // The daemon keeps an ended session for a while only (ARCHITECTURE §7.6): a tab that stayed open longer says so.
  'terminal.gone': '這個 session 結束已久，主人的電腦不再保留它的終端機內容。你可以關閉這個分頁。',
  'terminal.floorHint': '面板小於 {cols} × {rows}：終端機可捲動',
  'terminal.floorHintFull':
    'Claude Code 需要至少 {cols} 欄 × {rows} 列。這個面板比較小，所以終端機維持 {cols} × {rows}，可以左右、上下捲動查看；放大 agent 面板就能看到全部。',
  'terminal.overflowHint': '實際大小 {cols} × {rows}：可捲動或縮放',
  'terminal.overflowHintFull':
    '終端機以 session 的實際大小（{cols} 欄 × {rows} 列）顯示，比這個面板大：可以左右、上下捲動查看，或按「縮放以符合寬度」縮小顯示（內容不會重新排列）。',
  'link.noEditor': '編輯器尚未就緒，無法開啟 {path}。',
  'link.failed': '無法開啟 {path}：{message}',

  'new.title': '新增 session',
  'new.kind': '類型',
  'new.kind.agentHint': '在終端機裡執行 Claude Code。',
  'new.kind.terminal': '一般終端機',
  'new.kind.terminalHint': '一個 shell，用來執行測試、建置等指令。',
  'new.where': '工作位置',
  'new.where.main': '共享主工作區',
  'new.where.mainHint': '直接修改大家看到的檔案（有檔案鎖保護）。',
  'new.where.worktreeNew': '我的新 worktree',
  'new.where.worktreeHint': '在自己的 worktree 裡工作，不會弄亂主工作區；完成後再請主人合併。',
  'new.where.worktreeHintHost': '在獨立的 worktree 裡工作，不會弄亂主工作區；完成後再合併回主工作區。',
  'new.where.worktreeKept': '繼續我保留的 worktree：{branch}',
  'new.where.notGit': '這個資料夾不是 git 儲存庫，所以無法使用 worktree。',
  'new.runsAs.host': '這個 session 會在你的電腦上執行，agent 使用你的 Claude 帳號。',
  'new.runsAs.member': '這個 session 會在主人的電腦上執行，agent 使用主人的 Claude 帳號。',
  'new.name': '名稱（選填）',
  'new.nameHint': '顯示在分頁上，例如「修登入頁」。',
  'new.role.editor': '你的角色是「可編輯」，不能開啟 session。你可以觀看所有 session，也可以對 session 提出建議；需要開 agent 時，請主人把你的角色改成「可使用 agent」。',
  'new.role.viewer': '你的角色是「旁觀」，只能觀看 session，不能開啟 session，也不能提出建議。',
  'new.role.unknown': '還沒有連上工作區，暫時無法開啟 session。',
  'new.submit': '開啟',
  'new.created': '已開啟 {title}',

  'error.create': '無法開啟 session',
  'error.forbidden': '你的角色不能執行這個動作。',
  'error.hint.limit': '請先結束不再使用的 session，再試一次。',
  'error.hint.claudeMissing': '主人電腦上找不到 Claude Code（claude 指令）。請主人安裝後再試一次。',
  'error.hint.hooks': '主人電腦上的 smurg 設定不完整，請主人重新啟動 smurg host。',
  'error.hint.exited': '這個 session 已經結束了。',

  'end.title': '結束 session',
  'end.body': '結束後「{title}」的程序會被終止，終端機的內容仍然可以檢視。',
  'end.worktreeQuestion': '要保留這個 session 的 worktree 嗎？',
  'end.keep': '保留 worktree',
  'end.keepHint': '檔案和分支都留著，之後可以再開 session 繼續，或請主人合併。',
  'end.remove': '刪除 worktree',
  'end.removeHint': '連同還沒合併的修改一起刪除，無法復原。',
  'end.confirm': '結束 session',
  'end.done': '已結束 {title}',
  'terminate.title': '強制終止 session',
  'terminate.body': '要終止 {owner} 開的「{title}」嗎？它的所有程序會立即結束。',
  'terminate.confirm': '終止',

  // A logged-out agent: every session uses the host's Claude login (protocol v2), so only the host can fix it.
  'login.notice.host': '你的 Claude Code 還沒有登入。點一下終端機，輸入 /login，依照畫面上的指示登入。',
  'login.notice.member': '主人的 Claude Code 還沒有登入，這個 agent 暫時無法工作。請主人登入（在終端機輸入 /login）。',
  'login.check': '檢查登入狀態',
  'login.recheck': '重新檢查登入狀態',
  'login.result.loggedIn': '已登入 Claude。',
  'login.result.loggedOut': '還沒有登入。',
  'login.result.unknown': '無法確定登入狀態。',
  'empty.hidden': '有 {count} 個已結束的 session 被隱藏了（你關閉了它們的分頁）。',
  'empty.showHidden': '顯示已結束的 session',
  'info.term': '{label}：',
} as const;
