import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the agents feature (session tabs, xterm panel, new-session dialog, attach dialog). English defines the
// keys; strings.zh-TW.ts holds the same keys in Traditional Chinese.
export const t = defineStrings(
  'agents',
  {
    title: 'Agents',
    'tabs.label': 'Session tabs',
    'tab.label': '{title} ({owner})',
    'tab.pending': { one: '{count} suggestion is waiting for you', other: '{count} suggestions are waiting for you' },
    // An ended session's tab is closed in one's own panel only (ARCHITECTURE §9); a running session has no such control.
    'tab.close': 'Close {title}',
    'tab.closeHint': 'Press Delete to close this ended tab',
    'empty.title': 'No sessions yet',
    'empty.canCreate': 'Open an agent session or a terminal. Everyone in the workspace sees what it does as it happens.',
    'empty.cannotCreate': 'Once the host or a member with agent access opens a session, you can watch it here as it happens.',
    // Every tab that is left was closed by this person (ended sessions the host's computer still keeps).
    'empty.hidden': { one: '{count} ended session is hidden because you closed its tab.', other: '{count} ended sessions are hidden because you closed their tabs.' },
    'empty.showHidden': 'Show ended sessions',
    loading: 'Loading sessions…',
    loadError: 'Could not load the session list: {message}',
    'notice.pausedKeepAlive': 'The terminal of this tab is paused to save memory. It reconnects when you select the tab.',

    'action.new': 'New session',
    'action.end': 'End session',
    // The same button's visible text in the one-line session bar (a 420 px panel); its name stays "End session".
    'action.endShort': 'End',
    'action.terminate': 'Terminate',
    'action.closeTab': 'Close tab',
    'action.closeTabHint': 'Removes this ended session from your own panel only. Other members still see it.',
    'action.scale': 'Scale to fit the width',
    'action.unscale': 'Show at original size',
    'action.retry': 'Reconnect the terminal',
    'action.details': 'Details',
    'action.attach': 'Attach from your own terminal',
    'attach.title': 'Attach to this session from your own terminal',
    'attach.lead':
      'With the smurg command you can work in this session from a terminal on your own computer, the same way you use Claude Code. The host and members with agent access can type; everyone else can only watch.',
    'attach.leadHost': 'Run the command below on the computer that shares this workspace to attach to this session from a terminal.',
    'attach.firstTitle': 'The first time on this computer',
    'attach.firstNote':
      'Ask the host to create a new invite link with your role in the console (the link your browser joined with is used up). Log in first, then run the second command and paste the link (it is not shown as you paste).',
    'attach.thenTitle': 'Every time after that',
    'attach.hostTitle': 'Attach to the session',
    'attach.detachNote': 'Press Ctrl-] to detach. The session keeps running.',
    'attach.copy': 'Copy command',
    'attach.close': 'Done',
    'action.maximize': 'Maximize the agents panel (it takes the place of the editor)',
    'action.restoreWidth': 'Restore the size of the agents panel',
    'terminal.watchOnly': 'Watch only',

    'kind.agent': 'Agent (Claude Code)',
    'kind.terminal': 'Terminal',
    'status.starting': 'Starting',
    'status.running': 'Running',
    'status.exited': 'Ended',
    'status.exitedCode': 'Ended (exit code {code})',
    'status.terminated': 'Terminated by the host',
    'status.terminatedBy': 'Terminated by the host ({name})',
    'status.kicked': 'Ended (the member who opened it was removed from the workspace)',
    'status.left': 'Ended (the member who opened it left the workspace)',
    'status.roleChanged': 'Ended (the member who opened it no longer has agent access)',
    'status.stopped': 'Ended (the host stopped sharing)',
    'info.label': 'About {title}',
    'info.detailsLabel': 'Details of {title}',
    // One row of the details list: the label and its separator (the value follows).
    'info.term': '{label}:',
    'info.owner': 'Opened by',
    'info.kind': 'Kind',
    'info.status': 'Status',
    'info.where': 'Location',
    'info.runsAs': 'Runs on',
    'info.viewers': 'Watching',
    // The one-line summary above a terminal (a 420 px panel: short). The details row names the person after "Opened by".
    'owner.you': 'By you',
    'owner.other': 'By {name}',
    'owner.self': 'You',
    'runsAs.value': "The host's computer, with the host's Claude account",
    'where.main': 'Main workspace',
    'where.worktree': 'Worktree: {branch}',
    viewers: { one: '{count} connection', other: '{count} connections' },

    'terminal.label': 'Terminal of "{title}", opened by {owner}',
    'terminal.connecting': 'Connecting to the terminal…',
    'terminal.loadFailed': 'Could not load the terminal. Reload the page.',
    'terminal.attachFailed': 'Could not connect to the terminal: {message}',
    'terminal.readOnly':
      '{owner} opened this session; you can only watch. To have it do something, make a suggestion below: the host or a member with agent access decides whether to accept it.',
    'terminal.readOnlyViewer': '{owner} opened this session; you can only watch.',
    'terminal.exited': 'This session has ended. The terminal is read-only.',
    // The daemon keeps an ended session for a while only (ARCHITECTURE §7.6): a tab that stayed open longer says so.
    'terminal.gone': "This session ended a while ago, and the host's computer no longer keeps its terminal output. You can close this tab.",
    'terminal.floorHint': 'Panel smaller than {cols} × {rows}: the terminal scrolls',
    'terminal.floorHintFull':
      'Claude Code needs at least {cols} columns × {rows} rows. This panel is smaller, so the terminal stays at {cols} × {rows} and scrolls in both directions. Enlarge the agents panel to see all of it.',
    'terminal.overflowHint': 'Actual size {cols} × {rows}: scroll or scale',
    'terminal.overflowHintFull':
      'The terminal is shown at the actual size of the session ({cols} columns × {rows} rows), which is larger than this panel. Scroll in both directions, or use "Scale to fit the width" to draw it smaller (the content is not rearranged).',
    'link.noEditor': 'The editor is not ready yet, so {path} cannot be opened.',
    'link.failed': 'Could not open {path}: {message}',

    'new.title': 'New session',
    'new.kind': 'Kind',
    'new.kind.agentHint': 'Runs Claude Code in a terminal.',
    'new.kind.terminal': 'Plain terminal',
    'new.kind.terminalHint': 'A shell, for running tests, builds and other commands.',
    'new.where': 'Where to work',
    'new.where.main': 'Shared main workspace',
    'new.where.mainHint': 'Changes the files everyone sees (file locks protect them).',
    'new.where.worktreeNew': 'A new worktree of my own',
    'new.where.worktreeHint': 'Work in your own worktree without disturbing the main workspace. When you are done, ask the host to merge it.',
    'new.where.worktreeHintHost': 'Work in a separate worktree without disturbing the main workspace. When you are done, merge it back.',
    'new.where.worktreeKept': 'Continue in the worktree I kept: {branch}',
    'new.where.notGit': 'This folder is not a git repository, so worktrees are not available.',
    'new.runsAs.host': 'This session runs on your computer, and the agent uses your Claude account.',
    'new.runsAs.member': "This session runs on the host's computer, and the agent uses the host's Claude account.",
    'new.name': 'Name (optional)',
    'new.nameHint': 'Shown on the tab, for example "Fix the login page".',
    'new.role.editor':
      'As an editor you cannot open a session. You can watch every session and make suggestions to it. If you need to open an agent, ask the host to give you agent access.',
    'new.role.viewer': 'As a viewer you can only watch sessions. You cannot open one or make suggestions.',
    'new.role.unknown': 'You are not connected to the workspace yet, so you cannot open a session right now.',
    'new.submit': 'Open',
    'new.created': 'Opened {title}',

    'error.create': 'Could not open the session',
    'error.forbidden': 'Your role does not allow this.',
    'error.hint.limit': 'End a session you no longer use, then try again.',
    'error.hint.claudeMissing': "Claude Code (the claude command) was not found on the host's computer. Ask the host to install it, then try again.",
    'error.hint.hooks': "The smurg setup on the host's computer is incomplete. Ask the host to restart smurg host.",
    'error.hint.exited': 'This session has already ended.',

    'end.title': 'End session',
    'end.body': 'Ending "{title}" stops its processes. The terminal output stays readable.',
    'end.worktreeQuestion': 'Keep the worktree of this session?',
    'end.keep': 'Keep the worktree',
    'end.keepHint': 'The files and the branch stay. You can open another session in it later, or ask the host to merge it.',
    'end.remove': 'Delete the worktree',
    'end.removeHint': 'Deletes it together with the changes that are not merged yet. This cannot be undone.',
    'end.confirm': 'End session',
    'end.done': 'Ended {title}',
    'terminate.title': 'Terminate session',
    'terminate.body': 'Terminate "{title}", opened by {owner}? All of its processes stop at once.',
    'terminate.confirm': 'Terminate',

    // A logged-out agent: every session uses the host's Claude login, so only the host can fix it.
    'login.notice.host': 'Your Claude Code is not logged in. Click the terminal, type /login and follow the steps on screen.',
    'login.notice.member': "The host's Claude Code is not logged in, so this agent cannot work for now. Ask the host to log in (type /login in the terminal).",
    'login.check': 'Check login',
    'login.recheck': 'Check login again',
    'login.result.loggedIn': 'Logged in to Claude.',
    'login.result.loggedOut': 'Not logged in yet.',
    'login.result.unknown': 'Could not tell whether Claude is logged in.',
  },
  zhTW,
);
