import { defineStrings } from '../../strings/catalog.ts';

// Namespace of the agents feature (session tabs, xterm panel, new-session dialog, login guide, import config).
export const t = defineStrings('agents', {
  title: 'agent',
  'tabs.label': 'session 分頁',
  'tab.label': '{title}（{owner}）',
  'tab.pending': '{count} 則建議等待你處理',
  'empty.title': '目前沒有 session',
  'empty.canCreate': '開一個 agent session 或終端機，所有組員都能即時看到它在做什麼。',
  'empty.cannotCreate': '主人或「可執行 agent」的成員開啟 session 後，你可以在這裡即時觀看。',
  loading: '正在載入 session…',
  loadError: '無法載入 session 清單：{message}',
  'notice.pausedKeepAlive': '這個分頁暫時沒有顯示終端機（為了節省記憶體），選取後會重新連接。',

  'action.new': '新增 session',
  'action.import': '匯入個人設定',
  'action.more': '更多動作',
  'action.end': '結束 session',
  'action.terminate': '強制終止',
  'action.loginGuide': '登入說明',
  'action.scale': '縮放以符合寬度',
  'action.unscale': '以原始大小顯示',
  'action.retry': '重新連接終端機',
  'action.details': '詳細資訊',
  'action.attach': '在自己的終端機接上',
  'attach.title': '在自己的終端機接上這個 session',
  'attach.lead': '用 smurg 指令，就可以在你電腦上的終端機操作這個 session，用法和平常的 Claude Code 一樣。只有 session 的擁有者可以輸入，其他人是唯讀。',
  'attach.leadHost': '在分享這個工作區的電腦上執行下面的指令，就可以在終端機接上這個 session。',
  'attach.firstTitle': '第一次在這台電腦上使用',
  'attach.firstNote': '請主人在控制台建立一個和你相同角色的新邀請連結給你（瀏覽器加入時用過的連結已經失效）。先登入，再執行第二行指令並貼上這個連結（貼上時不會顯示）。',
  'attach.thenTitle': '之後每次接上',
  'attach.hostTitle': '接上 session',
  'attach.detachNote': '按 Ctrl-] 離開，session 會繼續執行。',
  'attach.copy': '複製指令',
  'attach.close': '完成',
  'action.maximize': '放大 agent 面板（取代編輯器的位置）',
  'action.restoreWidth': '還原 agent 面板大小',
  'terminal.watchOnly': '只能觀看',

  'kind.agent': 'agent（Claude Code）',
  'kind.terminal': '終端機',
  'kind.login': '登入程序（Claude 訂閱）',
  'status.starting': '啟動中',
  'status.running': '執行中',
  'status.exited': '已結束',
  'status.exitedCode': '已結束（結束代碼 {code}）',
  'status.terminated': '已被主人終止',
  'status.terminatedBy': '已被主人（{name}）終止',
  'status.kicked': '已結束（擁有者已被移出工作區）',
  'status.left': '已結束（擁有者已離開工作區）',
  'status.roleChanged': '已結束（擁有者的角色已變更）',
  'status.stopped': '已結束（主人已停止分享）',
  'info.label': '{title} 的資訊',
  'info.detailsLabel': '{title} 的詳細資訊',
  'info.owner': '擁有者',
  'info.kind': '類型',
  'info.status': '狀態',
  'info.where': '位置',
  'info.sandbox': '沙盒',
  'info.viewers': '觀看中',
  'owner.you': '{name}（你）',
  'where.main': '主工作區',
  'where.worktree': 'worktree：{branch}',
  'sandbox.on': '在沙盒內執行',
  'sandbox.off': '沒有沙盒（主人的 session）',
  viewers: '{count} 個連線',

  'terminal.label': '{owner}的「{title}」終端機',
  'terminal.connecting': '正在連接終端機…',
  'terminal.loadFailed': '無法載入終端機元件，請重新整理頁面。',
  'terminal.attachFailed': '無法連接終端機：{message}',
  'terminal.readOnly': '這是 {owner} 的 session，你只能觀看。想讓它做什麼，請在下方的「建議」提出，由 {owner} 決定是否採用。',
  'terminal.exited': '這個 session 已結束，終端機只能檢視。',
  'terminal.floorHint': '面板小於 {cols} × {rows}：終端機可捲動',
  'terminal.floorHintFull':
    'Claude Code 需要至少 {cols} 欄 × {rows} 列。這個面板比較小，所以終端機維持 {cols} × {rows}，可以左右、上下捲動查看；放大 agent 面板就能看到全部。',
  'terminal.overflowHint': '實際大小 {cols} × {rows}：可捲動或縮放',
  'terminal.overflowHintFull':
    '終端機以 session 的實際大小（{cols} 欄 × {rows} 列）顯示，比這個面板大：可以左右、上下捲動查看，或按「縮放以符合寬度」縮小顯示（內容不會重新排列）。',
  'link.noEditor': '編輯器尚未就緒，無法開啟 {path}。',
  'link.failed': '無法開啟 {path}：{message}',

  'new.title': '新增 session',
  'new.kind': '類型',
  'new.kind.agentHint': '在終端機裡執行 Claude Code。',
  'new.kind.terminal': '一般終端機',
  'new.kind.terminalHint': '一個 shell，用來執行測試、建置等指令。',
  'new.where': '工作位置',
  'new.where.main': '共享主工作區',
  'new.where.mainHint': '直接修改大家看到的檔案（有檔案鎖保護）。',
  'new.where.worktreeNew': '我的新 worktree',
  'new.where.worktreeHint': '在自己的 worktree 裡工作，不會弄亂主工作區；完成後再請主人合併。',
  'new.where.worktreeHintHost': '在獨立的 worktree 裡工作，不會弄亂主工作區；完成後再合併回主工作區。',
  'new.where.worktreeKept': '繼續我保留的 worktree：{branch}',
  'new.where.notGit': '這個資料夾不是 git 儲存庫，所以無法使用 worktree。',
  'new.name': '名稱（選填）',
  'new.nameHint': '顯示在分頁上，例如「修登入頁」。',
  'new.sandbox.guest': '你的 session 會在主人電腦上的沙盒裡執行：只能讀寫這個工作區（或你的 worktree）和你自己的暫存目錄，網路只能連到白名單上的網域。',
  'new.sandbox.host': '這是主人的 session：不放沙盒，使用你自己的 Claude Code 設定與登入。',
  'new.role.editor': '你的角色是「可編輯」，不能開啟 session。你可以觀看所有 session，也可以對別人的 session 提出建議；需要自己的 agent 時，請主人把你的角色改成「可執行 agent」。',
  'new.role.viewer': '你的角色是「旁觀」，只能觀看 session，不能開啟 session，也不能提出建議。',
  'new.role.unknown': '還沒有連上工作區，暫時無法開啟 session。',
  'new.apiKey.toggle': '用自己的 Anthropic API key 登入（選填）',
  'new.apiKey.label': '你的 Anthropic API key',
  'new.apiKey.hint': 'key 只會隨這次的請求送給這個 session，由主人電腦的記憶體保存，不會存進瀏覽器，也不會寫進任何紀錄。',
  'new.apiKey.invalid': 'API key 的格式不正確（不能有空白，最多 256 個字元）。',
  'new.submit': '開啟',
  'new.created': '已開啟 {title}',

  'error.create': '無法開啟 session',
  'error.sandbox': '沙盒無法啟動，session 沒有開啟',
  'error.sandboxNoFallback': 'smurg 不會在沒有沙盒的情況下執行客人的 session。請把上面的訊息轉告主人，處理後再試一次。',
  'error.claudeVersion': '主人電腦上的 Claude Code 版本太舊或無法辨識，為了安全不會開啟客人 session。請主人更新 Claude Code 後再試一次。',
  'error.forbidden': '你的角色不能執行這個動作。',
  'error.hint.limit': '請先結束不再使用的 session，再試一次。',
  'error.hint.claudeMissing': '主人電腦上找不到 Claude Code（claude 指令）。請主人安裝後再試一次。',
  'error.hint.hooks': '主人電腦上的 smurg 設定不完整，請主人重新啟動 smurg host。',
  'error.hint.sessionsRunning': '匯入只能在你沒有執行中的 session 時進行：請先結束你的 session，匯入後再開新的 session。',
  'error.hint.exited': '這個 session 已經結束了。',
  'error.hint.loginOff': '主人關閉了客人用 Claude 訂閱登入的功能，請改用你自己的 API key 登入。',
  'error.hint.loginRunning': '你已經有一個登入程序在執行，請在它的分頁完成登入。',

  'end.title': '結束 session',
  'end.body': '結束後「{title}」的程序會被終止，終端機的內容仍然可以檢視。',
  'end.worktreeQuestion': '要保留這個 session 的 worktree 嗎？',
  'end.keep': '保留 worktree',
  'end.keepHint': '檔案和分支都留著，之後可以再開 session 繼續，或請主人合併。',
  'end.remove': '刪除 worktree',
  'end.removeHint': '連同還沒合併的修改一起刪除，無法復原。',
  'end.confirm': '結束 session',
  'end.done': '已結束 {title}',
  'terminate.title': '強制終止 session',
  'terminate.body': '要終止{owner}的「{title}」嗎？它的所有程序會立即結束。',
  'terminate.confirm': '終止',

  'login.title': '登入 Claude',
  'login.lead': '這個 agent session 還沒有登入 Claude。請依照下面的步驟，用你自己的帳號登入。',
  'login.hostLead': '你的 Claude Code 還沒有登入。請在終端機輸入 /login，依照畫面上的指示用你的帳號登入。',
  'login.sub.title': '方法一：用 Claude 訂閱帳號登入',
  'login.sub.step1': '點一下終端機，輸入 /login 後按 Enter。',
  'login.sub.step2': '出現「Select login method」時，選擇 Claude 訂閱帳號（Claude account with subscription）。',
  'login.sub.step3': '終端機會顯示一個登入網址。點擊或複製它，在你自己的瀏覽器開啟，登入你的帳號並授權。',
  'login.sub.step4': '網頁會顯示一組授權碼。複製後貼到終端機「Paste code here if prompted」的位置，再按 Enter。',
  'login.sub.step5': '看到「Login successful」後，按下方的「重新檢查登入狀態」。',
  'login.sub.browserNote': '登入網址只會顯示在終端機裡，不會在主人的電腦上打開瀏覽器。請不要請主人幫你開啟或授權這個網址。',
  'login.guestSub.title': '方法一：用 Claude 訂閱登入',
  'login.guestSub.lead':
    '你的 agent 在沙盒裡無法自己完成訂閱登入，所以 smurg 會在主人電腦上、你自己的沙盒裡開一個專用的登入程序（只有你看得到），它會顯示一個登入網址。',
  'login.guestSub.start': '用 Claude 訂閱登入',
  'login.guestSub.off': '主人關閉了客人用 Claude 訂閱登入的功能，所以請用你自己的 Anthropic API key 登入。',
  'login.key.title': '方法二：用 Anthropic API key 登入',
  'login.key.titleOnly': '用 Anthropic API key 登入',
  'login.key.lead': '沒有訂閱的話，可以使用你自己的 API key。smurg 會用這個 key 重新開啟一個 session，取代這個還沒登入的 session。',
  'login.key.submit': '用這個 key 重新開啟 session',
  'login.key.limit': '建議在 Anthropic Console 為這個 key 設定花費上限，不用時就撤銷它。',
  'login.key.done': '已用你的 API key 開啟新的 session。',
  'login.key.oldStillRunning': '新的 session 已開啟，但舊的 session 沒能結束，請手動結束它。',
  'login.warning.title': '登入前請先了解',
  'login.warning.host': '你的 session 在主人的電腦上執行。即使放在沙盒裡，主人在技術上仍然可以讀取你在這裡使用的憑證（登入權杖或 API key），也可能用掉你的額度。只在你信任主人時登入。',
  'login.warning.leave': '你按「離開」退出工作區時，smurg 會登出並刪除你在主人電腦上的暫存目錄（連同憑證）。只是關閉分頁或斷線不會刪除。',
  'login.recheck': '重新檢查登入狀態',
  'login.check': '檢查登入狀態',
  'login.result.loggedIn': '已登入 Claude。',
  'login.result.loggedOut': '還沒有登入。完成上面的步驟後再檢查一次。',
  'login.result.unknown': '無法確定登入狀態。',
  'login.hide': '先隱藏說明',
  'login.watcher': '{owner} 的 Claude 還沒有登入。',

  'loginProcess.title': '用 Claude 訂閱登入',
  'loginProcess.step1':
    '下方的終端機會顯示「If the browser didn\'t open, visit:」和一個登入網址（主人的電腦不會打開任何瀏覽器）。點它，或選取後複製，在你自己的瀏覽器開啟。',
  'loginProcess.step2': '在瀏覽器登入你的 Claude 帳號，並按下授權（Authorize）。',
  'loginProcess.step3': '網頁會顯示一組授權碼：複製它，點一下下方的終端機，在「Paste code here if prompted」的位置貼上，再按 Enter。',
  'loginProcess.step4': '登入成功後，這個登入程序會自己結束，smurg 會再檢查一次你的登入狀態。',
  'loginProcess.private': '這個登入程序在主人電腦上你自己的沙盒裡執行，只有你看得到、只有你能輸入，最多執行 10 分鐘。',
  'loginProcess.cancel': '取消登入',
  'loginProcess.checking': '登入程序已結束，正在檢查登入狀態…',
  'loginProcess.done': '已登入 Claude。',
  'loginProcess.doneNext':
    '回到「{title}」，直接輸入下一個指令就可以，不需要重新開啟 session。如果它的狀態列還顯示「Not logged in」，不用理會：下一個指令就會使用新的登入。',
  'loginProcess.doneNoSession': '登入程序已順利結束。之後開啟的 agent session 會使用這個登入。',
  'loginProcess.back': '回到「{title}」',
  'loginProcess.notDone': '還沒有登入：登入程序已結束（結束代碼 {code}），但 Claude 仍回報沒有登入。可以再試一次，或改用 API key。',
  'loginProcess.unknown': '登入程序已結束（結束代碼 {code}），但無法確定登入狀態。請到 agent session 的登入說明按「重新檢查登入狀態」。',
  'loginProcess.timedOut': '登入程序已執行 10 分鐘，自動結束了。可以再試一次。',
  'loginProcess.cancelled': '已取消登入。',
  'loginProcess.retry': '再試一次',

  'import.title': '匯入個人設定',
  'import.lead': '把你自己的 CLAUDE.md、自訂指令（commands）和 skills 複製到你在主人電腦上的暫存設定目錄。之後開啟的 agent session 會載入它們；你離開工作區時會一起刪除。',
  'import.runningNote': '匯入前請先結束你所有的 session。',
  'import.runningBlocked': '你還有 {count} 個執行中的 session。主人電腦只在你沒有執行中的 session 時寫入設定：請先結束它們，匯入後再開新的 session。',
  'import.pick.claudeMd': '選擇 CLAUDE.md',
  'import.pick.commands': '選擇 commands 資料夾',
  'import.pick.skills': '選擇 skills 資料夾',
  'import.list': '將匯入 {count} 個檔案（{size}）',
  'import.skipped': '略過 {count} 個檔案',
  'import.reason.tooLarge': '超過 1 MB',
  'import.reason.notAllowed': '不是可以匯入的路徑',
  'import.reason.system': '系統檔案',
  'import.reason.unreadable': '無法讀取',
  'import.tooMany': '一次最多匯入 {max} 個檔案、共 {size}。請只選擇需要的資料夾。',
  'import.batches': '檔案較多，會分成 {count} 次送出；每次都是全部寫入或全部不寫入。',
  'import.submit': '匯入',
  'import.working': '正在匯入（{done}/{total}）…',
  'import.done': '已寫入 {count} 個檔案',
  'import.partial': '部分檔案已寫入，其餘沒有寫入：{message}',
  'import.failed': '匯入失敗：{message}',
  'import.empty': '還沒有選擇檔案。',
});
