import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the transfer feature (streaming upload / download in a Web Worker, transfers panel). English defines
// the keys; strings.zh-TW.ts holds the same keys in Traditional Chinese.
export const t = defineStrings(
  'transfer',
  {
    active: { one: '{count} transfer in progress', other: '{count} transfers in progress' },
    'panel.label': 'Uploads and downloads',
    'list.label': 'Transfer queue',
    'empty.title': 'No transfers right now',
    'empty.hint': 'Drag files or folders onto the file tree to upload them. The file tree menu lets you download a file, or a folder as a zip.',

    'action.clear': 'Clear finished',
    'action.pause': 'Pause',
    'action.resume': 'Resume',
    'action.cancel': 'Cancel',
    'action.retry': 'Retry',
    'action.dismiss': 'Remove',
    'action.save': 'Save file',
    'action.pickFiles': 'Choose the files to continue',
    'action.pickFolder': 'Choose the folder to continue',
    'action.reauthorize': 'Allow reading and continue',
    'action.discard': 'Discard this upload',
    'action.forName': '{action}: {name}',

    'kind.upload': 'Upload',
    'kind.download': 'Download',
    'kind.prefix': '{kind}: ',
    'item.detail': ': {detail}',
    'status.queued': 'Waiting',
    'status.preparing': 'Preparing',
    'status.running': 'Transferring',
    'status.verifying': "Checking what the host's computer already has",
    'status.paused': 'Paused',
    'status.paused.offline': 'Connection lost; continues by itself when it is back',
    'status.paused.reload': 'Interrupted by a page reload; choose the same files again to continue',
    'status.done': 'Done',
    'status.failed': 'Failed',
    'status.cancelled': 'Cancelled',

    'progress.label': 'Progress of {name}',
    'progress.bytes': '{done} of {total}',
    'progress.bytesUnknown': '{done} done',
    'progress.files': '{done} of {total} files',
    'progress.speed': '{speed}/s',
    'progress.remaining': 'About {time} left',

    'target.uploadTo': 'Upload to {path}',
    'target.uploadToRoot': 'Upload to the project root',
    'target.downloadFrom': 'From {path}',
    'target.downloadRoot': 'Whole project',
    'name.multiple': '{first} and others ({count} items)',

    'conflict.title': 'These names already exist',
    'conflict.description': "The host's computer already has the names below. What should happen with this upload?",
    'conflict.more': '…and {count} more',
    'conflict.overwrite': 'Overwrite',
    'conflict.rename': 'Keep both (rename automatically)',
    'conflict.cancel': 'Cancel upload',

    'fail.disk':
      "The host's disk does not have enough space, so the upload did not start: it needs {requested}, which would leave only {freeAfter}, less than the reserved {reserve} ({available} available now, {pending} set aside for other uploads in progress). The host can change the reserved space in the settings.",
    'fail.diskUnknown': "The host's disk does not have enough space, so the upload did not start.",
    'fail.diskMidway': 'The host\'s disk is full and the upload is paused. Once space is freed, press "Retry" to continue where it stopped.',
    'fail.sourceChanged': '"{path}" changed during the upload. The upload was stopped so that two versions do not get mixed; upload it again.',
    'fail.sourceUnreadable': 'Could not read "{path}": the file may have been moved or deleted, or the browser lost permission to read it.',
    'fail.connection': 'The transfer connection ended and cannot continue.',
    'fail.connection.kicked': 'The host removed you from the workspace; the transfer was stopped.',
    'fail.connection.revoked': "This browser's device key was revoked; the transfer was stopped.",
    'fail.connection.login': 'Your login expired. Log in again and retry.',
    'fail.connection.storage': "This browser's device key could not be read, so files cannot be transferred.",
    'fail.connection.keyMismatch': "The key of the host's computer differs from the one recorded earlier; the connection was refused for safety.",
    'fail.conflictDeclined': "Cancelled: the host's computer already has a file with the same name.",
    'fail.storage.quota': 'The browser is out of storage: {needed} needed, {available} left. Use Chrome (it saves straight to disk), or download with the smurg CLI.',
    'fail.storage.quotaUnknown': 'The browser is out of storage, so the download was stopped. Use Chrome (it saves straight to disk), or download with the smurg CLI.',
    'fail.storage.memory':
      'This browser can only keep downloads of up to {limit} in memory, and this file is {needed}. Use Chrome (it saves straight to disk), or download with the smurg CLI.',
    'fail.storage.memoryUnknown': 'This download is larger than the {limit} this browser can keep in memory. Use Chrome (it saves straight to disk), or download with the smurg CLI.',
    'fail.storage.write': 'Writing the downloaded file failed, so the download was stopped.',
    'fail.changedOnHost': "The file changed on the host's computer during the download. Download it again.",
    'fail.internal': 'An unexpected error occurred during the transfer.',
    'fail.files': { one: '{count} file was not uploaded', other: '{count} files were not uploaded' },

    'rejected.title': { one: '{count} item was not added to the upload', other: '{count} items were not added to the upload' },
    'rejected.duplicate': 'Duplicate name',
    'rejected.unreadable': 'Could not be read',
    'rejected.invalid': "The name has characters the host's computer does not accept",

    'download.skipped': {
      one: '{count} item was left out of the zip or added as an empty file',
      other: '{count} items were left out of the zip or added as empty files',
    },
    'download.skip.empty': 'Added to the zip, but empty (the file was gone when it was read)',
    'download.skip.special': 'Special file (for example a FIFO or a socket), skipped',
    'download.skip.link': 'Link that points outside the folder, skipped',
    'download.skip.other': 'Skipped ({reason})',
    'download.zip64':
      'This zip is large (ZIP64 format): the unzip tool built into macOS may show an error after it has extracted every file. If files are missing, use another unzip tool, or download files of 4 GB and more one by one.',
    'download.savedBlob': 'Download finished. If the browser did not save the file by itself, press "Save file".',
    'download.savedPicker': 'Saved to the location you chose.',

    'worker.unavailable': 'This browser cannot run transfers in the background (Web Worker), so uploading and downloading are not available.',
    'worker.noStorage': 'This browser window cannot use IndexedDB (for example in private browsing), so transfers cannot get the device key. Use a regular window.',
    'worker.failed': 'The transfer component could not start: {message}',
    'toast.nothingToUpload': 'Nothing to upload',
    'toast.resumeMismatch': 'The files you chose are not those of the interrupted upload; nothing can be continued.',
  },
  zhTW,
);
