// zh-TW table of the transfer namespace: the same keys as strings.ts (English defines them).
export const zhTW = {
  active: '{count} 個傳輸進行中',
  'panel.label': '上傳與下載',
  'list.label': '傳輸佇列',
  'empty.title': '目前沒有傳輸',
  'empty.hint': '把檔案或資料夾拖曳到檔案樹即可上傳；在檔案樹的選單中可以下載檔案，或把資料夾打包成 zip 下載。',

  'action.clear': '清除已完成',
  'action.pause': '暫停',
  'action.resume': '繼續',
  'action.cancel': '取消',
  'action.retry': '重試',
  'action.dismiss': '移除',
  'action.save': '儲存檔案',
  'action.pickFiles': '選擇檔案以繼續',
  'action.pickFolder': '選擇資料夾以繼續',
  'action.reauthorize': '允許讀取並繼續',
  'action.discard': '放棄這次上傳',
  'action.forName': '{action}：{name}',

  'kind.upload': '上傳',
  'kind.download': '下載',
  'kind.prefix': '{kind}：',
  'item.detail': '：{detail}',
  'status.queued': '等待中',
  'status.preparing': '準備中',
  'status.running': '傳輸中',
  'status.verifying': '正在比對主人電腦上已有的部分',
  'status.paused': '已暫停',
  'status.paused.offline': '連線中斷，恢復後會自動繼續',
  'status.paused.reload': '頁面重新整理後中斷，請重新選擇相同的檔案以繼續',
  'status.done': '完成',
  'status.failed': '失敗',
  'status.cancelled': '已取消',

  'progress.label': '{name} 的進度',
  'progress.bytes': '{done}／{total}',
  'progress.bytesUnknown': '已完成 {done}',
  'progress.files': '{done}／{total} 個檔案',
  'progress.speed': '{speed}/秒',
  'progress.remaining': '剩餘約 {time}',

  'target.uploadTo': '上傳到 {path}',
  'target.uploadToRoot': '上傳到專案根目錄',
  'target.downloadFrom': '來自 {path}',
  'target.downloadRoot': '整個專案',
  'name.multiple': '{first} 等 {count} 個項目',

  'conflict.title': '已經有同名的檔案',
  'conflict.description': '主人電腦上已經有下列名稱。要怎麼處理這次上傳？',
  'conflict.more': '……還有 {count} 個',
  'conflict.overwrite': '覆蓋',
  'conflict.rename': '另存新檔（自動改名）',
  'conflict.cancel': '取消上傳',

  'fail.disk': '主人的磁碟空間不足，上傳尚未開始：需要 {requested}，上傳後只剩 {freeAfter}，低於保留空間 {reserve}（目前可用 {available}，其他進行中的上傳預留 {pending}）。主人可以在設定中調整保留空間。',
  'fail.diskUnknown': '主人的磁碟空間不足，上傳尚未開始。',
  'fail.diskMidway': '主人的磁碟已滿，上傳已暫停。騰出空間後按「重試」即可從中斷處繼續。',
  'fail.sourceChanged': '「{path}」在上傳期間被修改，為了避免混入兩個版本已停止上傳，請重新上傳。',
  'fail.sourceUnreadable': '無法讀取「{path}」：檔案可能已被移動或刪除，或瀏覽器失去了讀取權限。',
  'fail.connection': '傳輸連線已結束，無法繼續。',
  'fail.connection.kicked': '你已被主人移出工作區，傳輸已停止。',
  'fail.connection.revoked': '這個瀏覽器的裝置金鑰已被撤銷，傳輸已停止。',
  'fail.connection.login': '登入已過期，請重新登入後再試。',
  'fail.connection.storage': '無法讀取這個瀏覽器的裝置金鑰，因此無法傳輸檔案。',
  'fail.connection.keyMismatch': '主人電腦的金鑰與先前記錄的不同，為了安全已拒絕連線。',
  'fail.conflictDeclined': '已取消：主人電腦上已有同名的檔案。',
  'fail.storage.quota': '瀏覽器的儲存空間不足：需要 {needed}，只剩 {available}。請改用 Chrome（可直接存到磁碟），或以 smurg CLI 下載。',
  'fail.storage.quotaUnknown': '瀏覽器的儲存空間不足，下載已停止。請改用 Chrome（可直接存到磁碟），或以 smurg CLI 下載。',
  'fail.storage.memory': '這個瀏覽器只能在記憶體中暫存 {limit} 以內的下載，而這個檔案有 {needed}。請改用 Chrome（可直接存到磁碟），或以 smurg CLI 下載。',
  'fail.storage.memoryUnknown': '這個下載超過了瀏覽器能在記憶體中暫存的 {limit}。請改用 Chrome（可直接存到磁碟），或以 smurg CLI 下載。',
  'fail.storage.write': '寫入下載的檔案時發生錯誤，下載已停止。',
  'fail.changedOnHost': '檔案在下載期間於主人電腦上被修改，請重新下載。',
  'fail.internal': '傳輸時發生未預期的錯誤。',
  'fail.files': '{count} 個檔案沒有上傳',

  'rejected.title': '{count} 個項目沒有加入上傳',
  'rejected.duplicate': '重複的名稱',
  'rejected.unreadable': '無法讀取',
  'rejected.invalid': '名稱含有主人電腦不接受的字元',

  'download.skipped': '{count} 個項目沒有放進 zip，或以空檔案放入',
  'download.skip.empty': '已放入 zip，但內容是空的（讀取時檔案已不存在）',
  'download.skip.special': '特殊檔案（例如 FIFO 或 socket），已略過',
  'download.skip.link': '指向資料夾外的連結，已略過',
  'download.skip.other': '已略過（{reason}）',
  'download.zip64': '這個 zip 很大（使用 ZIP64 格式）：macOS 內建的解壓縮工具可能在取出全部檔案後顯示錯誤；若缺少檔案，請改用其他解壓縮工具，或單獨下載 4 GB 以上的檔案。',
  'download.savedBlob': '下載完成。如果瀏覽器沒有自動存檔，請按「儲存檔案」。',
  'download.savedPicker': '已存到你選擇的位置。',

  'worker.unavailable': '這個瀏覽器無法在背景執行傳輸（Web Worker），因此無法上傳或下載。',
  'worker.noStorage': '這個瀏覽器視窗無法使用 IndexedDB（例如私密瀏覽），傳輸無法取得裝置金鑰。請改用一般視窗。',
  'worker.failed': '傳輸元件無法啟動：{message}',
  'toast.nothingToUpload': '沒有可以上傳的檔案',
  'toast.resumeMismatch': '選擇的檔案與中斷的上傳不同，沒有可以繼續的檔案。',
} as const;
