// The zh-TW words of the README's picture (scripts/readme-picture.ts draws them). Every one is a word of the product
// page's own picture (apps/site/public/zh-TW/index.html), which a lint holds to the app's zh-TW catalogs;
// tests/lint/readme-picture.test.ts holds this copy to that page.
import type { Words } from '../readme-picture.ts';

export const ZH_TW: Words = {
  lang: 'zh-Hant-TW',
  parts: ['決定', '計畫', '實作', '檢視'],
  topic: '結帳流程',
  connected: '已連線',
  qFrom: 'Claude 的選擇題',
  voted: ['3 人中 1 人已投票', '3 人中 2 人已投票', '3 人都投票了'],
  q: '購物車要存在哪裡？',
  optA: '存在伺服器',
  optB: '存在瀏覽器',
  leading: '領先',
  decides: '由 Ian 決定',
  submit: '送出答案',
  answered: '已回答：存在伺服器',
  spec: 'spec',
  plan: '計畫',
  specLine: ['購物車存在伺服器上，', '跟著帳號。'],
  writing: 'Claude 正在寫計畫…',
  items: '3 個工作項目',
  names: ['購物車 API', '付款', '結帳頁'],
  ready: '可以開始',
  running: '執行中',
  note: ['「開始」會為每個項目開一個 agent session，', '各自在自己的 worktree。'],
  start: '開始 3 個項目',
  started: '已開始 3 個項目。',
  toReview: '報告待看',
  worktree: 'worktree：',
  edited: '編輯',
  created: '建立',
  read: '讀取',
  working: 'Claude 工作中',
  waitingBadge: '等待許可',
  perm: ['Claude 請求許可', '執行指令'],
  permJoin: '',
  allow: '允許一次',
  deny: '拒絕',
  allowed: 'Ben 允許了一次',
  waiting: 'Claude 正在等待許可',
  report: '結果報告：',
  whatDone: '做了什麼',
  doneText: '購物車存在伺服器上，每個帳號一個。',
  howVerified: '怎麼驗證的',
  changes: '變更',
  reviewBtn: '我已看過',
  marked: '已標成看過。',
  reviewed: '已看過',
  reviewedMerged: '已看過 · 已合併',
  merged: '已合併到主工作區。',
};
