// zh-TW table of the `columns` namespace: exactly the keys of ./strings.ts (the English table defines them).
export const zhTW = {
  'region': '開啟的欄',
  'close': '關閉這一欄：{title}',
  'more': '「{title}」的更多操作',
  'closeOthers': '關閉其他欄',
  'pin': '釘選這一欄：{title}',
  'unpin': '取消釘選：{title}',
  'pin.item': '釘選這一欄',
  'unpin.item': '取消釘選',
  'title.hint': '{title}（按 Delete 關閉這一欄）',
  'title.topic': '{title} · {topic}',
  'refused': '已經開了四欄，請先關閉一欄。',
  'gone.session': '這個 session 結束已久，主人的電腦不再保留它的內容。你可以關閉這一欄。',
  'gone.topic': '這個主題已被刪除。你可以關閉這一欄。',
  'gone.changes': '這個合併請求已經不存在。你可以關閉這一欄。',
  'gone.close': '關閉這一欄',
  'waiting': '正在載入「{title}」',
  'placeholder.title': '這裡無法顯示「{title}」',
  'placeholder.body': '這個版本的 smurg 沒有可以顯示這種欄的功能。',
  'side.region': '編輯器旁的 session',
  'side.choose': '顯示在編輯器旁的 session',
  'side.none': '不顯示 session',
  'side.empty.title': '編輯器旁沒有 session',
  'side.empty.body': '選一個 agent session，把它的對話留在程式碼旁邊。',
  'side.empty.none': '還沒有 agent session。請到 session 畫面開一個。',
} as const;
