import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the worktree feature (root switcher, merge requests, the host's diff review). English defines the keys;
// strings.zh-TW.ts holds the same keys in Traditional Chinese.
export const t = defineStrings(
  'worktree',
  {
    // ---- switcher (top of the files sidebar)
    switcherLabel: 'Viewing',
    main: 'Main workspace',
    'option.gone': 'Removed worktree',
    'active.label': 'Worktree in view',
    'active.owner': 'Owner: {owner}',
    'active.branch': 'Branch: {branch}',
    'active.kept': 'Kept (no session at the moment)',
    'active.session': 'A session is using it',
    'active.shared': 'Read-only shared folders: {dirs}',
    'active.requestMerge': 'Ask the host to merge',
    'active.remove': 'Remove this worktree',
    'remove.title': "Remove {owner}'s worktree?",
    'remove.body': 'The worktree folder of branch {branch} will be deleted, together with any changes not yet merged into the main workspace. This cannot be undone.',
    'remove.confirm': 'Remove worktree',
    'remove.done': 'Worktree removed.',
    'remove.failed': 'Could not remove the worktree: {message}',

    // ---- merge requests list (host console)
    mergeTitle: 'Merge requests',
    'list.loading': 'Loading merge requests…',
    'list.failed': 'Could not load merge requests: {message}',
    'list.empty': "No merge requests yet. The host and members with agent access can ask the host to merge a worktree's changes into the main workspace.",
    'list.pendingTitle': 'Waiting for review ({count})',
    'list.decidedTitle': 'Decided',
    'list.draftsTitle': 'Work items nobody reviewed yet',
    'item.title': 'Merge request from {name}',
    'item.titleDraft': 'Changes of a work item',
    'item.branch': 'Branch {branch}',
    'item.worktreeGone': 'Worktree removed',
    'item.commit': 'Commit {commit}',
    'item.requestedAt': 'Requested {time}',
    'status.pending': 'Waiting for the host',
    'status.draft': 'Not requested yet',
    'status.draftReviewed': 'Reviewed, ready to merge',
    'status.merged': 'Merged',
    'status.rejected': 'Rejected',
    'status.conflict': 'Merge conflict',
    'detail.pendingRequester': 'The host is reviewing it. Changes made in the worktree after the request are not part of it.',
    'detail.merged': 'Merged into the main workspace {time}.',
    'detail.rejected': 'The host rejected this request; the worktree is unchanged. Reason: {reason}',
    'detail.rejectedNoReason': 'The host rejected this request; the worktree is unchanged.',
    'detail.conflict': 'The merge was aborted and the main workspace is unchanged. Files in conflict:',
    'detail.conflictHost':
      'What you can do next: merge by hand in your own terminal and resolve the conflicts (for example git merge refs/smurg/merge/{id}); change these files in the main workspace and try the merge again; or reject the request and say why.',
    'detail.conflictRequester': 'The host decides what happens next: resolve the conflicts on their own computer and merge, or reject the request.',
    'action.review': 'Review',
    'action.viewDiff': 'View diff',
    'mine.title': 'My worktrees',
    'mine.request': 'Request merge',
    'mine.pending': 'A request is waiting for review',

    // ---- request dialog (worktree owner)
    'request.title': 'Ask the host to merge {branch}',
    'request.lead': 'smurg puts everything changed in this worktree so far into one commit; that commit is what the host reviews and merges. Changes made later need a new request.',
    'request.message': 'Message (optional)',
    'request.placeholder': 'What changed and why it should be merged',
    'request.pendingNote': 'This worktree already has a request waiting for review; sending again creates another one.',
    'request.submit': 'Send merge request',
    'request.sent': 'Merge request sent. Waiting for the host to review it.',
    'request.failed': 'Could not send the merge request: {message}',
    'text.tooLong': 'The text is too long (at most {max} characters).',
    'text.invalidMultiline': 'The text has characters that are not allowed (control characters or text-direction controls). Remove them and send again.',
    'text.invalidLine': 'The reason must be one line, without control characters or text-direction controls.',

    // ---- review (host; the requester may look read-only)
    'review.title': 'Review the merge request from {name}',
    'review.titleReadOnly': 'Merge request from {name}',
    'review.titleDraft': 'Changes on {branch}',
    'review.summary': 'Branch {branch} · commit {commit} · {files}',
    'review.summaryGone': 'Worktree removed · commit {commit} · {files}',
    'review.fileCount': { one: '{count} file', other: '{count} files' },
    'review.fileCountUnknown': '… files',
    'review.counts': '{additions}, {deletions} in total',
    'review.counts.file': '{additions}, {deletions}',
    'review.linesAdded': { one: '{count} line added', other: '{count} lines added' },
    'review.linesDeleted': { one: '{count} line deleted', other: '{count} lines deleted' },
    'review.message': 'Message from {name}:',
    'review.messageDraft': 'Message:',
    'review.loading': 'Loading the diff…',
    'review.loadFailed': 'Could not load the diff: {message}',
    'review.reload': 'Reload',
    'review.files': 'Changed files',
    'review.noFiles': 'This request changes no files.',
    'review.truncated': 'The full diff is larger than 1 MiB, so only the first part is included. Each file marked "Open separately" has to be opened before you can merge.',
    'review.mustOpen': 'Open separately',
    'review.opened': 'Viewed',
    'review.remaining': {
      one: '{count} file still has to be opened before you can merge.',
      other: '{count} files still have to be opened before you can merge.',
    },
    'review.allOpened': 'Every file that had to be opened separately has been viewed.',
    'review.openNext': 'Open the next unviewed file',
    'review.selectFile': 'Select a file to see its diff.',
    'review.fileLoading': 'Loading the diff of {path}…',
    'review.fileFailed': 'Could not load the diff of {path}: {message}',
    'review.fileTruncated': 'The diff of this file is larger than 1 MiB; only the first part is shown.',
    'review.binary': 'Binary file; there is no text diff to show.',
    'review.withheld': 'This file is on a path only the host may read. Its changes are not shown to you.',
    'review.hiddenChars':
      'The diff of this file contains invisible characters (for example controls that change the direction text is displayed in). They are marked as ⟨U+…⟩. Check that the code really is what it looks like.',
    'review.hiddenChar': 'Invisible character {code}',
    'review.noTextChange': 'No change in the text (for example only the file name or the file permissions changed).',
    'review.showMore': { one: 'Show more ({count} more line)', other: 'Show more ({count} more lines)' },
    'review.diffLabel': 'Diff of {path}',
    'review.renamedFrom': 'Previously {path}',
    'review.binaryBadge': 'Binary',
    'file.status.added': 'Added',
    'file.status.modified': 'Modified',
    'file.status.deleted': 'Deleted',
    'file.status.renamed': 'Renamed',
    'file.status.copied': 'Copied',
    'file.status.type-changed': 'Type changed',
    'file.status.unmerged': 'Unmerged',
    'file.status.unknown': 'Unknown change',
    'review.approve': 'Merge into the main workspace',
    'review.retryApprove': 'Try the merge again',
    'review.confirmApprove': {
      one: 'Commit {commit} ({count} file) will be merged into the main workspace, and everyone sees the changes at once. Merge it?',
      other: 'Commit {commit} ({count} files) will be merged into the main workspace, and everyone sees the changes at once. Merge it?',
    },
    'review.confirm': 'Confirm merge',
    'review.reject': 'Reject',
    'review.rejectReason': 'Reason for rejecting (optional; {name} will see it)',
    'review.rejectReasonDraft': 'Reason for rejecting (optional)',
    'review.confirmReject': 'Confirm rejection',
    'review.merged': 'The changes from {name} were merged into the main workspace.',
    'review.mergedDraft': 'The changes were merged into the main workspace.',
    'review.conflict': 'The merge ran into conflicts and was aborted. The main workspace is unchanged.',
    'review.rejected': 'The merge request from {name} was rejected. The worktree is unchanged.',
    'review.rejectedDraft': 'The changes were rejected. The worktree is unchanged.',
    'review.failed': 'Could not finish: {message}',
    'review.decided': 'This request has already been decided: {status}.',
    // ---- the changed files of a result report (ChangedFiles.tsx)
    'files.byHand': 'edited by hand: {names}',
    'files.hostOnly': 'Host only',
    'files.openInEditor': 'Open in editor',
    'files.truncated': 'The whole diff is larger than 1 MiB: the remaining files load when you open them.',
    'notice.merged': 'The host merged your merge request into the main workspace.',
    'notice.rejected': 'The host rejected your merge request.',
    'notice.reason': 'Reason: {reason}',
    'notice.conflict': 'Your merge request conflicts with the main workspace, so the host could not merge it.',
    'notice.conflictFiles': 'Files in conflict: {files}',
  },
  zhTW,
);
