// zh-TW table of the worktree namespace: the same keys as strings.ts (English defines them).
export const zhTW = {
  // ---- switcher (top of the files sidebar)
  switcherLabel: '檢視的工作區',
  main: '主工作區',
  'option.gone': '已移除的 worktree',
  'active.label': '目前檢視的 worktree',
  'active.owner': '擁有者：{owner}',
  'active.branch': '分支：{branch}',
  'active.kept': '已保留（目前沒有 session）',
  'active.session': '有 session 正在使用',
  'active.shared': '唯讀的共享資料夾：{dirs}',
  'active.requestMerge': '請主人合併',
  'active.remove': '移除這個 worktree',
  'remove.title': '移除 {owner} 的 worktree？',
  'remove.body': '分支 {branch} 的 worktree 資料夾會被刪除，還沒合併回主工作區的修改會一起消失。這個動作無法復原。',
  'remove.confirm': '移除 worktree',
  'remove.done': '已移除 worktree。',
  'remove.failed': '無法移除 worktree：{message}',

  // ---- merge requests list (host console)
  mergeTitle: '合併請求',
  'list.loading': '正在載入合併請求…',
  'list.failed': '無法載入合併請求：{message}',
  'list.empty': '還沒有合併請求。主人和「可使用 agent」的成員可以請主人把 worktree 的修改合併回主工作區。',
  'list.pendingTitle': '等待審核（{count}）',
  'list.decidedTitle': '已處理',
  'list.draftsTitle': '還沒有人看過的工作項目',
  'item.title': '{name} 的合併請求',
  'item.titleDraft': '工作項目的變更',
  'item.branch': '分支 {branch}',
  'item.worktreeGone': 'worktree 已移除',
  'item.commit': '提交 {commit}',
  'item.requestedAt': '{time}提出',
  'status.pending': '等待主人審核',
  'status.draft': '尚未請求合併',
  'status.draftReviewed': '已看過，可以合併',
  'status.merged': '已合併',
  'status.rejected': '已拒絕',
  'status.conflict': '合併時發生衝突',
  'detail.pendingRequester': '主人審核中。提出請求之後在 worktree 裡的修改，不包含在這個請求裡。',
  'detail.merged': '已在 {time}合併到主工作區。',
  'detail.rejected': '主人拒絕了這個請求，worktree 保持原狀。原因：{reason}',
  'detail.rejectedNoReason': '主人拒絕了這個請求，worktree 保持原狀。',
  'detail.conflict': '合併已中止，主工作區沒有任何改變。發生衝突的檔案：',
  'detail.conflictHost': '接下來你可以：在自己的終端機裡手動合併並解決衝突（例如 git merge refs/smurg/merge/{id}）；先在主工作區調整這些檔案，再重新嘗試合併；或拒絕這個請求並說明原因。',
  'detail.conflictRequester': '主人會決定怎麼處理：在自己的電腦上解決衝突後合併，或拒絕這個請求。',
  'detail.conflictItem': '這是工作項目的變更，所以它的 agent 可以解決衝突：主人和「可使用 agent」的成員，可以在這個項目的結果報告，或計畫裡它的那一列，按「請 agent 解決衝突」。',
  'action.review': '審核',
  'action.viewDiff': '查看差異',
  'mine.title': '我的 worktree',
  'mine.request': '請求合併',
  'mine.pending': '已有等待審核的請求',

  // ---- request dialog (worktree owner)
  'request.title': '請主人合併 {branch}',
  'request.lead': 'smurg 會把這個 worktree 目前所有的修改建立成一個提交（commit），主人審核和合併的就是這個提交。之後再修改的內容，需要重新提出請求。',
  'request.message': '說明（選填）',
  'request.placeholder': '這次改了什麼、為什麼要合併',
  'request.pendingNote': '這個 worktree 已經有等待審核的請求；再送出會另外建立一個新的請求。',
  'request.submit': '送出合併請求',
  'request.sent': '已送出合併請求，等待主人審核。',
  'request.failed': '無法送出合併請求：{message}',
  'text.tooLong': '內容太長了（最多 {max} 個字元）。',
  'text.invalidMultiline': '內容裡有不允許的字元（控制字元或文字方向控制字元），請移除後再送出。',
  'text.invalidLine': '原因只能有一行，而且不能有控制字元或文字方向控制字元。',

  // ---- review (host; the requester may look read-only)
  'review.title': '審核 {name} 的合併請求',
  'review.titleReadOnly': '{name} 的合併請求',
  'review.titleDraft': '{branch} 的變更',
  'review.summary': '分支 {branch} · 提交 {commit} · {files}',
  'review.summaryGone': 'worktree 已移除 · 提交 {commit} · {files}',
  'review.fileCount': '{count} 個檔案',
  'review.fileCountUnknown': '… 個檔案',
  'review.counts': '共{additions}、{deletions}',
  'review.linesAdded': '新增 {count} 行',
  'review.linesDeleted': '刪除 {count} 行',
  'review.message': '{name} 的說明：',
  'review.messageDraft': '說明：',
  'review.loading': '正在載入差異…',
  'review.loadFailed': '無法載入差異：{message}',
  'review.reload': '重新載入',
  'review.files': '變更的檔案',
  'review.noFiles': '這個請求沒有任何檔案變更。',
  'review.truncated': '完整差異超過 1 MiB，只附上了前面的部分。標示「需要個別開啟」的檔案必須逐一開啟檢視，才能合併。',
  'review.mustOpen': '需要個別開啟',
  'review.opened': '已檢視',
  'review.remaining': '還有 {count} 個檔案需要個別開啟檢視，之後才能合併。',
  'review.allOpened': '所有需要個別開啟的檔案都已檢視。',
  'review.openNext': '開啟下一個未檢視的檔案',
  'review.selectFile': '選擇一個檔案查看差異。',
  'review.fileLoading': '正在載入 {path} 的差異…',
  'review.fileFailed': '無法載入 {path} 的差異：{message}',
  'review.fileTruncated': '這個檔案的差異超過 1 MiB，只顯示前面的部分。',
  'review.binary': '二進位檔案，無法顯示文字差異。',
  'review.withheld': '這個檔案位在只有主人能讀的路徑，它的變更不會顯示給你。',
  'review.hiddenChars': '這個檔案的差異含有看不見的字元（例如會改變文字顯示方向的控制字元），已經用 ⟨U+…⟩ 標示出來。請確認程式碼實際的內容和看起來的一樣。',
  'review.hiddenChar': '看不見的字元 {code}',
  'review.noTextChange': '沒有文字內容的變更（例如只改了檔名或檔案權限）。',
  'review.showMore': '顯示更多（還有 {count} 行）',
  'review.diffLabel': '{path} 的差異',
  'review.counts.file': '{additions}、{deletions}',
  'review.renamedFrom': '原本是 {path}',
  'review.binaryBadge': '二進位',
  'file.status.added': '新增',
  'file.status.modified': '修改',
  'file.status.deleted': '刪除',
  'file.status.renamed': '重新命名',
  'file.status.copied': '複製',
  'file.status.type-changed': '類型變更',
  'file.status.unmerged': '未合併',
  'file.status.unknown': '未知變更',
  'review.approve': '合併到主工作區',
  'review.retryApprove': '重新嘗試合併',
  'review.confirmApprove': '會把提交 {commit}（{count} 個檔案）合併到主工作區，所有人都會立即看到這些修改。確定要合併嗎？',
  'review.confirm': '確認合併',
  'review.reject': '拒絕',
  'review.rejectReason': '拒絕原因（選填，會告訴 {name}）',
  'review.rejectReasonDraft': '拒絕原因（選填）',
  'review.confirmReject': '確認拒絕',
  'review.merged': '已把 {name} 的修改合併到主工作區。',
  'review.mergedDraft': '已把這些變更合併到主工作區。',
  'review.conflict': '合併時發生衝突，已中止合併，主工作區沒有改變。',
  'review.rejected': '已拒絕 {name} 的合併請求，worktree 保持原狀。',
  'review.rejectedDraft': '已拒絕這些變更，worktree 保持原狀。',
  'review.failed': '無法完成：{message}',
  'review.decided': '這個請求已經處理過了：{status}。',
  // ---- the changed files of a result report (ChangedFiles.tsx)
  'files.byHand': '手動編輯：{names}',
  'files.hostOnly': '僅主人可見',
  'files.openInEditor': '在編輯器開啟',
  'files.truncated': '完整的差異超過 1 MiB：其餘檔案會在你展開時載入。',
  'notice.merged': '主人已把你的合併請求合併到主工作區。',
  'notice.rejected': '主人拒絕了你的合併請求。',
  'notice.reason': '原因：{reason}',
  'notice.conflict': '你的合併請求和主工作區有衝突，主人無法合併。',
  'notice.conflictFiles': '衝突的檔案：{files}',
} as const;
