// smurg's own license and the third-party notices of the single executable (`smurg licenses`).
//
// packages/cli/THIRD-PARTY-NOTICES.txt is generated by scripts/third-party-notices.ts from pnpm-lock.yaml and the
// installed packages: the license and notice files of every package the executable contains. It ends with a
// placeholder section for the Node.js runtime, because the Node.js release (and with it the text of Node's own LICENSE,
// which lists the libraries Node contains) is only known when an executable is built: scripts/build-sea.ts replaces
// that section with the LICENSE file of the Node.js distribution the executable is a copy of, and embeds the result,
// with LICENSE, as SEA assets (NOTICE_ASSETS). This module is shared by the build, the generator and the command.
import { existsSync, readFileSync, realpathSync } from 'node:fs';
import { dirname, join } from 'node:path';

/** The SEA asset keys scripts/build-sea.ts embeds and `smurg licenses` prints. */
export const NOTICE_ASSETS = {
  license: 'notices/LICENSE',
  thirdParty: 'notices/THIRD-PARTY-NOTICES.txt',
} as const;

/** The line that separates the packages' sections in the notices files. */
export const SECTION_RULE = '='.repeat(80);

/** The last section of packages/cli/THIRD-PARTY-NOTICES.txt as committed (the generator writes exactly this). */
export const NODE_PENDING_SECTION = `${SECTION_RULE}
Node.js runtime

The executable is a copy of the Node.js runtime with smurg's program inside it. In the copy of this file that is built
into the executable (\`smurg licenses\`) and in the one published with each release, this section is the LICENSE file of
the Node.js release that executable is built from, which also lists the libraries Node.js contains and their licenses.
`;

export interface NodeLicense {
  /** e.g. `22.22.1` */
  readonly version: string;
  /** The LICENSE file of that Node.js distribution. */
  readonly text: string;
}

/** Line endings, trailing spaces and trailing blank lines normalised, one final newline (as the generator does). */
export function normaliseText(text: string): string {
  const lines = text.replace(/^﻿/, '').replace(/\r\n?/g, '\n').split('\n').map((line) => line.replace(/[ \t]+$/, ''));
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  while (lines.length > 0 && lines[0] === '') lines.shift();
  return `${lines.join('\n')}\n`;
}

/**
 * The LICENSE file of the Node.js distribution `nodeBinary` belongs to: every official build (the tarballs nvm and
 * actions/setup-node unpack, the macOS installer's /usr/local) has `bin/node` next to a top-level `LICENSE`. null when
 * there is none (a distribution package that moved it elsewhere).
 */
export function nodeDistributionLicense(nodeBinary: string, version: string): NodeLicense | null {
  let real: string;
  try {
    real = realpathSync(nodeBinary);
  } catch {
    return null;
  }
  const file = join(dirname(dirname(real)), 'LICENSE');
  if (!existsSync(file)) return null;
  const text = readFileSync(file, 'utf8');
  // Node's LICENSE starts with Node's own MIT text; refuse a stray LICENSE of something else.
  if (!/^Node\.js is licensed for use as follows:/m.test(text)) return null;
  return { version, text: normaliseText(text) };
}

/**
 * The executable's complete notices: the committed file with its Node.js placeholder section replaced by `node`'s
 * LICENSE. Throws when the committed text does not end with that placeholder (it is not the generator's output).
 */
export function composeExecutableNotices(committed: string, node: NodeLicense): string {
  if (!committed.endsWith(`\n${NODE_PENDING_SECTION}`)) {
    throw new Error('THIRD-PARTY-NOTICES.txt does not end with the Node.js placeholder section (regenerate it: node scripts/third-party-notices.ts)');
  }
  if (!/^\d+\.\d+\.\d+$/.test(node.version)) throw new Error(`not a Node.js version: ${node.version}`);
  const section = `${SECTION_RULE}
node@${node.version} (the Node.js runtime)
License: MIT; the libraries Node.js contains are listed with their licenses in this LICENSE file
Source: https://nodejs.org/

----- LICENSE -----
${normaliseText(node.text)}`;
  return `${committed.slice(0, committed.length - NODE_PENDING_SECTION.length)}${section}`;
}
