// @vitest-environment node
// The web app's third-party notices: public/third-party-notices.txt (generated by scripts/third-party-notices.ts) is
// in every build's dist, so the relay serves it at /third-party-notices.txt; the build refuses a bundled npm package or
// a build tool's helper module that the file does not list (vite.config.ts thirdPartyNotices). The landing page's links
// to it, to smurg's license and to the guides: src/app/pages/LandingPage.test.tsx.
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import { build, type Plugin } from 'vite';
import { createTempDir, removeTempDir } from '../../../packages/daemon/src/testing/index.ts';
import { thirdPartyNotices } from '../vite.config.ts';

const WEB = fileURLToPath(new URL('..', import.meta.url));
const NOTICES = readFileSync(join(WEB, 'public', 'third-party-notices.txt'), 'utf8');

const temps: string[] = [];
afterEach(async () => {
  while (temps.length > 0) await removeTempDir(temps.pop() as string);
});

type Bundle = Record<string, { type: 'chunk'; modules: Record<string, unknown> } | { type: 'asset' }>;

/** Runs the plugin's generateBundle on a fake bundle; the error it raises, or null. */
function check(modules: readonly string[]): string | null {
  const plugin = thirdPartyNotices({ freshness: false }) as Plugin & { generateBundle(this: unknown, output: unknown, bundle: Bundle): void };
  const context = {
    error(message: string): never {
      throw new Error(message);
    },
  };
  try {
    plugin.generateBundle.call(context, {}, { 'index.js': { type: 'chunk', modules: Object.fromEntries(modules.map((id) => [id, {}])) }, 'x.css': { type: 'asset' } });
    return null;
  } catch (err) {
    return (err as Error).message;
  }
}

describe('third-party notices of the web app', () => {
  it('are in the built dist, byte for byte, next to index.html (served as /third-party-notices.txt)', async () => {
    const out = await createTempDir('web-notices');
    temps.push(out);
    await build({ root: WEB, configFile: join(WEB, 'vite.config.ts'), logLevel: 'silent', build: { outDir: out, emptyOutDir: true } });
    expect(existsSync(join(out, 'index.html'))).toBe(true);
    expect(readFileSync(join(out, 'third-party-notices.txt'), 'utf8')).toBe(NOTICES);
    expect(NOTICES.startsWith('smurg: third-party notices of the smurg web app\n')).toBe(true);
    for (const name of ['react', 'react-dom', 'monaco-editor', '@xterm/xterm', 'yjs', 'zod', 'vite', 'rolldown']) expect(NOTICES).toMatch(new RegExp(`\\n {2}${name.replace(/[/.]/g, '\\$&')}@\\S+ {2}`));
    // Monaco's own third-party notices travel with it.
    expect(NOTICES).toContain('----- ThirdPartyNotices.txt -----');
    // The two other files of public/ that the relay serves as they are travel the same way: what keeps the web app
    // out of search results (robots.txt, and the noindex line of _headers; apps/relay/test/search-engines.test.ts
    // holds what they say and serves them).
    expect(readFileSync(join(out, 'robots.txt'), 'utf8')).toBe(readFileSync(join(WEB, 'public', 'robots.txt'), 'utf8'));
    expect(readFileSync(join(out, '_headers'), 'utf8')).toBe(readFileSync(join(WEB, 'public', '_headers'), 'utf8'));
    expect(readFileSync(join(out, '_headers'), 'utf8')).toMatch(/^[ \t]+X-Robots-Tag: noindex$/m);
  }, 120_000);

  it('the build refuses a bundled package or a helper module the notices do not list', () => {
    const pnpm = (name: string): string => `/r/node_modules/.pnpm/${name.replace('/', '+')}@1.0.0/node_modules/${name}/index.js`;
    expect(check([pnpm('react'), pnpm('@xterm/xterm'), '/r/apps/web/src/main.tsx', '/r/packages/protocol/src/index.ts', '\0vite/preload-helper.js', '\0rolldown/runtime.js', `${pnpm('monaco-editor')}?worker`])).toBeNull();
    expect(check([pnpm('react'), pnpm('left-pad')])).toMatch(/the bundle contains left-pad, which apps\/web\/public\/third-party-notices\.txt does not list/);
    expect(check(['\0some-tool/helper.js'])).toMatch(/virtual modules of an unknown tool \(some-tool\/helper\.js\)/);
  });
});
