import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the files feature (tree, root switcher, drag-drop upload, download). English defines the keys;
// strings.zh-TW.ts holds the same keys in Traditional Chinese.
export const t = defineStrings(
  'files',
  {
    title: 'Files',
    treeLabel: 'File tree of {root}',
    menuLabel: 'Actions for "{name}"',
    menuLabelRoot: 'Actions for the root folder',
    loading: 'Loading files…',
    loadingFolder: 'Loading {name}…',
    emptyRoot: 'This folder has no files yet',
    emptyFolder: '(empty folder)',
    truncated: 'This folder has more than 10,000 items; only the first part is listed.',
    'root.main': 'Main workspace',
    'root.worktree': 'Worktree: {name}',
    'action.open': 'Open',
    'action.newFile': 'New file',
    'action.newFolder': 'New folder',
    'action.upload': 'Upload',
    'action.uploadFiles': 'Upload files…',
    'action.uploadFolder': 'Upload folder…',
    'action.rename': 'Rename…',
    'action.delete': 'Delete…',
    'action.download': 'Download',
    'action.downloadZip': 'Download (zip)',
    'action.downloadRoot': 'Download the whole workspace (zip)',
    'action.copyPath': 'Copy path',
    'action.refresh': 'Refresh',
    'action.retry': 'Retry',
    'error.list': 'Could not load the files: {message}',
    'error.folder': 'Could not load this folder',
    'error.unavailable': 'This feature is not ready yet. Try again in a moment.',
    'error.agentLocked': '{agent} is editing this file. Try again in a moment.',
    'error.humanLocked': 'This file is being edited by {names}. Try again in a moment.',
    'toast.deleted': 'Deleted "{name}"',
    'toast.pathCopied': 'Path copied',
    'toast.copyFailed': 'Could not copy to the clipboard',
    'drop.hint': 'Drop to upload into "{folder}"',
    'drop.hintRoot': 'Drop to upload into the root folder',
    'badge.agentLock': '{agent} editing',
    'badge.agentLockLabel': '{agent} is editing this file; it cannot be edited for now',
    'badge.humanLock': 'Editing: {names}',
    'badge.humanLockLabel': 'Being edited by {names}; agents cannot change it for now',
    'badge.you': 'you',
    'badge.recentLabel': 'Recently changed by {name} ({time})',
    'badge.readOnlyLabel': 'Read-only (shared folder)',
    'badge.hostOnlyLabel': 'Only the host can change this file',
    'actor.system': 'an outside program',
    'name.empty': 'Enter a name',
    'name.slash': 'A name cannot contain "/"',
    'name.dots': 'A name cannot be "." or ".."',
    'name.invisible': 'A name cannot contain control characters or invisible direction characters',
    'name.backslash': 'A name cannot contain "\\"',
    'name.tooLong': 'The name is too long',
    'name.invalid': 'This name cannot be used',
    'name.exists': 'This folder already has an item with this name (upper and lower case count as the same)',
    'name.unchanged': 'The name has not changed',
    'name.hostOnly': 'Only the host can create or change a file with this name',
    'dialog.newFileTitle': 'New file',
    'dialog.newFolderTitle': 'New folder',
    'dialog.renameTitle': 'Rename "{name}"',
    'dialog.inRoot': 'Location: root folder',
    'dialog.inFolder': 'Location: {folder}',
    'dialog.fileName': 'File name',
    'dialog.folderName': 'Folder name',
    'dialog.newName': 'New name',
    'dialog.create': 'Create',
    'dialog.rename': 'Rename',
    'dialog.cancel': 'Cancel',
    'dialog.delete': 'Delete',
    'dialog.deleteFileTitle': 'Delete "{name}"?',
    'dialog.deleteFolderTitle': 'Delete the folder "{name}" and everything in it?',
    'dialog.deleteFileText': "The file is deleted from the host's computer. Everyone sees the change, and it cannot be undone here.",
    'dialog.deleteFolderText': "The folder and every file in it are deleted from the host's computer. Everyone sees the change, and it cannot be undone here.",
    'dialog.deleteFileInUse':
      'This file is open or being edited by {names}. After it is deleted, their tabs show that the file was deleted, and what they type afterwards cannot be saved.',
    'dialog.deleteFolderInUse':
      'Files in this folder are open or being edited by {names}. After the folder is deleted, their tabs show that the file was deleted, and what they type afterwards cannot be saved.',
    'action.forceRelease': 'Force release the lock…',
    'forceRelease.title': 'Force release the lock on "{name}"?',
    'forceRelease.agentText':
      '{holders} is editing this file. After a force release everyone can edit it right away; if what the agent writes next overlaps with someone else\'s edits, it appears in the conflicts panel.',
    'forceRelease.humanText': 'This file is being edited by {holders}. After a force release, agents can change it right away.',
    'forceRelease.confirm': 'Force release',
    'forceRelease.done': 'Force released the lock on "{name}"',
    'forceRelease.failed': 'Could not force release: {message}',
    'list.sentence': '; ',
  },
  zhTW,
);
