// zh-TW table of the files namespace: the same keys as strings.ts (English defines them).
export const zhTW = {
  title: '檔案',
  treeLabel: '{root} 的檔案樹',
  menuLabel: '「{name}」的動作',
  menuLabelRoot: '根目錄的動作',
  loading: '正在載入檔案…',
  loadingFolder: '正在載入 {name}…',
  emptyRoot: '這個資料夾還沒有任何檔案',
  emptyFolder: '（空資料夾）',
  truncated: '這個資料夾超過 10,000 個項目，只列出前面的部分。',
  'root.main': '主工作區',
  'root.worktree': 'worktree：{name}',
  'action.open': '開啟',
  'action.newFile': '新增檔案',
  'action.newFolder': '新增資料夾',
  'action.upload': '上傳',
  'action.uploadFiles': '上傳檔案…',
  'action.uploadFolder': '上傳資料夾…',
  'action.rename': '重新命名…',
  'action.delete': '刪除…',
  'action.download': '下載',
  'action.downloadZip': '下載（zip 壓縮檔）',
  'action.downloadRoot': '下載整個工作區（zip 壓縮檔）',
  'action.copyPath': '複製路徑',
  'action.refresh': '重新整理',
  'action.retry': '重試',
  'error.list': '無法載入檔案：{message}',
  'error.folder': '無法載入這個資料夾',
  'error.unavailable': '這項功能還沒有準備好，請稍後再試。',
  'error.agentLocked': '{agent} 正在修改這個檔案，請稍後再試。',
  'error.humanLocked': '{names} 正在編輯這個檔案，請稍後再試。',
  'toast.deleted': '已刪除「{name}」',
  'toast.pathCopied': '已複製路徑',
  'toast.copyFailed': '無法複製到剪貼簿',
  'drop.hint': '放開以上傳到「{folder}」',
  'drop.hintRoot': '放開以上傳到根目錄',
  'badge.agentLock': '{agent} 修改中',
  'badge.agentLockLabel': '{agent} 正在修改這個檔案，暫時無法編輯',
  'badge.humanLock': '{names} 編輯中',
  'badge.humanLockLabel': '{names} 正在編輯這個檔案，agent 暫時不能修改它',
  'badge.you': '你',
  'badge.recentLabel': '最近由 {name} 修改（{time}）',
  'badge.readOnlyLabel': '唯讀（共享資料夾）',
  'badge.hostOnlyLabel': '只有主人可以修改這個檔案',
  'actor.system': '外部程式',
  'name.empty': '請輸入名稱',
  'name.slash': '名稱不能包含「/」',
  'name.dots': '名稱不能是「.」或「..」',
  'name.invisible': '名稱不能包含控制字元或看不見的方向字元',
  'name.backslash': '名稱不能包含「\\」',
  'name.tooLong': '名稱太長',
  'name.invalid': '這個名稱無法使用',
  'name.exists': '這個資料夾裡已經有同名的項目（不分大小寫）',
  'name.unchanged': '名稱沒有改變',
  'name.hostOnly': '只有主人可以建立或修改這個名稱的檔案',
  'dialog.newFileTitle': '新增檔案',
  'dialog.newFolderTitle': '新增資料夾',
  'dialog.renameTitle': '重新命名「{name}」',
  'dialog.inRoot': '位置：根目錄',
  'dialog.inFolder': '位置：{folder}',
  'dialog.fileName': '檔案名稱',
  'dialog.folderName': '資料夾名稱',
  'dialog.newName': '新名稱',
  'dialog.create': '建立',
  'dialog.rename': '重新命名',
  'dialog.cancel': '取消',
  'dialog.delete': '刪除',
  'dialog.deleteFileTitle': '要刪除「{name}」嗎？',
  'dialog.deleteFolderTitle': '要刪除資料夾「{name}」和裡面的所有內容嗎？',
  'dialog.deleteFileText': '檔案會從主人的電腦上刪除，所有人都會看到這個變更，無法在這裡復原。',
  'dialog.deleteFolderText': '資料夾和裡面的所有檔案都會從主人的電腦上刪除，所有人都會看到這個變更，無法在這裡復原。',
  'dialog.deleteFileInUse': '{names}正開著或正在編輯這個檔案。刪除後，他們的分頁會顯示檔案已被刪除，之後輸入的內容無法儲存。',
  'dialog.deleteFolderInUse': '{names}正開著或正在編輯這個資料夾裡的檔案。刪除後，他們的分頁會顯示檔案已被刪除，之後輸入的內容無法儲存。',
  'action.forceRelease': '強制釋放鎖…',
  'forceRelease.title': '要強制釋放「{name}」的鎖嗎？',
  'forceRelease.agentText': '{holders} 正在修改這個檔案。強制釋放後，大家可以立刻編輯；agent 接下來寫入的內容若和別人的編輯重疊，會出現在「衝突」面板。',
  'forceRelease.humanText': '{holders}正在編輯這個檔案。強制釋放後，agent 可以立刻修改它。',
  'forceRelease.confirm': '強制釋放',
  'forceRelease.done': '已強制釋放「{name}」的鎖',
  'forceRelease.failed': '無法強制釋放：{message}',
  'list.sentence': '；',
} as const;
