// Device keys and pinned daemon keys on top of a KeyValueStore (IndexedDB in browsers). Every record read back is
// re-validated before use; nothing unusable is ever handed to the handshake.
import { equalBytes } from '../bytes.ts';
import { isWorkspaceId } from '../relay/routes.ts';
import {
  createDeviceKeyRecord,
  deviceKeyPairFromRecord,
  isUsableDeviceKeyRecord,
  selfTestDeviceKey,
  type CreateDeviceKeyOptions,
  type DeviceKeyPair,
  type DeviceKeyRecord,
} from './device-key.ts';
import { DAEMON_PIN_STORE, DEVICE_KEY_STORE, type KeyValueStore } from './kv.ts';

export type KeyStoreErrorCode = 'corrupt-record' | 'pin-mismatch' | 'bad-argument';

export class KeyStoreError extends Error {
  readonly code: KeyStoreErrorCode;

  constructor(code: KeyStoreErrorCode, message: string) {
    super(message);
    this.name = 'KeyStoreError';
    this.code = code;
  }
}

const RECORD_VERSION = 1;

// ---------------------------------------------------------------------------------------------------------------
// Device keys
// ---------------------------------------------------------------------------------------------------------------

type StoredDeviceKey = { v: typeof RECORD_VERSION; createdAt: number; record: DeviceKeyRecord };

export interface LoadedDeviceKey {
  readonly keyPair: DeviceKeyPair;
  readonly createdAt: number;
}

export interface LoadOrCreateResult extends LoadedDeviceKey {
  /** A new key was generated by this call. */
  readonly created: boolean;
  /**
   * An existing record was unusable (e.g. a WebKit X25519 CryptoKey that did not survive storage, or corruption)
   * and was replaced. The daemon does not know the new key: the user needs a new invite for this workspace.
   */
  readonly replacedUnusable: boolean;
}

export interface DeviceKeyStore {
  /** The key stored under `id` after re-validation and a DH self-test, or null if absent or unusable. */
  load(id: string): Promise<LoadedDeviceKey | null>;
  loadOrCreate(id: string): Promise<LoadOrCreateResult>;
  delete(id: string): Promise<void>;
}

export interface DeviceKeyStoreOptions extends CreateDeviceKeyOptions {
  subtle?: SubtleCrypto;
  now?: () => number;
}

function assertId(id: string): void {
  if (typeof id !== 'string' || id.length === 0 || id.length > 256) throw new KeyStoreError('bad-argument', 'invalid key id');
}

/**
 * Device keys by id. The web app uses one key per workspace (id = workspaceId), so a revoked key can be replaced for
 * that workspace alone. Creation uses an atomic add: two tabs racing both end up with the same stored key.
 */
export function createDeviceKeyStore(kv: KeyValueStore, options: DeviceKeyStoreOptions = {}): DeviceKeyStore {
  const subtle = options.subtle ?? globalThis.crypto.subtle;
  const now = options.now ?? Date.now;

  const tryUse = async (stored: unknown): Promise<LoadedDeviceKey | null> => {
    if (typeof stored !== 'object' || stored === null) return null;
    const s = stored as Partial<StoredDeviceKey>;
    if (s.v !== RECORD_VERSION || typeof s.createdAt !== 'number' || !isUsableDeviceKeyRecord(s.record)) return null;
    try {
      const keyPair = await deviceKeyPairFromRecord(s.record, subtle);
      await selfTestDeviceKey(keyPair);
      return { keyPair, createdAt: s.createdAt };
    } catch {
      return null;
    }
  };

  const store: DeviceKeyStore = {
    async load(id) {
      assertId(id);
      return tryUse(await kv.get(DEVICE_KEY_STORE, id));
    },
    async loadOrCreate(id) {
      assertId(id);
      const existing = await kv.get(DEVICE_KEY_STORE, id);
      const usable = existing === undefined ? null : await tryUse(existing);
      if (usable) return { ...usable, created: false, replacedUnusable: false };
      const record = await createDeviceKeyRecord(subtle, options);
      const value: StoredDeviceKey = { v: RECORD_VERSION, createdAt: now(), record };
      if (existing === undefined) {
        if (!(await kv.add(DEVICE_KEY_STORE, id, value))) {
          // Another tab won the race: use its key.
          const winner = await tryUse(await kv.get(DEVICE_KEY_STORE, id));
          if (winner) return { ...winner, created: false, replacedUnusable: false };
          throw new KeyStoreError('corrupt-record', 'stored device key is unusable');
        }
      } else {
        await kv.put(DEVICE_KEY_STORE, id, value);
      }
      // Use what storage gives back, never the in-memory original: that is what the next page load will see.
      const stored = await tryUse(await kv.get(DEVICE_KEY_STORE, id));
      if (!stored) throw new KeyStoreError('corrupt-record', `a freshly stored ${record.kind} device key does not survive storage`);
      return { ...stored, created: true, replacedUnusable: existing !== undefined };
    },
    async delete(id) {
      assertId(id);
      await kv.delete(DEVICE_KEY_STORE, id);
    },
  };
  return store;
}

// ---------------------------------------------------------------------------------------------------------------
// Pinned daemon keys
// ---------------------------------------------------------------------------------------------------------------

type StoredPin = { v: typeof RECORD_VERSION; key: Uint8Array; pinnedAt: number };

export interface DaemonPinStore {
  /** The pinned daemon key, or null if none. A stored record that fails validation throws 'corrupt-record'. */
  get(workspaceId: string): Promise<Uint8Array | null>;
  /**
   * Pins a VERIFIED daemon key (from clientConnect's onDaemonVerified). Re-pinning the same key is a no-op. A different
   * key throws 'pin-mismatch' unless `replace` is set, which is only legitimate after the key was verified against a
   * fresh invite's fingerprint (noise.md gotcha 16: never auto-accept a changed daemon key).
   */
  pin(workspaceId: string, daemonStaticKey: Uint8Array, options?: { replace?: boolean }): Promise<void>;
  delete(workspaceId: string): Promise<void>;
}

function assertWorkspace(workspaceId: string): void {
  if (!isWorkspaceId(workspaceId)) throw new KeyStoreError('bad-argument', 'invalid workspace id');
}

export function createDaemonPinStore(kv: KeyValueStore, options: { now?: () => number } = {}): DaemonPinStore {
  const now = options.now ?? Date.now;
  const read = async (workspaceId: string): Promise<Uint8Array | null> => {
    const stored = await kv.get(DAEMON_PIN_STORE, workspaceId);
    if (stored === undefined) return null;
    const s = stored as Partial<StoredPin> | null;
    if (!s || s.v !== RECORD_VERSION || !(s.key instanceof Uint8Array) || s.key.length !== 32 || typeof s.pinnedAt !== 'number') {
      throw new KeyStoreError('corrupt-record', 'stored daemon pin is malformed');
    }
    return s.key.slice();
  };
  return {
    async get(workspaceId) {
      assertWorkspace(workspaceId);
      return read(workspaceId);
    },
    async pin(workspaceId, daemonStaticKey, pinOptions = {}) {
      assertWorkspace(workspaceId);
      if (!(daemonStaticKey instanceof Uint8Array) || daemonStaticKey.length !== 32) {
        throw new KeyStoreError('bad-argument', 'daemon key must be 32 bytes');
      }
      let existing: Uint8Array | null;
      try {
        existing = await read(workspaceId);
      } catch (err) {
        // A corrupt pin may be overwritten only by an explicit replacement.
        if (!(err instanceof KeyStoreError) || !pinOptions.replace) throw err;
        existing = null;
      }
      if (existing && equalBytes(existing, daemonStaticKey)) return;
      if (existing && !pinOptions.replace) throw new KeyStoreError('pin-mismatch', 'a different daemon key is pinned for this workspace');
      const value: StoredPin = { v: RECORD_VERSION, key: daemonStaticKey.slice(), pinnedAt: now() };
      await kv.put(DAEMON_PIN_STORE, workspaceId, value);
    },
    async delete(workspaceId) {
      assertWorkspace(workspaceId);
      await kv.delete(DAEMON_PIN_STORE, workspaceId);
    },
  };
}
