import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// Namespace of the suggest feature (suggestion composer, the queue of those who may type into a session, the author's
// list). The host and members with agent access decide on suggestions to ANY session; editors suggest. English
// defines the keys; strings.zh-TW.ts holds the same keys in Traditional Chinese.
export const t = defineStrings(
  'suggest',
  {
    title: 'Suggestions',
    'empty.noSession': 'No session yet. Once someone opens a session, you can make suggestions to it here.',
    'session.label': '"{title}", opened by {owner}',

    'composer.label': 'Suggestion for "{title}", opened by {owner}',
    'composer.placeholder': 'What should the agent do? For example: add tests for this function first.',
    'composer.hint': 'A suggestion waits in the queue first. It is sent into the session only after the host or a member with agent access accepts it.',
    'composer.send': 'Send suggestion',
    'composer.shortcut': 'Ctrl + Enter to send',
    'composer.sent': 'Suggestion sent. The host or a member with agent access decides on it.',
    'composer.failed': 'Could not send the suggestion: {message}',
    'composer.exited': 'This session has ended, so it takes no more suggestions.',
    'composer.viewer': 'As a viewer you can watch sessions but cannot make suggestions.',
    'source.label': 'Attached code: {path}, lines {range}',
    'source.labelLine': 'Attached code: {path}, line {line}',
    'source.remove': 'Remove the attached code',
    'source.open': 'Open {path} at line {line}',
    'text.blank': 'Enter a suggestion.',
    'text.tooLong': 'The suggestion is too long (at most {max} characters).',
    'text.invalid': 'The suggestion contains characters that are not allowed (control characters or text-direction characters). Remove them, then send it again.',

    'queue.title': 'Suggestions waiting for your decision ({count})',
    'queue.lead': 'What others suggest for this session. A suggestion is sent into the session only after someone accepts it. The host and members with agent access can decide.',
    'queue.empty': 'No suggestions are waiting for you.',
    'queue.from': 'From {name}',
    'queue.accept': 'Accept',
    'queue.editAccept': 'Edit and accept',
    'queue.reject': 'Reject',
    'queue.editLabel': 'Edit the suggestion',
    'queue.confirmEdit': 'Accept the edited text',
    'queue.reasonLabel': 'Reason for rejecting (optional; the author sees it)',
    'queue.confirmReject': 'Confirm rejection',
    'queue.accepted': 'Accepted the suggestion from {name}. It was sent into the session.',
    'queue.rejected': 'Rejected the suggestion from {name}.',
    'queue.failed': 'Could not handle this suggestion: {message}',
    'queue.exited': 'This session has ended, so suggestions can no longer be accepted.',
    'queue.others': { one: '{count} suggestion is waiting in other sessions.', other: '{count} suggestions are waiting in other sessions.' },
    'queue.goOthers': 'Go to them',
    'queue.history': 'Handled suggestions',

    'status.pending': 'Waiting',
    'status.accepted': 'Accepted',
    'status.accepted-modified': 'Accepted with edits',
    'status.rejected': 'Rejected',
    'status.withdrawn': 'Withdrawn',

    'mine.title': 'My suggestions',
    'mine.to': 'For {target}',
    'mine.unknownSession': 'a session that no longer exists',
    'mine.edit': 'Edit',
    'mine.editLabel': 'Edit my suggestion',
    'mine.save': 'Save changes',
    'mine.withdraw': 'Withdraw',
    'mine.withdrawn': 'Suggestion withdrawn.',
    'mine.final': 'Text that was sent:',
    'mine.reason': 'Reason: {reason}',
    'mine.more': 'Show more ({count} more)',
    'mine.failed': 'Could not update the suggestion: {message}',

    // Why smurg itself closed a suggestion (nobody decided on it): Suggestion.closedReason.
    'closed.session-ended': 'The session ended.',
    'closed.author-kicked': 'Its author was removed from the workspace.',
    'closed.author-demoted': 'Its author can no longer make suggestions.',

    'notice.accepted': 'Your suggestion was accepted',
    'notice.acceptedModified': 'Your suggestion was accepted with edits',
    'notice.rejected': 'Your suggestion was rejected',
    // The rejected suggestion on its own line, then the reason.
    'notice.quote': '"{text}"',
    'notice.quoteReason': '"{text}"\nReason: {reason}',

    'send.title': 'Send the selected code to a session',
    'send.lead': '{path}, lines {range}',
    'send.leadLine': '{path}, line {line}',
    'send.target': 'Which session?',
    'send.own': 'Paste into "{title}" (Enter is not pressed for you)',
    'send.other': 'Send as a suggestion to "{title}", opened by {owner}',
    'send.none': 'No session is running.',
    'send.confirm': 'Continue',
    'send.pasted': 'Pasted into "{title}". Check it, then press Enter in the terminal to send it.',
    'send.missing': 'This session was not found. It may have ended.',
    'send.exited': 'This session has ended.',
    'send.tooLong': 'The selection is too long to paste in one go.',
    'send.viewer': 'Your role cannot make suggestions.',
    'send.failed': 'Could not paste: {message}',
    'send.suggestFailed': 'Could not send the suggestion: {message}',
    'layout.collapse': 'Collapse suggestions (more room for the terminal)',
    'layout.expand': 'Expand suggestions',
  },
  zhTW,
);
