import { defineStrings } from '../../strings/catalog.ts';
import { zhTW } from './strings.zh-TW.ts';

// The left column of the sessions view (UX §3; DESIGN §5.12 items 1–9): the inbox, the session list grouped by topic,
// the rail it folds to, and the banners above the columns.
export const t = defineStrings(
  'sidebar',
  {
    'region': 'Inbox and sessions',
    'resize': 'the inbox and the session list',

    // ---- inbox
    'inbox.title': 'Inbox',
    'inbox.counts': '{waiting} waiting, {look} to look at',
    'inbox.group.waiting': 'Agents are waiting',
    'inbox.group.look': 'For you to look at',
    'inbox.empty': 'Nothing is waiting for you.',
    'inbox.empty.viewer': 'Nothing is waiting for you. As a viewer you get only mentions here.',
    'inbox.row': '{kind}: {title}. {where}. {age}',
    'inbox.row.unread': '{kind}, new: {title}. {where}. {age}',
    'inbox.dismiss': 'Dismiss: {title}',
    'inbox.failed': 'That did not work: {reason}',
    'inbox.preview': 'Waiting for you',
    'inbox.preview.open': 'Open',
    'inbox.announce': 'New in your inbox, an agent is waiting: {title}. {where}',
    'inbox.toast': 'An agent is waiting: {title}',
    'inbox.toast.open': 'Open',

    // ---- what a row says
    'where.topic': '{topic} › {session}',
    'where.free': 'No topic › {session}',
    'fact.voted': '{voted} of {eligible} voted',
    'fact.allVoted': 'All {eligible} voted',
    'fact.submit': 'All {eligible} voted · submit “{leading}”',
    'fact.leading': 'leading: “{leading}”',
    'fact.decides': '{name} decides',
    'fact.youOr': 'you or {name}',
    'fact.youOrOthers': 'you or one of {count} others',
    'fact.notAnswered': '{name} has not answered for {time}',
    'fact.notReviewed': '{name} has not reviewed it for {time}',
    'fact.offline': '{name} is offline',
    'fact.checks': '{passed} passed · {notVerified} not verified',
    'fact.conflict': 'Conflict',
    'fact.unblocks.one': 'item {items} waits for it',
    'fact.unblocks.many': 'items {items} wait for it',
    'fact.sessionsWait': { one: '{count} session waits', other: '{count} sessions wait' },
    'title.vote': 'Vote: {question}',
    'title.suggestion': '{name}: {text}',
    'title.suggestions': '{name}: {count} suggestions',
    'title.report': 'Result report: {item}',
    'title.merge.ready': 'Reviewed, ready to merge: {what}',
    'title.merge.asks': '{name} asks to merge {what}',
    'title.merge.pending': 'Merge request: {what}',
    'title.merge.changes': 'changes of a session',
    'title.mention': '{name} mentioned you: {text}',
    'title.result.rejected': '{name} rejected your suggestion: {text}',
    'title.result.edited': '{name} accepted your suggestion with changes: {text}',
    'title.attention.itemStalled': '{item} stopped without a report',
    'title.attention.itemFailed': "{item}: the agent's process failed",
    'title.attention.itemStopped': '{item}: the session was ended',
    'title.attention.itemNotStarted': '{item} did not start',
    'title.attention.planPaused': { one: 'smurg was restarted: {count} item is paused', other: 'smurg was restarted: {count} items are paused' },
    'title.attention.discussionLost': 'The discussion of {topic} is closed',
    'title.attention.account.limit': "The host's Claude account reached a usage limit",
    'title.attention.account.loggedOut': "The host's Claude Code is logged out",
    'action.continue': 'Continue',
    'action.tryAgain': 'Try again',
    'action.continueAll': 'Continue all',
    'action.restartDiscussion': 'Restart discussion',

    // ---- sessions
    'sessions.title': 'Sessions',
    'sessions.tree': 'Sessions by topic',
    'sessions.new': 'New',
    'sessions.new.menu': 'New topic, session or terminal',
    'sessions.new.topic': 'New topic',
    'sessions.new.session': 'New session',
    'sessions.new.terminal': 'Terminal',
    'sessions.new.unavailable': 'This cannot be opened in this build of smurg.',
    'sessions.filter': 'Show',
    'sessions.filter.all': 'All',
    'sessions.filter.mine': 'Mine',
    'sessions.filter.waiting': 'Waiting',
    'sessions.empty': 'No topics yet.',
    'sessions.empty.filter': 'Nothing matches this filter.',
    'group.free': 'No topic',
    'group.archived': 'Archived: {name}',
    'group.label': '{name}, {phase}',
    'group.label.waiting': '{name}, {phase}, {count} waiting',
    'group.waiting': '{count} waiting',
    'group.menu': 'Actions for {name}',
    'group.watch': 'Watch its running sessions side by side',
    'group.more': 'More actions',
    'archived.show': 'Show archived topics',
    'archived.failed': 'The archived topics could not be loaded: {reason}',
    'row.earlier': 'Earlier discussion',
    'row.spec': 'Spec',
    'row.spec.missing': 'not written yet',
    'row.spec.draft': 'draft',
    'row.plan': 'Plan',
    'row.plan.missing': 'no plan yet',
    'row.plan.reviewed': '{reviewed} of {items} reviewed',
    'row.responsible': 'Responsible: {name}',
    'row.everyone': 'No one is responsible: everyone watches',
    'row.report.review': 'its result report waits for review',
    'row.report.reviewed': 'its result report was reviewed',
    'row.report.open': 'Open the result report',
    'row.unread': 'something happened since you last looked',
    'row.open.in': 'open in a column',
    'row.menu': 'Actions for {title}',
    'row.open': 'Open',
    'row.openSide': 'Open to the side',
    'row.openSide.hint': 'Open to the side (Shift+Enter)',

    // ---- the rail
    'rail.inbox': 'Inbox: {waiting} waiting, {look} to look at',
    'rail.sessions': 'Sessions',
    'rail.new': 'New topic',

    // ---- banners above the columns
    'restart.items': {
      one: "smurg was restarted on the host's computer. {count} item is paused.",
      other: "smurg was restarted on the host's computer. {count} items are paused.",
    },
    'restart.plans': {
      one: "smurg was restarted on the host's computer. The plan of {count} topic is paused.",
      other: "smurg was restarted on the host's computer. The plans of {count} topics are paused.",
    },
    'restart.who': 'The host or a member with agent access can continue them.',
    'restart.continue': 'Continue all',
    'restart.failed': 'Could not continue: {reason}',
    'account.limit': "The host's Claude account reached a usage limit. Agents wait until it resets.",
    'account.limit.at': "The host's Claude account reached a usage limit. Agents wait until {time}.",
    'account.loggedOut': "The host's Claude Code is logged out, so agents cannot work. Only the host can log in again.",
    'account.sessions': { one: '{count} session waits.', other: '{count} sessions wait.' },
  },
  zhTW,
);
