// zh-TW table of the `sidebar` namespace: exactly the keys of ./strings.ts (the English table defines them).
export const zhTW = {
  'region': '收件夾與 session',
  'resize': '收件夾與 session 清單',

  'inbox.title': '收件夾',
  'inbox.counts': '{waiting} 個在等，{look} 個待看',
  'inbox.group.waiting': 'agent 在等你',
  'inbox.group.look': '等你看的',
  'inbox.empty': '目前沒有等你處理的事。',
  'inbox.empty.viewer': '目前沒有等你處理的事。「旁觀」的成員在這裡只會收到提及。',
  'inbox.row': '{kind}：{title}。{where}。{age}',
  'inbox.row.unread': '{kind}，新的：{title}。{where}。{age}',
  'inbox.dismiss': '移除：{title}',
  'inbox.failed': '沒有成功：{reason}',
  'inbox.preview': '等你處理',
  'inbox.preview.open': '開啟',
  'inbox.announce': '收件夾有新項目，agent 在等：{title}。{where}',
  'inbox.toast': 'agent 在等：{title}',
  'inbox.toast.open': '開啟',

  'where.topic': '{topic} › {session}',
  'where.free': '未分主題 › {session}',
  'fact.voted': '{eligible} 人中 {voted} 人已投票',
  'fact.allVoted': '{eligible} 人都投票了',
  'fact.submit': '{eligible} 人都投票了 · 送出「{leading}」',
  'fact.leading': '領先：「{leading}」',
  'fact.decides': '由 {name} 決定',
  'fact.youOr': '你或 {name}',
  'fact.youOrOthers': '你或另外 {count} 人之一',
  'fact.notAnswered': '{name} 已經 {time} 沒有回答',
  'fact.notReviewed': '{name} 已經 {time} 沒有看',
  'fact.offline': '{name} 不在線上',
  'fact.checks': '{passed} 項通過 · {notVerified} 項未驗證',
  'fact.conflict': '衝突',
  'fact.unblocks.one': '項目 {items} 在等它',
  'fact.unblocks.many': '項目 {items} 在等它',
  'fact.sessionsWait': '{count} 個 session 在等',
  'title.vote': '投票：{question}',
  'title.suggestion': '{name}：{text}',
  'title.suggestions': '{name}：{count} 則建議',
  'title.report': '結果報告：{item}',
  'title.merge.ready': '已看過，可以合併：{what}',
  'title.merge.asks': '{name} 請求合併：{what}',
  'title.merge.pending': '合併請求：{what}',
  'title.merge.changes': '某個 session 的變更',
  'title.mention': '{name} 提到你：{text}',
  'title.result.rejected': '{name} 沒有採用你的建議：{text}',
  'title.result.edited': '{name} 修改後採用了你的建議：{text}',
  'title.attention.itemStalled': '{item} 沒寫報告就停下了',
  'title.attention.itemStalled.restart': '{item} 已暫停：smurg 重新啟動過',
  'title.attention.itemStalled.stopped': '{item} 被人停止，沒有報告',
  'title.attention.itemStalled.error': '{item} 因錯誤停止，沒有報告',
  'title.attention.itemFailed': '{item}：agent 的程序失敗了',
  'title.attention.itemStopped': '{item}：session 已被結束',
  'title.attention.itemNotStarted': '{item} 沒有開始',
  'title.attention.planPaused': 'smurg 重新啟動了：{count} 個項目已暫停',
  'title.attention.discussionLost': '「{topic}」的討論已結束',
  'title.attention.account.limit': '主人的 Claude 帳號達到用量上限',
  'title.attention.account.loggedOut': '主人的 Claude Code 已登出',
  'action.continue': '繼續',
  'action.tryAgain': '再試一次',
  'action.continueAll': '全部繼續',
  'action.restartDiscussion': '重新開始討論',

  'sessions.title': 'session',
  'sessions.tree': '依主題分組的 session',
  'sessions.new': '新增',
  'sessions.new.menu': '新增主題、session 或終端機',
  'sessions.new.topic': '新增主題',
  'sessions.new.session': '新增 session',
  'sessions.new.terminal': '終端機',
  'sessions.new.unavailable': '這個版本的 smurg 無法開啟這個功能。',
  'sessions.filter': '顯示',
  'sessions.filter.all': '全部',
  'sessions.filter.mine': '我的',
  'sessions.filter.waiting': '等待中',
  'sessions.empty': '還沒有主題。',
  'sessions.empty.filter': '沒有符合這個篩選的項目。',
  'group.free': '未分主題',
  'group.archived': '已封存：{name}',
  'group.label': '{name}，{phase}',
  'group.label.waiting': '{name}，{phase}，{count} 個在等',
  'group.waiting': '{count} 個在等',
  'group.menu': '「{name}」的操作',
  'group.watch': '並排觀看它執行中的 session',
  'group.more': '更多操作',
  'archived.show': '顯示已封存的主題',
  'archived.failed': '無法載入已封存的主題：{reason}',
  'row.earlier': '先前的討論',
  'row.spec': 'spec',
  'row.spec.missing': '還沒寫',
  'row.spec.draft': '草稿',
  'row.plan': '計畫',
  'row.plan.missing': '還沒有計畫',
  'row.plan.reviewed': '{items} 項中 {reviewed} 項已看過',
  'row.responsible': '負責人：{name}',
  'row.everyone': '沒有負責人：大家一起看',
  'row.report.review': '它的結果報告待看',
  'row.report.reviewed': '它的結果報告已看過',
  'row.report.open': '開啟結果報告',
  'row.unread': '你上次看過之後有新動態',
  'row.open.in': '已在某一欄開啟',
  'row.menu': '「{title}」的操作',
  'row.open': '開啟',
  'row.openSide': '在旁邊開啟',
  'row.openSide.hint': '在旁邊開啟（Shift+Enter）',

  'rail.inbox': '收件夾：{waiting} 個在等，{look} 個待看',
  'rail.sessions': 'session',
  'rail.new': '新增主題',

  'restart.items': '主人電腦上的 smurg 重新啟動了。{count} 個項目已暫停。',
  'restart.plans': '主人電腦上的 smurg 重新啟動了。{count} 個主題的計畫已暫停。',
  'restart.who': '主人或「可使用 agent」的成員可以讓它們繼續。',
  'restart.continue': '全部繼續',
  'restart.failed': '無法繼續：{reason}',
  'account.limit': '主人的 Claude 帳號達到用量上限。agent 會等到額度重置。',
  'account.limit.at': '主人的 Claude 帳號達到用量上限。agent 會等到 {time}。',
  'account.loggedOut': '主人的 Claude Code 已登出，agent 無法工作。只有主人可以重新登入。',
  'account.sessions': '{count} 個 session 在等。',
} as const;
