import { defineStrings } from './catalog.ts';
import { zhTW } from './app.zh-TW.ts';

// App-wide strings: landing, login, language and theme menus, errors and generic words.
export const tApp = defineStrings(
  'app',
  {
    name: 'smurg',
    tagline: 'A live workspace for people and agents',
    'landing.lead': 'Share a project folder from your own computer with your teammates: edit files together in real time, and watch and direct Claude Code together.',
    'landing.points.e2e': 'End-to-end encrypted: files, terminals and commands never pass through the smurg server in plain text.',
    'landing.points.host': "Every file and every agent session stays on the host's computer.",
    'landing.points.suggest': "Teammates without a Claude subscription still see the agent's output live and can send suggestions.",
    'landing.howToJoin.title': 'How to join a workspace',
    'landing.howToJoin.body': "Open the invite link the host gave you (https://…/join/…#k=…&s=…). The first time you join, the invite link proves the identity of the host's computer.",
    'landing.howToHost.title': 'How to share a folder',
    'landing.howToHost.body': 'On your computer, run smurg host <folder> and send the invite link it prints to your teammates.',
    'landing.recent': 'Recent workspaces',
    'landing.recent.empty': 'This browser has not opened a workspace yet.',
    'landing.recent.forget': 'Remove from the list',
    'landing.recent.lastOpened': 'Last opened: {time}',
    'landing.footer.docs': 'Docs',
    'landing.footer.docsUrl': 'https://smurg.ai/docs/',
    'landing.footer.source': 'Source code',
    'landing.footer.license': 'License',
    'landing.footer.licenseUrl': 'https://smurg.ai/license/',
    'landing.footer.notices': 'Third-party notices',

    'login.title': 'Log in',
    'login.lead': 'Log in first. smurg only uses the login to know who you are; it does not get your code or your Claude credentials.',
    'login.github': 'Log in with GitHub',
    'login.none': 'This smurg server has no login method set up yet. Contact whoever runs it.',
    'login.google': 'Log in with Google',
    'login.signedInAs': 'Logged in as {name}',
    'login.logout': 'Log out',
    'login.checking': 'Checking whether you are logged in…',
    'login.relayDown': 'Cannot reach the smurg server. Check your network and try again.',
    'login.retry': 'Retry',
    'login.dev.title': 'Development login',
    'login.dev.note': 'This server has the development login turned on (local development only).',
    'login.dev.user': 'Account name',
    'login.dev.userHint': 'Letters, digits, ".", "_" and "-"; up to 64 characters',
    'login.dev.displayName': 'Display name (optional)',
    'login.dev.submit': 'Log in with a development account',
    'login.dev.invalid': 'An account name may only contain letters, digits, ".", "_" and "-", up to 64 characters.',

    'theme.label': 'Appearance',
    'theme.system': 'Match system',
    'theme.dark': 'Dark',
    'theme.light': 'Light',

    'notFound.title': 'Page not found',
    'notFound.body': 'The address may be mistyped, or the workspace ID is wrong.',
    'notFound.home': 'Back to home',

    'error.generic': 'Something unexpected went wrong. Try again later.',
    'error.notImplemented': "smurg on the host's computer does not support this yet.",
    'error.relay': 'Cannot reach the smurg server. Try again later.',
    'error.relayStatus': 'The smurg server answered with an error ({status}).',
    'error.unauthorized': 'Your login has expired. Log in again.',

    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.retry': 'Retry',
    'common.unknown': 'Unknown',
    'common.justNow': 'just now',
  },
  zhTW,
);
