import { defineStrings } from './catalog.ts';

// App-wide strings: landing, login, errors and generic words.
export const tApp = defineStrings('app', {
  name: 'smurg',
  tagline: '多人 × 多 agent 即時協作工作區',
  'landing.lead': '把自己電腦上的專案資料夾分享給組員，一起即時編輯檔案、一起看和指揮 Claude Code。',
  'landing.points.e2e': '端對端加密：檔案、終端機與指令都不會以明文經過 smurg 的伺服器。',
  'landing.points.host': '所有檔案和 agent session 都留在主人的電腦上。',
  'landing.points.suggest': '沒有 Claude 訂閱的組員，也能即時看到 agent 的輸出並提出建議。',
  'landing.howToJoin.title': '如何加入工作區',
  'landing.howToJoin.body': '請開啟主人給你的邀請連結（https://…/join/…#k=…&s=…）。第一次加入時，邀請連結會證明主人電腦的身分。',
  'landing.howToHost.title': '如何分享資料夾',
  'landing.howToHost.body': '在你的電腦上執行 smurg host <資料夾>，把產生的邀請連結傳給組員。',
  'landing.recent': '最近開啟的工作區',
  'landing.recent.empty': '這個瀏覽器還沒有開啟過任何工作區。',
  'landing.recent.open': '開啟',
  'landing.recent.forget': '從清單移除',
  'landing.recent.lastOpened': '上次開啟：{time}',

  'login.title': '登入',
  'login.lead': '請先登入。smurg 只用登入來確認你是誰，不會取得你的程式碼或 Claude 憑證。',
  'login.github': '使用 GitHub 登入',
  'login.none': '這個 smurg 伺服器還沒有設定任何登入方式，請聯絡架設它的人。',
  'login.google': '使用 Google 登入',
  'login.signedInAs': '已登入：{name}',
  'login.logout': '登出',
  'login.checking': '正在確認登入狀態…',
  'login.relayDown': '無法連上 smurg 伺服器，請檢查網路後重試。',
  'login.retry': '重試',
  'login.dev.title': '開發用登入',
  'login.dev.note': '這個伺服器開啟了開發用登入（只在本機開發環境提供）。',
  'login.dev.user': '帳號名稱',
  'login.dev.userHint': '英數字、「.」、「_」、「-」，最多 64 個字元',
  'login.dev.displayName': '顯示名稱（選填）',
  'login.dev.submit': '以開發用帳號登入',
  'login.dev.invalid': '帳號名稱只能包含英數字、「.」、「_」、「-」，最多 64 個字元。',

  'theme.label': '外觀',
  'theme.system': '跟隨系統',
  'theme.dark': '深色',
  'theme.light': '淺色',

  'notFound.title': '找不到這個頁面',
  'notFound.body': '網址可能打錯了，或工作區 ID 不正確。',
  'notFound.home': '回到首頁',

  'error.generic': '發生未預期的錯誤，請稍後再試。',
  'error.notImplemented': '主人電腦上的 smurg 還不支援這項功能。',
  'error.relay': '無法連上 smurg 伺服器，請稍後再試。',
  'error.relayStatus': 'smurg 伺服器回應錯誤（{status}）。',
  'error.unauthorized': '你的登入已過期，請重新登入。',
  'error.boundary.title': '畫面發生錯誤',
  'error.boundary.body': '這個區塊無法顯示。你的連線和其他區塊不受影響。',
  'error.boundary.retry': '重新顯示',

  'common.cancel': '取消',
  'common.confirm': '確定',
  'common.close': '關閉',
  'common.retry': '重試',
  'common.loading': '載入中…',
  'common.unknown': '未知',
  'common.you': '你',
  'common.justNow': '剛剛',
  'common.secondsAgo': '{n} 秒前',
  'common.minutesAgo': '{n} 分鐘前',
  'common.hoursAgo': '{n} 小時前',
  'common.daysAgo': '{n} 天前',
});
