// zh-TW table of the `conn` namespace: exactly the keys of ./connection.ts (the English table defines them).
export const zhTW = {
  'pill.idle': '尚未連線',
  'pill.connecting': '連線中…',
  'pill.retrying': '重新連線中…',
  'pill.handshaking': '建立加密連線中…',
  'pill.online': '已連線',
  'pill.hostOffline': '主人已離線',
  'pill.relayUnreachable': '無法連上伺服器',
  'pill.roleChanged': '角色已變更',
  'pill.keyMismatch': '主人金鑰不符',
  'pill.rejected': '連線被拒絕',
  'pill.kicked': '已被移出',
  'pill.closed': '連線已關閉',
  'pill.loginRequired': '需要登入',

  'detail.connecting': '正在連線到 smurg 伺服器。',
  'detail.handshaking.invite': '正在用邀請連結驗證主人電腦的身分。',
  'detail.handshaking.device': '正在驗證主人電腦的身分。',
  'detail.online': '已建立端對端加密連線。',
  'detail.online.resumed': '已重新連線，並補上離線期間的訊息。',
  'detail.retry.timeout': '加密連線逾時，稍後會自動重試。',
  'detail.retry.aborted': '主人的電腦暫時無法接受連線，稍後會自動重試。',
  'detail.retry.busy': '主人的電腦忙碌中，稍後會自動重試。',
  'detail.retry.protocol': '連線發生錯誤，稍後會自動重試。',
  'detail.retry.stalled': '主人的電腦一段時間沒有回應，正在重新連線。',
  'detail.retry.generic': '連線中斷，正在重新連線。',
  'detail.roleChanged': '主人變更了你的角色，正在重新連線以套用新的權限。',
  'detail.hostOffline.relay': '主人的電腦目前離線（可能進入睡眠或網路中斷）。主人回來後會自動重新連線。',
  'detail.hostOffline.silence': '超過 8 秒沒有收到主人電腦的回應。主人回來後會自動重新連線。',
  'detail.hostOffline.stopped': '主人已停止分享這個工作區。主人重新開始分享後會自動重新連線。',
  'detail.hostOffline.consequence': '在主人回來之前，檔案修改不會被儲存，也無法操作 agent。',
  'detail.relayUnreachable': '這是你和 smurg 伺服器之間的網路問題，不是主人離線。',
  'sentences': '{first}{second}',
  'statusPrefix': '連線狀態：',
  'retryIn': '{count} 秒後重試',

  'keyMismatch.title': '安全警告：已拒絕連線',
  'keyMismatch.lead': 'smurg 伺服器（relay）交給你的「主人電腦金鑰」，和邀請連結裡記載的（或你之前信任的）金鑰不一樣。',
  'keyMismatch.refused': '為了保護你，這次連線已被拒絕：沒有任何檔案內容、終端機輸出或指令被送出。',
  'keyMismatch.causes': '這可能表示有人正在攔截連線，也可能是主人重新安裝了 smurg。在確認原因之前，請不要再嘗試連線到這個工作區。',
  'keyMismatch.whatToDo': '接下來請這樣做',
  'keyMismatch.step1': '透過其他管道聯絡主人，例如當面、打電話，或你們平常使用的通訊軟體（不要只依賴這個網站）。',
  'keyMismatch.step2': '請主人產生一個新的邀請連結，並用同樣的管道傳給你。',
  'keyMismatch.step3': '用新的邀請連結重新加入。',
  'keyMismatch.technical': '技術資訊：{detail}（{mode}）',
  'keyMismatch.detail.fingerprint': '主人金鑰的指紋不符',
  'keyMismatch.detail.unauthenticated': '對方無法證明持有主人金鑰',
  'keyMismatch.mode.invite': '首次加入',
  'keyMismatch.mode.device': '重新連線',

  'rejected.invite-invalid.title': '邀請連結無法使用',
  'rejected.invite-invalid.body': '這個邀請連結已過期、已用完次數，或已被主人撤銷。請向主人索取新的邀請連結。',
  'rejected.aborted.title': '邀請連結無法使用',
  'rejected.aborted.body': '主人的電腦不認得這個邀請連結（可能已過期、已用完或已被撤銷）。請向主人索取新的邀請連結。',
  'rejected.device-revoked.title': '這個裝置已無法連線',
  'rejected.device-revoked.body': '主人的電腦不再接受這個瀏覽器的裝置金鑰（例如你曾被移出工作區，或瀏覽器的金鑰已遺失）。請向主人索取新的邀請連結。',
  'rejected.device-other-account.title': '這個瀏覽器已經用另一個帳號加入過',
  'rejected.device-other-account.body':
    '這個瀏覽器先前用另一個帳號加入了這個工作區，所以不能改用現在登入的帳號連線。請登出後改用原本的帳號登入；如果要用現在的帳號，請改用另一個瀏覽器設定檔或無痕視窗開啟邀請連結。',
  'rejected.identity-invalid.title': '無法確認你的登入身分',
  'rejected.identity-invalid.body': '主人的電腦無法驗證你的登入資訊。請重新整理頁面；若問題持續，請登出後重新登入。',
  'rejected.kicked.title': '你已被移出工作區',
  'rejected.kicked.body': '主人已將你移出這個工作區。若需要再次加入，請向主人索取新的邀請連結。',
  'rejected.version.title': '版本不相容',
  'rejected.version.body': '這個網頁和主人電腦上的 smurg 版本不相容。請重新整理頁面；若問題持續，請主人更新 smurg。',
  'rejected.unknown.title': '主人拒絕了這次連線',
  'rejected.unknown.body': '主人的電腦拒絕了這次連線，但沒有說明原因。請稍後再試，或聯絡主人。',

  'closed.local.title': '連線已關閉',
  'closed.local.body': '你已離開這個工作區。',
  'closed.kicked.title': '你已被移出工作區',
  'closed.kicked.body': '主人已將你移出這個工作區，你開的 session 也已結束。若需要再次加入，請向主人索取新的邀請連結。',
  'closed.revoked.title': '這個裝置已被撤銷',
  'closed.revoked.body': '主人撤銷了這個瀏覽器的裝置金鑰。若需要再次加入，請向主人索取新的邀請連結。',
  'closed.login-required.title': '請重新登入',
  'closed.login-required.body': '你的登入已過期或尚未登入。登入後會自動回到這個工作區。',
  'closed.relay-refused.title': 'smurg 伺服器拒絕了連線',
  'closed.relay-refused.body': '伺服器拒絕了這個請求。請確認你開啟的是主人給你的網址。',
  'closed.no-trust.title': '這個瀏覽器還沒有加入這個工作區',
  'closed.no-trust.body': '請使用主人給你的邀請連結加入。邀請連結的格式是 https://…/join/…#k=…&s=…；請整段複製貼上，不要只複製「#」之前的部分。',
  'closed.storage-error.title': '無法讀寫裝置金鑰',
  'closed.storage-error.body': '瀏覽器無法使用這個網站的儲存空間（IndexedDB）。請確認沒有封鎖網站資料，或改用一般（非私密）視窗。',

  'action.home': '回到首頁',
  'action.reload': '重新整理頁面',
  'action.reconnect': '重新連線',

  'toast.roleChanged': '你的角色已變更為「{role}」',
  'toast.resynced': '已重新連線，畫面已重新載入最新狀態',
  'banner.memoryKeys': '這個瀏覽器無法儲存裝置金鑰（可能是私密瀏覽模式）。關閉分頁後，需要新的邀請連結才能再次加入。',
} as const;
