import { defineStrings } from './catalog.ts';
import { zhTW } from './connection.zh-TW.ts';

// Connection states as the UI names them (ARCHITECTURE §4 "Client states"). "Cannot reach the server" and "Host
// offline" are deliberately different messages: one is the person's own network or our server, the other the host's
// laptop.
export const tConn = defineStrings(
  'conn',
  {
    'pill.idle': 'Not connected',
    'pill.connecting': 'Connecting…',
    'pill.retrying': 'Reconnecting…',
    'pill.handshaking': 'Securing…',
    'pill.online': 'Connected',
    'pill.hostOffline': 'Host offline',
    'pill.relayUnreachable': 'Server unreachable',
    'pill.roleChanged': 'Role changed',
    'pill.keyMismatch': 'Host key mismatch',
    'pill.rejected': 'Refused',
    'pill.kicked': 'Removed',
    'pill.closed': 'Closed',
    'pill.loginRequired': 'Login needed',

    'detail.connecting': 'Connecting to the smurg server.',
    'detail.handshaking.invite': "Verifying the identity of the host's computer with the invite link.",
    'detail.handshaking.device': "Verifying the identity of the host's computer.",
    'detail.online': 'The end-to-end encrypted connection is up.',
    'detail.online.resumed': 'Reconnected, and caught up on what you missed while offline.',
    'detail.retry.timeout': 'The encrypted connection timed out. It will retry automatically.',
    'detail.retry.aborted': "The host's computer cannot accept the connection right now. It will retry automatically.",
    'detail.retry.busy': "The host's computer is busy. It will retry automatically.",
    'detail.retry.protocol': 'The connection hit an error. It will retry automatically.',
    'detail.retry.stalled': "The host's computer has not answered for a while. Reconnecting.",
    'detail.retry.generic': 'The connection dropped. Reconnecting.',
    'detail.roleChanged': 'The host changed your role. Reconnecting to apply the new permissions.',
    'detail.hostOffline.relay': "The host's computer is offline (it may be asleep or off the network). You will reconnect automatically when the host is back.",
    'detail.hostOffline.silence': "The host's computer has not answered for more than 8 seconds. You will reconnect automatically when the host is back.",
    'detail.hostOffline.stopped': 'The host stopped sharing this workspace. You will reconnect automatically when the host shares it again.',
    'detail.hostOffline.consequence': 'Until the host is back, file changes are not saved and agents cannot be used.',
    'detail.relayUnreachable': 'This is a network problem between you and the smurg server; the host is not offline.',
    // Two whole sentences shown one after the other: each language decides what goes between them.
    'sentences': '{first} {second}',
    'statusPrefix': 'Connection status: ',
    'retryIn': { one: 'Retrying in {count} second.', other: 'Retrying in {count} seconds.' },

    'keyMismatch.title': 'Security warning: connection refused',
    'keyMismatch.lead': "The host computer's key that the smurg server (relay) handed you is not the one recorded in the invite link (or the one you trusted before).",
    'keyMismatch.refused': 'To protect you, this connection was refused: no file content, terminal output or command was sent.',
    'keyMismatch.causes': 'Someone may be intercepting the connection, or the host may have reinstalled smurg. Do not try to connect to this workspace again until you know which.',
    'keyMismatch.whatToDo': 'What to do next',
    'keyMismatch.step1': 'Contact the host some other way: in person, by phone, or in the chat app you normally use (do not rely on this website alone).',
    'keyMismatch.step2': 'Ask the host to make a new invite link and send it to you the same way.',
    'keyMismatch.step3': 'Join again with the new invite link.',
    'keyMismatch.technical': 'Technical details: {detail} ({mode})',
    'keyMismatch.detail.fingerprint': "the fingerprint of the host's key does not match",
    'keyMismatch.detail.unauthenticated': "the other side could not prove it holds the host's key",
    'keyMismatch.mode.invite': 'first join',
    'keyMismatch.mode.device': 'reconnect',

    'rejected.invite-invalid.title': 'This invite link cannot be used',
    'rejected.invite-invalid.body': 'This invite link has expired, has been used up, or was revoked by the host. Ask the host for a new invite link.',
    'rejected.aborted.title': 'This invite link cannot be used',
    'rejected.aborted.body': "The host's computer does not recognize this invite link (it may have expired, been used up or been revoked). Ask the host for a new invite link.",
    'rejected.device-revoked.title': 'This device can no longer connect',
    'rejected.device-revoked.body': "The host's computer no longer accepts this browser's device key (for example because you were removed from the workspace, or the browser lost its key). Ask the host for a new invite link.",
    'rejected.device-other-account.title': 'This browser already joined with another account',
    'rejected.device-other-account.body':
      'This browser joined this workspace earlier with another account, so it cannot connect with the account that is logged in now. Log out and log in with the original account; to use the current account, open the invite link in another browser profile or a private window.',
    'rejected.identity-invalid.title': 'Your login could not be verified',
    'rejected.identity-invalid.body': "The host's computer could not verify your login. Reload the page; if it keeps happening, log out and log in again.",
    'rejected.kicked.title': 'You were removed from the workspace',
    'rejected.kicked.body': 'The host removed you from this workspace. To join again, ask the host for a new invite link.',
    'rejected.version.title': 'Incompatible versions',
    'rejected.version.body': "This page and smurg on the host's computer are not compatible. Reload the page; if it keeps happening, ask the host to update smurg.",
    'rejected.unknown.title': 'The host refused this connection',
    'rejected.unknown.body': "The host's computer refused this connection without giving a reason. Try again later, or contact the host.",

    'closed.local.title': 'Connection closed',
    'closed.local.body': 'You left this workspace.',
    'closed.kicked.title': 'You were removed from the workspace',
    'closed.kicked.body': 'The host removed you from this workspace, and the sessions you opened have ended. To join again, ask the host for a new invite link.',
    'closed.revoked.title': 'This device was revoked',
    'closed.revoked.body': "The host revoked this browser's device key. To join again, ask the host for a new invite link.",
    'closed.login-required.title': 'Log in again',
    'closed.login-required.body': 'Your login has expired, or you are not logged in. After you log in you come back to this workspace automatically.',
    'closed.relay-refused.title': 'The smurg server refused the connection',
    'closed.relay-refused.body': 'The server refused this request. Check that you opened the address the host gave you.',
    'closed.no-trust.title': 'This browser has not joined this workspace yet',
    'closed.no-trust.body': 'Join with the invite link the host gave you. An invite link looks like https://…/join/…#k=…&s=…; copy and paste all of it, not only the part before the "#".',
    'closed.storage-error.title': 'Cannot read or write the device key',
    'closed.storage-error.body': "The browser cannot use this site's storage (IndexedDB). Check that site data is not blocked, or use a normal (not private) window.",

    'action.home': 'Back to home',
    'action.reload': 'Reload the page',
    'action.reconnect': 'Reconnect',

    'toast.roleChanged': 'Your role is now {role}',
    'toast.resynced': 'Reconnected: the page now shows the latest state',
    'banner.memoryKeys': 'This browser cannot keep the device key (it may be in private browsing mode). After you close the tab you need a new invite link to join again.',
  },
  zhTW,
);
