// zh-TW table of the `join` namespace: exactly the keys of ./join.ts (the English table defines them).
export const zhTW = {
  title: '加入工作區',
  'reading': '正在讀取邀請連結…',
  'invalid.title': '邀請連結格式不正確',
  'invalid.body': '這個邀請連結不完整或被修改過，因此無法使用。請向主人索取新的邀請連結，並完整複製整段網址（包括「#」之後的部分）。',
  'missing.title': '邀請連結不完整',
  'missing.body': '網址裡少了「#k=…&s=…」這一段，所以無法確認主人的身分。有些通訊軟體會截斷連結：請完整複製主人給你的整段網址，再開啟一次。',
  'storageMemory': '這個瀏覽器不允許網站暫存資料，登入後需要再開啟一次邀請連結。',
  'login.title': '登入後加入工作區',
  'login.body': '登入後會自動回到這裡繼續加入。邀請連結的祕密資訊只留在這個分頁，不會送到任何伺服器。',
  'connecting.title': '正在加入工作區',
  'connecting.hostOffline': '主人的電腦目前離線。主人上線後會自動繼續加入，請保持這個分頁開啟。',
  'keyChange.title': '主人的電腦金鑰和之前不同',
  'keyChange.lead': '你之前加入過這個工作區，當時主人電腦的金鑰和這個邀請連結記載的不一樣。',
  'keyChange.reason': '這通常是因為主人重新安裝了 smurg；但也可能是有人想冒充主人。',
  'keyChange.ask': '只有在你已經透過其他管道（當面、電話或你們平常使用的通訊軟體）向主人確認，這個新連結確實是主人剛剛給你的，才繼續。',
  'keyChange.confirm': '我已向主人確認，使用新的連結',
  'keyChange.cancel': '取消',
  'confirm.title': '要加入這個工作區嗎？',
  'confirm.lead': '你開啟了一個 smurg 邀請連結。這個連結是別人給你的（也可能是某個網頁把你帶到這裡）。',
  'confirm.workspace': '工作區代碼',
  'confirm.identity': '你的身分',
  'confirm.identityValue': '{name}（{provider}）',
  'confirm.providerDev': '開發用帳號',
  'confirm.shared': '加入後，這個工作區的主人會看到你的名稱、帳號和裝置名稱，你也會成為這個工作區的成員。',
  'confirm.ask': '只有在你認得這個邀請、確實想加入時，才按「加入」。',
  'confirm.join': '加入',
  'confirm.cancel': '不要加入',
  'done': '已加入，正在開啟工作區…',
} as const;
