import { defineStrings } from './catalog.ts';
import { zhTW } from './stores.zh-TW.ts';

// Text produced by the shared stores (src/lib/stores) rather than by a feature.
export const tStores = defineStrings(
  'stores',
  {
    'docs.bufferOverflow': 'Too much sync data piled up for this file. Close it and open it again.',
    'area.files': 'Files',
    'area.locks': 'File locks',
    'area.docs': 'Open files',
    'area.sessions': 'Sessions',
    'area.suggestions': 'Suggestions',
    'area.topics': 'Topics and plans',
    'area.inbox': 'Inbox',
    'area.conversations': 'Conversations',
    'area.host': "The host's Claude account",
    'area.activity': 'Activity',
    'area.conflicts': 'Conflicts',
    'area.worktrees': 'Worktrees',
    'area.admin': 'Host console data',
    'area.presence': 'Online members',
    'area.workspace': 'Workspace',
    'area.transfers': 'Transfers',
    // A session nobody gave a title, where the sentence already names who opened it. (The full default title,
    // "Terminal (Ian)", is the wire catalogue's `session.title.*`: one wording for the web app and the CLI.)
    'session.kind.agent': 'Claude',
    'session.kind.terminal': 'Terminal',
    // What a session or a work item is doing (ui/StatusGlyph; lib/session-status.ts).
    'status.running': 'Running',
    'status.question': 'Waiting for an answer',
    'status.permission': 'Waiting for permission',
    'status.stalled': 'Stopped without a report',
    'status.idle': 'Idle',
    'status.done': 'Done',
    'status.failed': 'Failed',
    'status.ended': 'Ended',
    'status.blocked': 'Waiting for another item',
    'status.todo': 'Not started',
    // The phases of a topic.
    'phase.discussing': 'Discussing',
    'phase.spec': 'Spec',
    'phase.plan': 'Plan',
    'phase.executing': 'Executing',
    'phase.complete': 'Complete',
    // The kinds of things that wait for a person (inbox items and cards; ui/KindIcon).
    'kind.question': 'Question',
    'kind.vote': 'Open vote',
    'kind.permission': 'Permission request',
    'kind.attention': 'Stopped: needs someone',
    'kind.suggestion': 'Suggestion',
    'kind.report': 'Report to review',
    'kind.merge': 'Merge request',
    'kind.mention': 'Mention',
    'kind.result': 'What happened to your suggestion',
    // What a column of the sessions view shows (lib/columns/describe.ts), and a work item's name.
    'item.label': '{number} · {title}',
    'column.session': 'Session',
    'column.spec': 'Spec',
    'column.plan': 'Plan',
    'column.report': 'Result report',
    'column.reportOf': 'Result report: {item}',
    'column.changes': 'Changes',
    'column.changesOf': 'Changes: {branch}',
    'worktree.mine': 'My worktree',
    'worktree.of': "{owner}'s worktree",
    'worktree.named': '{who} ({name})',
    'worktree.since': '{who} (created {time})',
  },
  zhTW,
);
