// zh-TW table of the `stores` namespace: exactly the keys of ./stores.ts (the English table defines them).
export const zhTW = {
  'docs.bufferOverflow': '這個檔案累積了太多尚未處理的同步資料，請關閉後重新開啟。',
  'area.files': '檔案',
  'area.locks': '檔案鎖',
  'area.docs': '開啟中的檔案',
  'area.sessions': 'session',
  'area.suggestions': '建議',
  'area.topics': '主題與計畫',
  'area.inbox': '收件夾',
  'area.conversations': '對話',
  'area.host': '主人的 Claude 帳號',
  'area.activity': '活動動態',
  'area.conflicts': '衝突',
  'area.worktrees': 'worktree',
  'area.admin': '主人控制台資料',
  'area.presence': '線上成員',
  'area.workspace': '工作區',
  'area.transfers': '傳輸',
  'session.kind.agent': 'Claude',
  'session.kind.terminal': '終端機',
  'status.running': '執行中',
  'status.question': '等待回答',
  'status.permission': '等待許可',
  'status.stalled': '沒寫報告就停下了',
  'status.idle': '待命',
  'status.done': '完成',
  'status.failed': '失敗',
  'status.ended': '已結束',
  'status.blocked': '等待其他項目',
  'status.todo': '尚未開始',
  'phase.discussing': '討論中',
  'phase.spec': 'spec',
  'phase.plan': '計畫',
  'phase.executing': '執行中',
  'phase.complete': '已完成',
  'kind.question': '選擇題',
  'kind.vote': '還沒投的票',
  'kind.permission': '權限請求',
  'kind.attention': '停住了：需要有人處理',
  'kind.suggestion': '建議',
  'kind.report': '待看的結果報告',
  'kind.merge': '合併請求',
  'kind.mention': '提及',
  'kind.result': '你的建議的結果',
  'item.label': '{number} · {title}',
  'column.session': 'session',
  'column.spec': 'spec',
  'column.plan': '計畫',
  'column.report': '結果報告',
  'column.reportOf': '結果報告：{item}',
  'column.changes': '變更',
  'column.changesOf': '變更：{branch}',
  'worktree.mine': '我的 worktree',
  'worktree.of': '{owner} 的 worktree',
  'worktree.named': '{who}（{name}）',
  'worktree.since': '{who}（{time} 建立）',
} as const;
