// zh-TW table of the `ui` namespace: exactly the keys of ./ui.ts (the English table defines them).
export const zhTW = {
  'dialog.close': '關閉對話框',
  'toast.region': '通知',
  'toast.dismiss': '關閉這則通知',
  'split.resize': '拖曳或用方向鍵調整「{name}」的大小',
  'language.label': '語言',
  'spinner.loading': '載入中',
  'drawer.expand': '展開「{name}」',
  'drawer.collapse': '收合「{name}」',
  'avatar.online': '{name}（在線上）',
  'avatar.offline': '{name}（離線）',
  'avatar.agent': '{name}（agent）',
  'avatar.more': '還有 {count} 位',
  'table.empty': '沒有資料',
  'boundary.error': '「{name}」無法顯示',
  'boundary.errorBody': '頁面的這個部分發生錯誤。連線和其他部分不受影響。',
  'boundary.retry': '重新顯示',
  'columns.resize': '拖曳或用方向鍵調整「{name}」的寬度',
  'columns.more': '還有 {count} 欄',
  'copy.done': '已複製',
  'copy.failed': '無法複製，請手動選取文字',
} as const;
