// zh-TW table of the `ui` namespace: exactly the keys of ./ui.ts (the English table defines them).
export const zhTW = {
  'dialog.close': '關閉對話框',
  'toast.region': '通知',
  'toast.dismiss': '關閉這則通知',
  'split.resize': '拖曳或用方向鍵調整「{name}」的大小',
  'language.label': '語言',
  'spinner.loading': '載入中',
  'drawer.expand': '展開「{name}」',
  'drawer.collapse': '收合「{name}」',
  'avatar.online': '{name}（在線上）',
  'avatar.offline': '{name}（離線）',
  'avatar.agent': '{name}（agent）',
  'avatar.more': '還有 {count} 位',
  'table.empty': '沒有資料',
  'boundary.error': '「{name}」無法顯示',
  'boundary.errorBody': '頁面的這個部分發生錯誤。連線和其他部分不受影響。',
  'boundary.retry': '重新顯示',
  'chunk.gone.title': 'smurg 已經更新',
  'chunk.gone.body': '重新整理頁面就會換成新的網頁；如果主人還沒更新，頁面會告訴你。',
  'chunk.offline.title': '頁面的這個部分載入不了',
  'chunk.offline.body': '瀏覽器離線了，或連不上 smurg 伺服器。網路恢復後，請重新整理頁面。',
  'chunk.failed.title': '頁面的這個部分載入不了',
  'chunk.failed.body': '請重新整理頁面，再載入一次。',
  'chunk.reload': '重新整理頁面',
  'page.crashed.title': '這個頁面無法繼續運作',
  'page.crashed.body': '頁面發生錯誤。請重新整理頁面再繼續。',
  'columns.resize': '拖曳或用方向鍵調整「{name}」的寬度',
  'columns.more': '還有 {count} 欄',
  'copy.done': '已複製',
  'copy.failed': '無法複製，請手動選取文字',
} as const;
