// zh-TW table of the `workbench` namespace: exactly the keys of ./workbench.ts (the English table defines them).
export const zhTW = {
  'skip': '跳到主要內容',
  'region.files': '檔案',
  'region.editor': '編輯器',
  'region.session': '編輯器旁的 session',
  'region.drawer': '動態、傳輸與終端機',
  'tab.activity': '活動',
  'tab.conflicts': '衝突',
  'tab.transfers': '傳輸',
  'tab.terminal': '終端機',
  'topbar.label': '工作區',
  'topbar.host': '主人：{name}',
  'topbar.rolePrefix': '你的角色：',
  'topbar.members': '線上成員',
  'topbar.console': '主人控制台',
  'topbar.togglePanels': '版面',
  'topbar.toggleLeft': '顯示或隱藏收件夾與 session 清單',
  'topbar.toggleSidebar': '顯示或隱藏檔案',
  'topbar.toggleSide': '顯示或隱藏編輯器旁的 session',
  'topbar.toggleDrawer': '顯示或隱藏動態、傳輸與終端機',
  'topbar.leave': '離開',
  'topbar.more': '更多選項',
  'mode.label': '模式',
  'mode.sessions': 'session',
  'mode.sessions.title': 'session：對話、計畫、spec 與結果報告',
  'mode.sessions.counts': 'session：{waiting} 個在等，{look} 個待看',
  'mode.code': '手寫 code 模式',
  'mode.code.title': '手寫 code 模式：檔案、編輯器與終端機',
  'mode.code.conflicts': '手寫 code 模式：{count} 個未處理的衝突',
  'title.waiting': '（{count} 個在等）{title}',
  'leave.title': '離開這個工作區？',
  'leave.body': '你開的終端機和未分主題的 session 會結束。你開始的主題 session（討論和工作項目）改由主人接手，並繼續執行。你設定的東西會移除：你設為一律允許的指令類型、你開始但還沒啟動的工作項目、你放寬的權限模式，以及你還在等 agent 讀取的訊息。之後仍可以用這個瀏覽器重新連線。',
  'leave.bodyHost': '你是主人：離開只會關閉這個分頁的連線，不會停止分享。要停止分享，請在主人電腦的終端機執行 smurg stop。',
  'leave.confirm': '離開',
  'leave.failed': '離開時發生問題：{reason}',
  'connecting.title': '正在連線到工作區',
  'notify.title': '{name} 通知你',
  'error.area': '{area}：{message}',
  'console.title': '主人控制台',
  'console.notHost.title': '只有主人可以使用控制台',
  'console.notHost.body': '主人控制台可以邀請成員、變更角色、踢人和查看操作紀錄。',
  'console.back': '回到 session 畫面',
  'empty.first.title': '從一個主題開始',
  'empty.first.body': '主題是一項功能或一件工作。大家一起和 agent 討論，agent 寫出 spec 和計畫，各個工作項目再並行執行。',
  'empty.first.step': '步驟 {number}',
  'empty.first.discuss': '討論',
  'empty.first.discuss.body': '大家一起和 agent 對話。agent 會出選擇題，由你們投票。',
  'empty.first.spec': 'spec',
  'empty.first.spec.body': 'agent 寫出 spec。大家一起編輯，或請 agent 修改。',
  'empty.first.plan': '計畫',
  'empty.first.plan.body': 'agent 把工作拆成項目，並建議誰負責哪些。',
  'empty.first.execute': '執行與檢視',
  'empty.first.execute.body': '每個項目一個 session。讀它的結果報告，然後標記為已看過。',
  'empty.first.new': '新增主題',
  'empty.first.session': '或是開一個不屬於主題的 session',
  'empty.first.watch': '主人或「可使用 agent」的成員開始主題之後，它會出現在左邊。',
  'empty.unavailable': '這個版本的 smurg 無法開啟這個功能。',
  'empty.open.title': '目前沒有開啟任何東西',
  'empty.open.body': '點左邊的 session、spec、計畫或收件夾項目，就會在這裡開啟。Shift+點擊（或 Shift+Enter）會在旁邊開啟，最多四欄。',
  'code.origin': '從「{session}」開啟',
  'code.origin.plain': '從 session 畫面開啟',
  'code.back': '回到這個 session',
  'notice.started': '有新主題開始了：{name}',
  'notice.spec-ready': '{name}：spec 初稿好了',
  'notice.plan-ready': '{name}：計畫好了',
  'notice.plan-updated': '{name}：計畫更新了',
  'notice.complete': '{name}：所有項目都看過了，主題已完成。',
  'notice.open': '開啟',
} as const;
