import { defineStrings } from './catalog.ts';

// The workbench layout (/w/:workspaceId) and the console shell.
export const tWorkbench = defineStrings('workbench', {
  'skip': '跳到主要內容',
  'region.files': '檔案',
  'region.editor': '編輯器',
  'region.agents': 'agent',
  'region.suggestions': '建議',
  'region.drawer': '動態與傳輸',
  'tab.activity': '活動',
  'tab.conflicts': '衝突',
  'tab.transfers': '傳輸',
  'tab.mergeRequests': '合併請求',
  'topbar.label': '工作區',
  'topbar.host': '主人：{name}',
  'topbar.role': '你的角色：{role}',
  'topbar.rolePrefix': '你的角色：',
  'topbar.members': '線上成員',
  'topbar.connection': '連線狀態：{status}',
  'topbar.console': '主人控制台',
  'topbar.workbench': '回到工作區',
  'topbar.togglePanels': '版面',
  'topbar.toggleSidebar': '顯示或隱藏檔案',
  'topbar.toggleRight': '顯示或隱藏 agent 與建議',
  'topbar.toggleDrawer': '顯示或隱藏動態與傳輸',
  'topbar.leave': '離開',
  'topbar.more': '更多選項',
  'leave.title': '離開這個工作區？',
  'leave.body': '你在這個工作區開的 session 會結束。之後仍可以用這個瀏覽器重新連線。',
  'leave.bodyHost': '你是主人：離開只會關閉這個分頁的連線，不會停止分享。要停止分享，請在主人電腦的終端機執行 smurg stop。',
  'leave.confirm': '離開',
  'leave.failed': '離開時發生問題：{reason}',
  'connecting.title': '正在連線到工作區',
  'connecting.firstTime': '第一次連線可能需要幾秒鐘。',
  'hostOffline.title': '主人已離線',
  'notify.title': '{name} 通知你',
  'error.area': '{area}：{message}',
  'console.title': '主人控制台',
  'console.notHost.title': '只有主人可以使用控制台',
  'console.notHost.body': '主人控制台可以邀請成員、變更角色、踢人和查看操作紀錄。',
  'slot.error': '「{name}」無法顯示',
  'slot.errorBody': '這個區塊發生錯誤。連線和其他區塊不受影響。',
  'slot.retry': '重新顯示',
});
