import { defineStrings } from './catalog.ts';
import { zhTW } from './workbench.zh-TW.ts';

// The workspace shell (/w/:workspaceId): the top bar with the mode switch, the sessions view around its columns, code
// mode's layout, and the console shell.
export const tWorkbench = defineStrings(
  'workbench',
  {
    'skip': 'Skip to main content',
    'region.files': 'Files',
    'region.editor': 'Editor',
    'region.session': 'Session beside the editor',
    'region.drawer': 'Activity, transfers and terminal',
    'tab.activity': 'Activity',
    'tab.conflicts': 'Conflicts',
    'tab.transfers': 'Transfers',
    'tab.terminal': 'Terminal',
    'topbar.label': 'Workspace',
    'topbar.host': 'Host: {name}',
    'topbar.rolePrefix': 'Your role: ',
    'topbar.members': 'Online members',
    'topbar.console': 'Host console',
    'topbar.togglePanels': 'Layout',
    'topbar.toggleLeft': 'Show or hide the inbox and the session list',
    'topbar.toggleSidebar': 'Show or hide files',
    'topbar.toggleSide': 'Show or hide the session beside the editor',
    'topbar.toggleDrawer': 'Show or hide activity, transfers and terminal',
    'topbar.leave': 'Leave',
    'topbar.more': 'More options',
    'mode.label': 'Mode',
    'mode.sessions': 'Sessions',
    'mode.sessions.title': 'Sessions: conversations, plans, specs and reports',
    'mode.sessions.counts': 'Sessions: {waiting} waiting, {look} to look at',
    'mode.code': 'Code mode',
    'mode.code.title': 'Code mode: files, editor and terminal',
    'mode.code.conflicts': { one: 'Code mode: {count} open conflict', other: 'Code mode: {count} open conflicts' },
    'title.waiting': '({count} waiting) {title}',
    'leave.title': 'Leave this workspace?',
    'leave.body': 'The terminals and the sessions without a topic that you opened end. The topic sessions you started (discussions and work items) pass to the host and keep running. What you put in place is removed: the kinds of commands you always allowed, the work items you started that have not begun, a permission mode you loosened, and your messages that still wait for an agent. You can reconnect later with this browser.',
    'leave.bodyHost': "You are the host: leaving only closes this tab's connection and does not stop sharing. To stop sharing, run smurg stop in a terminal on the host computer.",
    'leave.confirm': 'Leave',
    'leave.failed': 'Something went wrong while leaving: {reason}',
    'connecting.title': 'Connecting to the workspace',
    'notify.title': 'Notification from {name}',
    'error.area': '{area}: {message}',
    'console.title': 'Host console',
    'console.notHost.title': 'Only the host can use the console',
    'console.notHost.body': 'In the host console the host invites members, changes roles, removes members and reads the audit log.',
    'console.back': 'Back to the sessions',
    // The right side of the sessions view while no column is open (UX §12).
    'empty.first.title': 'Start with a topic',
    'empty.first.body': 'A topic is a feature or a task. Everyone discusses it with the agent, the agent writes a spec and a plan, and the work items run side by side.',
    'empty.first.step': 'Step {number}',
    'empty.first.discuss': 'Discuss',
    'empty.first.discuss.body': 'Everyone talks with the agent. It asks multiple-choice questions and you vote.',
    'empty.first.spec': 'Spec',
    'empty.first.spec.body': 'The agent writes the spec. Edit it together or ask for changes.',
    'empty.first.plan': 'Plan',
    'empty.first.plan.body': 'The agent splits the work into items and suggests who is responsible.',
    'empty.first.execute': 'Execute and review',
    'empty.first.execute.body': 'One session per item. Read its result report and mark it reviewed.',
    'empty.first.new': 'New topic',
    'empty.first.session': 'or open a single session without a topic',
    'empty.first.watch': 'When the host or a member with agent access starts a topic, it appears on the left.',
    'empty.unavailable': 'This cannot be opened in this build of smurg.',
    'empty.open.title': 'Nothing is open',
    'empty.open.body': 'Click a session, a spec, a plan or an inbox item on the left to open it here. Shift+click (or Shift+Enter) opens it to the side; up to four columns fit.',
    // Code mode: where "Open in editor" came from.
    'code.origin': 'Opened from {session}',
    'code.origin.plain': 'Opened from the sessions view',
    'code.back': 'Back to the session',
    // What a change of a topic tells everyone.
    'notice.started': 'A new topic was started: {name}',
    'notice.spec-ready': '{name}: the spec draft is ready',
    'notice.plan-ready': '{name}: the plan is ready',
    'notice.plan-updated': '{name}: the plan was updated',
    'notice.complete': '{name}: every item is reviewed. The topic is complete.',
    'notice.open': 'Open',
  },
  zhTW,
);
