import { defineStrings } from './catalog.ts';
import { zhTW } from './workbench.zh-TW.ts';

// The workbench layout (/w/:workspaceId) and the console shell.
export const tWorkbench = defineStrings(
  'workbench',
  {
    'skip': 'Skip to main content',
    'region.files': 'Files',
    'region.editor': 'Editor',
    'region.agents': 'Agents',
    'region.suggestions': 'Suggestions',
    'region.drawer': 'Activity and transfers',
    'tab.activity': 'Activity',
    'tab.conflicts': 'Conflicts',
    'tab.transfers': 'Transfers',
    'tab.mergeRequests': 'Merge requests',
    'topbar.label': 'Workspace',
    'topbar.host': 'Host: {name}',
    'topbar.rolePrefix': 'Your role: ',
    'topbar.members': 'Online members',
    'topbar.console': 'Host console',
    'topbar.workbench': 'Back to workspace',
    'topbar.togglePanels': 'Layout',
    'topbar.toggleSidebar': 'Show or hide files',
    'topbar.toggleRight': 'Show or hide agents and suggestions',
    'topbar.toggleDrawer': 'Show or hide activity and transfers',
    'topbar.leave': 'Leave',
    'topbar.more': 'More options',
    'leave.title': 'Leave this workspace?',
    'leave.body': 'The sessions you opened in this workspace will end. You can reconnect later with this browser.',
    'leave.bodyHost': "You are the host: leaving only closes this tab's connection and does not stop sharing. To stop sharing, run smurg stop in a terminal on the host computer.",
    'leave.confirm': 'Leave',
    'leave.failed': 'Something went wrong while leaving: {reason}',
    'connecting.title': 'Connecting to the workspace',
    'notify.title': 'Notification from {name}',
    'error.area': '{area}: {message}',
    'console.title': 'Host console',
    'console.notHost.title': 'Only the host can use the console',
    'console.notHost.body': 'In the host console the host invites members, changes roles, removes members and reads the audit log.',
    'slot.error': '{name} cannot be shown',
    'slot.errorBody': 'Something went wrong in this panel. The connection and the other panels are not affected.',
    'slot.retry': 'Show again',
  },
  zhTW,
);
